### PR TITLE
Fix #7:Map resolve

### LINKED ISSUE #7: addtion of functionalities at services section
We can integrate this project with Google Maps API.
Upon interaction with clinics and blood bank cards, Google Maps API will provide some fake locations of hospitals and blood banks near the area produced by a user.
So, please assign me this issue to work under GSSoC '24.
Screenshot 2024-05-09 210919

### PR DESCRIPTION
**Pull request by kumar1397**
## Description

I used Leaflet with OpenStreetMap to add map functionality which upon receiving location input from user shows Rapidoc healthcare units near them.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #7 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/122858524/30738411-ad1e-4328-af95-ac3d9d77e941

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
@Anishkagupta04  @varshith257 
please consider this PR.

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
please make it more attractive and also bg colour is too much vibrant

**Comment by varshith257** [comment]
@kumar1397 Incorporate the changes requested

**Comment by kumar1397** [comment]
@Anishkagupta04 @varshith257 
 Sure, will complete very soon.

**Comment by kumar1397** [comment]
@Anishkagupta04 @varshith257 
please check the changes.

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution

**Pull request merged**
