### PR TITLE
✔️Improved the FAQ Page ( Fixed Navbar | Made Responsive )

### LINKED ISSUE #1138: ➕Enhancement: Improving the "FAQ Section" of the Website!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @varshith257 @Anishkagupta04 

I would like to enhance the UI and functionality of the current FAQ page to improve user experience.
Currently there are many issue with it 
- There's no Main Heading describing the purpose of the page 
- There's No Favicon to the Page
- The FAQ container is static and doesn't use any of the transitional or hovering effects

### Here's what I Will do:
- **Styling it to follow the Website's theme.**
- **Improve the "Accordian" Functionality** to be smooth transist.
- Will Make sure that **at a time** **only 1 answer should display** and others remain hidden
- **Update existing content and add new comprehensive questions** based on user feedback and common inquiries.
- **Adding transition moving effect to the FAQ sections questions.**
- Will **Add Hovering Text-Shadows to it,** so that it **will be engaging**.

**Current FAQ Section -** 

https://github.com/user-attachments/assets/b7be151e-51d4-4b37-80b3-86169a46351c

**For example like this - (my previous work)** 

https://github.com/user-attachments/assets/c89daa15-163c-47fb-824d-e31db4c10481

Please assign me under GSSOC'24.
Looking forward to contributing to our project!
thankyou!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @varshith257 @Anishkagupta04 
issue closes #1138 

I have Completely improved the FAQ Page of the website - 

- **Added a "Search-Functionality"** to **filter out the questions** the customer needs faster
- The Search Functionality **Will display all the Questions** **matching the entered input** even if it is a single character
- **Added Interactive Hovering Effects** to the questions and Answers 
- **Added Main Heading and Introductory paragraph** to let users know a bit about the page 
- **Added Text Shadow to highlight the Important one's**
- Made the **Complete FAQ Page "Responsive" for all screen sizes** 
- Added Favicon to the page 
image

### Additionally - 
- I Have **Fixed the Inconsistent navbar issues**
- I **added correct navigating links to the links in the navbar** to redirect to respective page
- **Made the nav responsive and hamburger will appear too.**

Here's the implementation - 

https://github.com/user-attachments/assets/1d9b2493-6803-4335-a812-629ec340450b

Please take a look and review it !
thankyou..

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aslams2020** [comment]
@varshith257 Please review it.
Thankyou

**Comment by varshith257** [comment]
Can you update branch and make success of netifly deployment?

**Comment by aslams2020** [comment]
@varshith257 Done!

**Comment by varshith257** [comment]
@aslams2020  Once see the navbar the mobile navbar element collided in it

**Comment by aslams2020** [comment]
@varshith257 Ohkay, sorry i missed that.
fixing it!

**Comment by aslams2020** [comment]
@varshith257 done! Please check


https://github.com/user-attachments/assets/f27c96f3-9f6d-4189-ba10-246ed441ba61

**Comment by aslams2020** [comment]
@varshith257

**Pull request merged**
