### PR TITLE
footer

### LINKED ISSUE #186: 💡[FEATURE]:A structured footer
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by P-lavanya16**
## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #186 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot (104)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
Remove these line from footer and above

**Review by Anishkagupta04 — COMMENTED** [review]
Line above copyright and above rapidoc

**Comment by varshith257** [comment]
@P-lavanya16 We have a good alignment of footer now:

image

**Comment by P-lavanya16** [comment]
@Anishkagupta04 ok

**Comment by varshith257** [comment]
Closing! As footer is now structured

**Pull request closed without merging**
