### PR TITLE
Improved UI of Doctors Page

### PR DESCRIPTION
**Pull request by abhishekdumaniya**
# Type of change 

- [ ] Added new project
- [x] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : #243  
* ### Short description : 
* changed the UI of the doctors

### CODE REVIEW

**Comment by varshith257** [comment]
Page color seems inconsistent what we using already

**Comment by abhishekdumaniya** [comment]
@varshith257 I will review the color scheme and ensure consistency across all pages If you have any specific examples or suggestions, please let me know...

**Comment by varshith257** [comment]
> @varshith257 I will review the color scheme and ensure consistency across all pages If you have any specific examples or suggestions, please let me know...

Maybe that blue color doesn't seem to be aligned with what already using

**Comment by abhishekdumaniya** [comment]
> > @varshith257 I will review the color scheme and ensure consistency across all pages If you have any specific examples or suggestions, please let me know...
> 
> Maybe that blue color doesn't seem to be aligned with what already using

@varshith257 I have added a picture. please review this picture.....

Screenshot 2024-05-21 140924

**Comment by abhishekdumaniya** [comment]
> Is this color aligned with home page color Schema?

@varshith257 The home page has this color which does not look good
Screenshot 2024-05-21 150551

It looks better than that

Screenshot 2024-05-21 140924

**Comment by Anishkagupta04** [comment]
Add details like this in the inbox

**Comment by abhishekdumaniya** [comment]
> 
> 
> Add details like this in the inbox

@Anishkagupta04 Well this is going to take some time......

**Comment by Anishkagupta04** [comment]
Take your timee👍

**Comment by abhishekdumaniya** [comment]
@varshith257 Can you merge my PR so that I can change some UI otherwise, a merge conflicts will occur

**Comment by abhishekdumaniya** [comment]
@varshith257 Can you merge this PR of mine because this page link is not available in the navbar of the home page and this is my pending PR please can you merge this PR of mine

**Comment by abhishekdumaniya** [comment]
@varshith257 Can you merge this PR?

**Comment by varshith257** [comment]
No activity! and updates of changes

**Pull request closed without merging**
