### PR TITLE
"Organizing all the files and making an exact replica of the Rapiddocs website"

### PR DESCRIPTION
**Pull request by rabinarayanpadhy07**
## PR Description
"Organizing all the files and making an exact replica of the Rapiddocs website
_Add your description_
organizing all the files and making exact replica of rapidocs websites
## Related Issues: Issue for which you are raising a PR for
#99 
- Closes #
I have fixed all the things on the website to exactly match RapidDocs."
### Issue
#99 
[Issue number or description]

### Checklist
**BEFORE**
Screenshot_20-5-2024_122329_127 0 0 1
**AFTER**\
Screenshot_20-5-2024_122712_127 0 0 1

- [x] I have gone through the [contributing guide](## PR Description

_Add your description_

## Related Issues: Issue for which you are raising a PR for

- Closes #

### Issue

[Issue number or description]

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by varshith257** [comment]
@rabinarayanpadhy07 Thanks for this

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL. Is this how website seems to look alike?

**Comment by rabinarayanpadhy07** [comment]
> @Anishkagupta04 PTAL. Is this how the website seems to look alike?

Could you take me to the contribution section

**Comment by Anishkagupta04** [comment]
@varshith257 yeah currently the website is looking like this need to modify much the alignment is all messed up 🥲

**Comment by varshith257** [comment]
@Anishkagupta04 Suggest the required changes

**Comment by Anishkagupta04** [comment]
Align the content below the heading please as it is right align

**Comment by varshith257** [comment]
> Align the content below the heading please as it is right align

@rabinarayanpadhy07

**Comment by rabinarayanpadhy07** [comment]
> > Align the content below the heading please as it is right align
> 
> @rabinarayanpadhy07

hey can you come to an google meet

**Comment by varshith257** [comment]
I am not pretty sure how could look alike because @Anishkagupta04 is PA and could be well known how this project look like

cc/ @Anishkagupta04

**Comment by varshith257** [comment]
> "Hey, can you come to a Google Meet to discuss about projects?"

I am not pretty sure how could look alike because @Anishkagupta04 is PA and could be well known how this project look like

cc/ @Anishkagupta04

**Pull request merged**
