### PR TITLE
Added "Customer Agreement" and "Terms and Conditions" Pages

### LINKED ISSUE #685: Feature 🌟: Add "Customer Agreement" and "Terms and Conditions" Pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 and @varshith257 

Here is the feature i want to suggest - 

To enhance the website's compliance and provide clear guidelines to users, 
I propose **creating two new pages:** **"Customer Agreement"** and **"Terms and Conditions."** 
[ These pages will be linked in the footer for easy access. ]

### What will i do ?

1. Create a "Customer Agreement" Page and will link it to existing text in the footer.
2. Create a "Terms and Conditions"  Page and Add text to the footer.

### Use Case

- The "Customer Agreement" text in the footer will be linked to a detailed customer agreement page.
- he footer will contain a new "Terms and Conditions" text linked to the respective page.
- Users will have easy access to important legal and usage information, improving transparency and trust.

Could you please assign me this issue under GSSoC'24?
### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Anishkagupta04 and @varshith257 ,
issue closes #685 

**Below are the Changes I Implemented -** 

-  I **Created two separate HTML pages** for "Customer Agreement" and "Terms and Conditions" and linked them into the footer links
- I tried my very best **to style the two pages** similar to the **website's color theme** so that visually it will look good to see.
- I **also added favicons** to both the pages as you can see in the video below.
- Additionally, I have included a footer at the end of both the pages to re-navigate to the "Home" page instead of changing the tabs manually.

Please take look to the video below - 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/8ce2ba31-c5d9-4e23-b8e8-67394a5d1123

@varshith257 Please review the changes and let me know if any adjustments are needed. Thank you!
I look forward to contribute tmore to your project.

## Type of PR
- [x] Feature enhancement

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aslams2020** [comment]
@Anishkagupta04 / @varshith257

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution

**Comment by aslams2020** [comment]
Please add the level and gssoc label as given in issue.

@Anishkagupta04, @varshith257 Thankyou for merging the PR. 
I Look forward to contribute more 😊

**Comment by aslams2020** [comment]
@Anishkagupta04  /  @varshith257

**Pull request merged**
