### PR TITLE
Made "Blood Test" Page Responsive 

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @varshith257  issue #894 

I have made the blood test page responsive (you can redirect to /test.html)

## Before

image

image

## After 

image

image

image

### Screenrecord

https://github.com/user-attachments/assets/ced58d2d-e2e4-4cc2-94d8-b538a5f97e0c

## Type of PR

- [x] Bug fix

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by varshith257** [comment]
@MastanSayyad Can the navbar align with the left and also need to update rapidoc logo with the text? @Anjaliavv51 @aditya-bhaumik Guide, through this recently merged Prs of you.

approve/request changes

**Comment by MastanSayyad** [comment]
@varshith257 understood!

**Comment by Anjaliavv51** [comment]
@MastanSayyad make the nav bar in small screen according to the below and place the logo as below inside the nav bar.

image


image

**Comment by Anjaliavv51** [comment]
@MastanSayyad after changes , please resolve the conflicts too.

**Comment by varshith257** [comment]
@MastanSayyad Also ensure the logo is replaced by text in navbar of how other prs of same issue added

**Comment by varshith257** [comment]
@MastanSayyad Any progress on this?

**Comment by MastanSayyad** [comment]
Yeah it's done @varshith257

**Comment by varshith257** [comment]
I can see only one line change?

**Comment by MastanSayyad** [comment]
@varshith257 I didn't commit yet

**Comment by MastanSayyad** [comment]
@varshith257 Who did the changes before in the Test.html file? Everything is messed up in it, Navbar footer, body content everything is misaligned and improper, every changes I made are completely broke now!

**Comment by varshith257** [comment]
I think @Anjaliavv51 has recent commits to test.html of adding mobile responsive.check it out at commit history of file

**Comment by MastanSayyad** [comment]
@varshith257 It is not responsive and the header navbar is completely gone, in mobile view there is no hamburger same goes to footer, but i have fixed it, only navbar has to be updated

**Comment by Anjaliavv51** [comment]
> @varshith257 It is not responsive and the header navbar is completely gone, in mobile view there is no hamburger same goes to footer, but i have fixed it, only navbar has to be updated 





@varshith257 what he said is crt , they r missing , the above screenshot are from the deploy link of the repo

**Comment by Anjaliavv51** [comment]
@MastanSayyad but in your code changes preview , their is no any view of navbar hamburger and footer social icons size is large.

**Comment by MastanSayyad** [comment]
> @MastanSayyad but in your code changes preview , their is no any view of navbar hamburger and footer social icons size is large.
> 
> 
> 
> 
> 
> 
> 

It's because I have merged and updated the latest branch

**Comment by Anjaliavv51** [comment]
@MastanSayyad sorry I didn't get u?

**Comment by MastanSayyad** [comment]
> @MastanSayyad sorry I didn't get u?

I mean In preview the changes are due to latest branch updates (there are no changes of mine yet as i didnt commit/push the changes)

**Comment by Anjaliavv51** [comment]
> > @MastanSayyad sorry I didn't get u?
> 
> I mean In preview the changes are due to latest branch updates (there are no changes of mine yet as i didnt commit/push the changes)

Okay then ,pls commit the changes.

**Comment by MastanSayyad** [comment]
Wait, I'm fixing the broken code, almost finished!

**Comment by MastanSayyad** [comment]
Hey @varshith257 I have fixed everything the page is now fully responsive 

image

image

image


### Screen Record


https://github.com/user-attachments/assets/aa0bf643-d856-45a1-b8d2-7fd69762c169

**Comment by MastanSayyad** [comment]
Hey @varshith257 @Anjaliavv51 @aditya-bhaumik review it, the page is responsive now!

**Review by Anjaliavv51 — APPROVED** [review]
Approved.

**Comment by Anjaliavv51** [comment]
@varshith257 changes are great merge the PR.

**Comment by MastanSayyad** [comment]
@varshith257 pls merge this PR

**Comment by varshith257** [comment]
@MastanSayyad Can you also align navbar elements? I can see they are misaligned in the navbar

**Comment by MastanSayyad** [comment]
> @MastanSayyad Can you also align navbar elements? I can see they are misaligned in the navbar

@varshith257 It's done now!

image

**Review by Anjaliavv51 — APPROVED** [review]
Approved 
@MastanSayyad Done a Great Job!

**Comment by Anjaliavv51** [comment]
@varshith257 changes are great it can be merged.

**Comment by varshith257** [comment]
Thanks @MastanSayyad and @Anjaliavv51  for following up on this

**Pull request merged**
