### PR TITLE
Label Addition

### LINKED ISSUE #991: 📝[Documentation Update]: Bug , Enchancement and Documentation label to Issues & PR.
Automatic Addition of Bug , Enchancement and Documentation label to Issues

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#991

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #991 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR 
"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

Automatic label addition is added to both the issues and PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR
"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

Automatic label addition is added to both the issues and PR.

**Review by varshith257 — APPROVED** [review]

**Comment by Anjaliavv51** [comment]
@varshith257 
"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

Automatic label addition is added to both the issues and PR.

**Comment by varshith257** [comment]
I am viewing in mobile. Let me add make changes when I am with my desktop

**Comment by Anjaliavv51** [comment]
> @varshith257 please review the PR "Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions". Make sure to do the above after PR merging.
> 
> Automatic label addition is added to both the issues and PR.

@varshith257 please do this the only changes will be done.

**Comment by Anjaliavv51** [comment]
> I am viewing in mobile. Let me add make changes when I am with my desktop

okay

**Comment by Anjaliavv51** [comment]
> I am viewing in mobile. Let me add make changes when I am with my desktop

@varshith257 please merge the code and then

"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

Automatic label addition is added to both the issues and PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please merge the code and then

"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

Automatic label addition is added to both the issues and PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please merge the PR

**Comment by varshith257** [comment]
Is it working in your local branch?

**Comment by Anjaliavv51** [comment]
@varshith257 yes

**Comment by Anjaliavv51** [comment]
@varshith257 look at the below ss
image

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by varshith257** [comment]
OK! Reopen it to get merged

**Comment by varshith257** [comment]
Have you deleted your fork?

**Comment by Anjaliavv51** [comment]
> Have you deleted your fork?

yes as it not updated.

**Pull request closed without merging**
