### PR TITLE
Implementing Multilingual support #514

### LINKED ISSUE #514: ✨[Feature Request]: Implementing Multilingual support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.
The below image is my last project where I made it available in different languages.

### Use Case

Increased Accessibility:

User Inclusivity: By supporting multiple languages, the project becomes accessible to a wider audience who may not be proficient in the primary language. This inclusivity ensures that users from different linguistic backgrounds can use and benefit from the project.
Improved Usability: Users can interact with the project in their native language, which improves their overall experience and satisfaction. This is particularly important for complex projects where understanding the content is crucial for effective use.
Global Reach:

Market Expansion: Multilingual support allows the project to be marketed and used globally. It opens up opportunities in regions and countries where the primary language is not spoken.
Diverse User Base: Attracting a diverse user base can provide richer feedback and insights, helping to improve the project based on varied user experiences and needs.
Enhanced Communication:

Better Support: Providing documentation, help files, and customer support in multiple languages can significantly improve the support experience for non-native speakers.
Community Engagement: Users are more likely to engage with the project and contribute to its community if they can communicate and collaborate in their preferred language.

### Benefits

Describe the solution you'd like
Implementing multilingual support in a project can significantly enhance its usability, accessibility, and reach. Here are several ways this feature could enhance the use of the project and the benefits it would bring to the project or community:

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Damini2004**
## Description

Multilingual support has been added in website.
## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #514 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/119414762/115c643b-7110-4d31-b9ea-9b220f8b6742

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/119414762/fb58525a-5778-4326-bf0c-f3cc7409f541

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Kindly review the PR

### CODE REVIEW

**Comment by varshith257** [comment]
@Damini2004 The language selection button could be in navbar ?

**Comment by Damini2004** [comment]
@varshith257 sure I will add it in navbar instead outside of the navbar. 
Any other changes ?

**Comment by Damini2004** [comment]
@varshith257 Kindly gothrough it changes commited.

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution

**Pull request merged**
