### PR TITLE
appointment page

### PR DESCRIPTION
**Pull request by bhumika-1127**
This is with respect to issue #170 which I was assigned.I have created an Appointment Page for for website which is triggered by "make an appointment button" on doctors page. @varshith257 @Anishkagupta04  I would request you to increase the level to level3 as it took a lot time and also I have added a JavaScript file for making it more dynamic.
image
image

### CODE REVIEW

**Comment by varshith257** [comment]
I think we can make this page some more visually appealing. What are your thoughts @Anishkagupta04 ?

**Comment by bhumika-1127** [comment]
This is the complete website. Are there any changes required @varshith257 @Anishkagupta04. You can suggest them, i will look into it. 
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/137604220/353a673d-a3a5-4e29-9a05-5c5370a29fab

**Comment by bhumika-1127** [comment]
@Anishkagupta04 I have resolved the conflict that occured. Kindly accept the Pull Request to incorporate the changes.

**Comment by bhumika-1127** [comment]
@Anishkagupta04 Kindly let me know how can I help you. It's been 2 days my pull request in yet not accepted.

**Comment by Anishkagupta04** [comment]
Add an option for Hospital selection

**Comment by Anishkagupta04** [comment]
You can refer this images it seems preety good idea aur if you can do something like this

**Pull request merged**
