### PR TITLE
fixed login and username 

### LINKED ISSUE #700: 🐞[Bug]: without account creation login is sucessfull
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Login is still sucessfull even if account is not created.

### Expected behavior

login should be after sign up only 

### Add ScreenShots

Screenshot 2024-06-25 124537

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Subhams-GIT**
## Description
1. fixed login where without signup login was sucessfull.
2. fixed username.
3. added expiry time.

## Related Issues
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #700 

## Type of PR

- [*] Bug fix
- [*] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot (361)
Screenshot (360)
Screenshot (359)
Screenshot (358)

-[*] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [* ] I have updated my branch and synced it with project `main` branch before making this PR
- [* ] I have performed a self-review of my code
- [* ] I have tested the changes thoroughly before submitting this pull request.
- [ *] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
firebase config needs to be changed
Screenshot 2024-07-08 221804

### CODE REVIEW

**Comment by Subhams-GIT** [comment]
Pls review this asap either there will be again merge conflicts.

**Comment by varshith257** [comment]
@Subhams-GIT Can you fix the merge conflicts and tag me?

**Comment by Subhams-GIT** [comment]
Sure but pls review it else ther would be again conflicts

**Comment by varshith257** [comment]
Ok fix conflicts and tag me

**Comment by Subhams-GIT** [comment]
@varshith257 pls check this

**Comment by varshith257** [comment]
@Subhams-GIT Can you tag me after fixing conflicts?

**Pull request closed without merging**
