### PR TITLE
Successful-Appointment

### PR DESCRIPTION
**Pull request by CS251000**
Screenshot 2024-05-14 at 1 20 42 PM

Solves issue #20 
Successful appointment will redirect to this message page with a button to navigate to the home page for better user experience.
The user will no longer be ambiguous about the success of the booking of the appointment

### CODE REVIEW

**Comment by varshith257** [comment]
@CS251000 I think we can enhance the UI of page more

**Comment by CS251000** [comment]
@varshith257 mostly these message pages after booking something are minimal to display the message and render back to the home page

Baki i am open to suggestions if you want anything in particular

**Comment by varshith257** [comment]
Okay, We are planning of migration of codebase to React and can improve there the UI

**Review by varshith257 — APPROVED** [review]
LGTM

**Pull request merged**
