### PR TITLE
made counts and feature section on the landing page responsive

### LINKED ISSUE #364: ✨[Feature Request]: Counts Section is not a properly aligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The width is not proper 

Screenshot (361)

It can fixed 

Screenshot (362)

### Use Case

It will lead to better layout 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Pruthaa17**
#364

made counts and feature section on the landing page responsive

- Closes #364 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

**### _EARLIER :_** 

Screenshot (397)
Screenshot (398)
Screenshot (399)
Screenshot (400)
Screenshot (401)
Screenshot (402)

### **_AFTER MAKING CHANGES_** 

Screenshot (405)
Screenshot (406)
Screenshot (407)
Screenshot (408)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@Pruthaa17 Can you give some more gap between elements here?

image

**Comment by varshith257** [comment]
And rest everything is fine

**Comment by Pruthaa17** [comment]
@varshith257 

Screenshot (409)

**Comment by Pruthaa17** [comment]
Can you add label (level) to this pull request @varshith257

**Comment by varshith257** [comment]
@Pruthaa17 What is your expected level for it?

**Comment by Pruthaa17** [comment]
> @Pruthaa17 What is your expected level for it?

Perchance 3 ?? Because I worked on 2 sections simultaneously and also made them responsive !

**Comment by Pruthaa17** [comment]
@varshith257 If I raised a issue for database connection for forms and various registrations which would you prefer ? MySQL or MongoDB

**Comment by varshith257** [comment]
@Pruthaa17 Ok! I will add `level3` to this PR as your expected level. Here's a small task for you. You have correctly pointed to our current planning of backend support for this project

PostgreSQL is one I prefer as I worked with three of these dbs.  But I can't say we use this only for our project as every usecase has other preferences over dbs in projects. Submit a report of your findings, why we prefer PostgreSQL for our project, and why not MongoDB and MySQL. Pros and cons of them and what you are suggesting to use finally based on your research?

I believe finally it could be worth it for both your curiosity about staying up to date with industry trends and project tech. If you have any queries or encounter any roadblocks in decision-making, ping me at discord/linkedin.

**Comment by varshith257** [comment]
@Anishkagupta04 FYI, I have added level3 for the my above comment

**Comment by Pruthaa17** [comment]
Thanks , For putting up this discussion of preferences of Dbs. Previously I found most of the projects using using MySQL and MongoDB so I didn't bothered about PostgreSQL but the fact the it is  one of the mostly used DB for open source contribution !! 

Thanks for the task it was indeed helpful !!

**Pull request merged**
