### PR TITLE
feat: Improved UI Functionality and Integrate Star Rate System in the Feedback Form

### LINKED ISSUE #759: ➕Enhancement: Improving "UI and Functionality" Of the Feedback Form
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 and @varshith257,

Here is the the Enhancement I Propose to do - 
Currently, the feedback form on the website **requires improvements to enhance user experience and functionality.** 
I **want to make several enhancements** to the form to align it **better with the website theme** and improve usability.

Here is the current Feedback page - 

image

### Here's What Will I Do - 

1. **UI Enhancement:** **Update the UI to match the website theme** for consistency and better user experience. 
2. **Rating System:** Modifying the **Rating system** to make it more intuitive and user-friendly.
3. **"Custom Success Popup":** Implement **a custom popup to notify users** upon successful form submission.
4. **Real Email Sending Integration:** Integrate real email sending functionality using Formspree.io to notify the admin of new feedback submissions. (This is a great functionality to add )
5. Styling the Current "Submit" Button with much better Hover Effects! 
6. Additionally, **I will try to add animations** wherever Needed.

I hope I was able to explain you the solution.
Please assign me this issue under GSSoC'24.

### Use Case

If the feedback form itself has a creative UI and engaging functionalities, The user will tend to give feedbacks about the website often times.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Anishkagupta04 and @varshith257 
issue closes #759 

I Have Updated and improved the Complete feedback form.

### Below Are The Changes I Implemented
1. **Changed Complete Alignment and UI of the feedback** form to look visually appealing.
2. I **Added a dynamic Rating system** using emojis (😡, 😒, 😐, 😊,😁) **to reflect user sentiment rating** 1,2,3,4,5 respectively.
3. Added a **"Custom Success Popup"** (a popup to notify users upon successful form submission.)
4. **Tried my very best** to style the form **to follow the website theme.**
5. **Added a "Reset Form Functionality"** so that After Submit the Existing data gets reset for next one.
6.  **tried to added animations** wherever Needed.
7. **Styled the Current "Submit" Button** with much better Hover Effects!

**Here is the Video -** 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/39b4d1fd-a4f8-45ed-9078-1f1c60905d7b

If the feedback form itself has a creative UI and engaging functionalities, The user will tend to give feedbacks about the website often times.

Please take a look and review it.

## Type of PR
- [x] Feature enhancement

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by varshith257** [comment]
The appointment for is still misaligned

**Comment by aslams2020** [comment]
@varshith257, My assigned work was to Improve "Feedback Form".
I think someone already generated PR for that appointment form alignment.

**Comment by varshith257** [comment]
Will look into it

**Comment by varshith257** [comment]
@aslams2020 The color scheme of changes should align with the home page color scheme look at it. Update hex codes that to align with home page colors

**Comment by aslams2020** [comment]
@varshith257 Done!

**Comment by varshith257** [comment]
@aslams2020 Hexcodes are mismatching take a reference from other sections. The bg-color to be dark green hex used in other sections

**Comment by aslams2020** [comment]
@varshith257 Done!

**Comment by varshith257** [comment]
All emojis are same. Instead replace with star rating system better

**Comment by varshith257** [comment]
If you incorporate them too will award level 3

**Comment by aslams2020** [comment]
@varshith257 Done! Please take a look.

**Comment by varshith257** [comment]
Thanks! @aslams2020

**Pull request merged**
