### PR TITLE
Fixes issue #949

### LINKED ISSUE #949: Validating Email
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Validating email, register the user if the entered email is valid.

### Use Case

Free from unauthorized login.

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
Validation of email

Validation of email using firebase, that ensures user to register if the entered email is valid email.
Verification is done by sending a verification email.

Prevent from unauthorized access.
- Closes #949 

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [X] Documentation update

## Screenshots / videos (if applicable)
https://drive.google.com/file/d/1zmcGU6QB116CPJx0EuJAt3UaOYnscRkS/view?usp=drive_link

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
I have forked the repository again and made the necessary changes. Even though everything is up to date, the branch still has conflicts. Can you please resolve these conflicts?

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
I've completed the work. Please review the PR and assign the appropriate labels. Thank you.

**Review by varshith257 — APPROVED** [review]

**Comment by Bhattu-Anitha-07** [comment]
Thank you @varshith257 
Will contribute more.

**Comment by Bhattu-Anitha-07** [comment]
Please assign issue no. #944 to me.
Thank you

**Pull request merged**
