### PR TITLE
Text color change for subscribe button

### PR DESCRIPTION
**Pull request by Soujanya2004**
## Description

changed text color in footer for subscribe button
issue number- 914

## Type of PR

- [x] Bug fix
Screenshot (130)

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [X ] I have performed a self-review of my code
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by varshith257** [comment]
@Anjaliavv51 @aditya-bhaumik PTAL

**Comment by Anjaliavv51** [comment]
@Soujanya2004 please fill the PR correctly(Missing of check box(

**Comment by Anjaliavv51** [comment]
@Soujanya2004 please changes the color mentioned in issue for all the html pages in the repo

**Comment by Soujanya2004** [comment]
@Anjaliavv51 sure i will change

**Comment by varshith257** [comment]
Closing in favour of #932

**Pull request closed without merging**
