### PR TITLE
Improvement of navbar in "Find a doctor" page and "News" page 

### LINKED ISSUE #1041: 🐞[Bug]: Improvement of navbar in "Find a doctor" page and "News" page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello PA,
The navbar on the "Find a Doctor" page is not styled properly. Additionally, the nav items on the "News" page are not aligned correctly.

### Expected behavior

Proper alignement and styling of navbar.

### Add ScreenShots

Before:
image
image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
## Description
Enhanced the UI for the navbar on the News page.
Implemented proper navigation for the navbar links on the News page.
Replaced the "Rapidoc" text in the navbar with an icon.
Added a background color to the "Find a Doctor" button.

## Related Issues

- Closes #1041 

## Type of PR

- [X] (Buf Fix)

## Screenshots / videos (if applicable)

Before:
image
After:
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 @Anishkagupta04 
Please review this PR.
Thank you.

**Comment by varshith257** [comment]
@aditya-bhaumik  Take a look

**Review by aditya-bhaumik — COMMENTED** [review]
image
The news page is not working properly please check in the deploy @Bhattu-Anitha-07

**Comment by Bhattu-Anitha-07** [comment]
Ok @aditya-bhaumik

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 @aditya-bhaumik 
Please review the changes I made.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 @aditya-bhaumik 
Please review this PR.

**Pull request merged**
