### PR TITLE
Animated emoji Addition

### LINKED ISSUE #995: ✨[Feature Request]:  Animated Emoji addition
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Animated Emoji addition

### Use Case

Animated Emoji addition

### Benefits

Animated Emoji addition

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Damini2004**
## Description

Animated emoji Addition

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #995 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Damini2004** [comment]
@varshith257  review it.

**Comment by Damini2004** [comment]
@varshith257 kinldy review and merge it.

**Comment by varshith257** [comment]
@Damini2004 Solve conflicts and tag me for quick review

**Comment by Damini2004** [comment]
@varshith257  Does the conflicts get resolved ?

**Comment by Damini2004** [comment]
@varshith257 review it.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
