### PR TITLE
Made the Book An Appointment page responsive .

### PR DESCRIPTION
**Pull request by meetarora10**
## Description
Made the Book An Appointment page responsive .
## Related Issues
#894
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (744)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by meetarora10** [comment]
@varshith257 please review this .

**Comment by meetarora10** [comment]
@varshith257 kindly review this PR.

**Comment by varshith257** [comment]
@Anjaliavv51 Could you look into it ?

/approve or request any changes

**Comment by Anjaliavv51** [comment]
@meetarora10 please align the bottom footer text 

image

**Comment by meetarora10** [comment]
Sure @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@meetarora10 remove that copy code sentence

**Review by Anjaliavv51 — APPROVED** [review]
Approved

**Comment by Anjaliavv51** [comment]
@varshith257 changes are good PTAL and merge the code.

**Comment by meetarora10** [comment]
Screenshot (868)
@varshith257 @Anjaliavv51 done as you said .

**Comment by Anjaliavv51** [comment]
@meetarora10 place the social favicons after follow us , not below the follow us

**Comment by meetarora10** [comment]
@Anjaliavv51 done .
Screenshot (869)
Screenshot (870)

**Comment by meetarora10** [comment]
@varshith257 please have a look.

**Review by Anjaliavv51 — APPROVED** [review]
Icons are aligned everything is good approved.

**Pull request merged**
