### PR TITLE
✨[feature request]:Wanted to replace a share button instead of Social icons

### LINKED ISSUE #428: ✨[feature request]: Redesigning of Footer for Better User Experience
Toggle Share Button from this

To this

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/abbf18c9-2a23-4bcf-a50f-83788511dacc

### PR DESCRIPTION
**Pull request by Anjaliavv51**
… icons

Resolves #428

## Description

Replaced a share button to Social icons.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 @Anishkagupta04 please review the changes , replacement of toggle share button instead of Social Icons.

**Comment by Anjaliavv51** [comment]
@varshith257 as u stated hover is also applied

**Review by Anjaliavv51 — COMMENTED** [review]
Review

**Comment by varshith257** [comment]
Better if we align as below reference by adding a Follow Us Section and keeping button in a way that splitting doesn't breaks by overlapping and also reduce some size of that button to align cleanly in footer

image

**Comment by varshith257** [comment]
@Anjaliavv51 I will review all of your issues and PRs by EOD

**Comment by Anjaliavv51** [comment]
@varshith257 okay

**Comment by Anjaliavv51** [comment]
@varshith257 please review my PR

**Comment by varshith257** [comment]
Any image or video of changes?

**Comment by Anjaliavv51** [comment]
> Any image or video of changes?


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/265e6c2c-02a6-4881-bea2-11e4baf058c5

**Comment by Anjaliavv51** [comment]
@varshith257 please check it

**Comment by varshith257** [comment]
Better if we add a Follow Us Section and align this button there as in attached image https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/459#issuecomment-2153748896

**Pull request closed without merging**
