### PR TITLE
error 404 page

### PR DESCRIPTION
**Pull request by taneeshaa15**
Error 404 page:

pr3

Hi, @Anishkagupta04 @varshith257 ,
I hope you're doing well. I've addressed the issue #442 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Also, please assign the label according to my work, before merging.

Best regards,
Tanisha Garg

### CODE REVIEW

**Comment by taneeshaa15** [comment]
@Anishkagupta04 @varshith257 Please review it and give your valuable feedback.

**Comment by varshith257** [comment]
Can be header of the name Rapidoc be aligned to the right corner?

**Comment by taneeshaa15** [comment]
sure

**Comment by taneeshaa15** [comment]
@varshith257 @Anishkagupta04 Logo has been fixed, please review it.
Thanks

**Comment by taneeshaa15** [comment]
Hi @varshith257 @Anishkagupta04 ,
The header is aligned to right corner as you said.
I request you to review it once again and give your valuable feedback.

Updated Header:
final logo fixed

Best regards,
Tanisha Garg

**Pull request merged**
