### PR TITLE
Adjust emergency button size for better visibility

### LINKED ISSUE #40: please add label for GSSoC24
please add label for GSSoC24

_Originally posted by @lavshashank in https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/issues/38#issuecomment-2105669700_

### PR DESCRIPTION
**Pull request by tiashamaitra**
## Description

Adjusted the size of the emergency button from 16px to 30px for highlighting it.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #40 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by tiashamaitra** [comment]
Hi @Anishkagupta04 @projectmaintainer,

This pull request includes the implementation of OAuth for secure login, addressing issue #40. This contribution is part of the GirlScript Summer of Code (GSSoC) 2024.

Could you please add the `GSSoC` label to this pull request?

Thank you!

Best regards, [Your Name]

**Comment by tiashamaitra** [comment]
Hi @Anishkagupta04 @projectmaintainer,

This pull request includes the implementation of OAuth for secure login, addressing issue #40 . This contribution is part of the GirlScript Summer of Code (GSSoC) 2024.

Could you please add the `GSSoC` label to this pull request?

Thank you!

Best regards, [Tiasha Maitra]

**Comment by Anishkagupta04** [comment]
please see into it again its somehow out of the screen a little bit

**Comment by tiashamaitra** [comment]
But just changed the font size so the span also expanded proportionally

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
