### PR TITLE
changed the service layout

### LINKED ISSUE #730: ✨[Feature Request]:  Re-design service page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current service page is not in accordance with the current theme.

### Use Case

Better UI is important for every website and helps the users

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Aligned the services page with the main website theme

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #730 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/ccad7209-bbca-4a1b-9ce2-4d199be13e39

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
@samarsajad Everything is good. Can fix this?

image


I think it got misaligned move Find out Little more to left

image


Here move text to upside and learn more could be down side the image in center and make sure add a div box to learnmore

**Comment by samarsajad** [comment]
Alright. I'll work on it

**Comment by samarsajad** [comment]
Made the chnages as requested. PTAl @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
@samarsajad Looks good to merge. You can also open a issue to make this page mobile responsive

**Review by varshith257 — APPROVED** [review]

**Comment by samarsajad** [comment]
> @samarsajad Looks good to merge. You can also open a issue to make this page mobile responsive

create the issue #845 . Please assign this to me @varshith257 @Anishkagupta04

**Pull request merged**
