### PR TITLE
update index.html, blood.html, doc.html as like mobile app

### PR DESCRIPTION
**Pull request by jayeshpandey01**
1. index.html (Home Page):
   "Experience seamless healthcare access with our mobile app's home screen. Instantly navigate to schedule appointments, check blood donation drives, or connect with doctors. Streamlined design ensures quick access to vital features."

2. blood.html (Blood Donation Page):
   "Join our community-driven blood donation initiative through our app. Locate nearby blood drives, register as a donor, or organize events. Simplified interface empowers users to save lives effortlessly."

3. doc.html (Doctor Directory Page):
   "Discover trusted healthcare professionals effortlessly with our app's doctor directory. Browse through a comprehensive list of specialists, filter by location, expertise, or availability. Connect with ease for personalized medical care."

### CODE REVIEW

**Comment by jayeshpandey01** [comment]
Screenshot 2024-05-12 142047
Screenshot 2024-05-12 142104
Screenshot 2024-05-12 142119

**Comment by Anishkagupta04** [comment]
to resolve conflicts before continuing.
Conflicting files
blood.html
doc.html
index.html
js/validate.js

**Comment by Anishkagupta04** [comment]
please use a better text font it is looking soo casual and informal

**Comment by varshith257** [comment]
@Anishkagupta04 Can you send your discord id?

**Comment by jayeshpandey01** [comment]
My discord I'd @pandey_jayesh

**Comment by jayeshpandey01** [comment]
> please use a better text font it is looking soo casual and informal

Done

**Comment by varshith257** [comment]
> @varshith257 discord id @anishkaguptacontributor

I have messaged you in discord. PTAL

**Comment by Anishkagupta04** [comment]
Kindly share the ss @jayeshpandey01

**Comment by varshith257** [comment]
@jayeshpandey01 Any updates?

**Comment by jayeshpandey01** [comment]
> Kindly share the ss @jayeshpandey01
 Apology for Delay Due to End Semester Exams

Screenshot 2024-05-18 174118
Screenshot 2024-05-18 174135
Screenshot 2024-05-18 174155

**Comment by Anishkagupta04** [comment]
Kindly view the changed website coz there are many chnges been done and now I can't merge this take a look to the website changes and then identify the error which you want to resolve

**Comment by varshith257** [comment]
@jayeshpandey01 Can pull the latest upstream and follow up on the progress of this PR

**Comment by varshith257** [comment]
@jayeshpandey01 Closing! No activity

**Comment by jayeshpandey01** [comment]
Hi Anishkagupta04,

Thank you for sharing the list of conflicting files
. I will resolve these conflicts before continuing with the project. I
appreciate your feedback regarding the text font, and I will make sure to
use a better font that aligns with the formal tone of the website.

Looking forward to working together on this project.
Best regards,
Jayesh Pandey

**Pull request closed without merging**
