### PR TITLE
Added Animated icon in Navbar and Footer links

### LINKED ISSUE #466: ✨[Feature Request]: Adding Animated icons in Footer and Navbar links
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will beautify the page after adding icons to it

### Use Case

.

### Benefits

_No response_

### Add ScreenShots

Screenshot (1939)

Screenshot (1941)

Screenshot (1942)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Description

[Please include a brief description of the changes or features added]

## Related Issues #466

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #466

## Type of PR

- [x] Feature enhancement

before

Screenshot (1939)

after

Screenshot (1941)

Screenshot (1943)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Hello @Anishkagupta04 
please review this PR and merge it

**Comment by SadafKausar2025** [comment]
Screenshot (1958)

**Comment by SadafKausar2025** [comment]
hello @varshith257 
I have removed icons from footer .
please review this PR and merge it

**Comment by varshith257** [comment]
Will review soon. I am viewing it in mobile so unable to find why lot of code has been deleted in PR

**Comment by SadafKausar2025** [comment]
I have also fixed the subscribe button which was not align properly before

Screenshot (1959)

**Comment by SadafKausar2025** [comment]
footer icons codes are deleted

**Comment by SadafKausar2025** [comment]
@varshith257 
yes footer links code are deleted

**Comment by SadafKausar2025** [comment]
hello @varshith257 and @Anishkagupta04 
I have resolved the conflict please merge my PR

**Comment by Anishkagupta04** [comment]
pleassee look into the footer its orientation is dismantle

**Comment by SadafKausar2025** [comment]
> pleassee look into the footer its orientation is dismantle

yes checking

**Comment by SadafKausar2025** [comment]
hello @Anishkagupta04 
please check now Is it correct?

**Comment by SadafKausar2025** [comment]
hello @varshith257  and @Anishkagupta04  
I have resolved the conflict
please merge it

**Pull request closed without merging**
