### PR TITLE
Added documentation file via upload

### LINKED ISSUE #9: Add Documentation
Documentation is missing, without any proper documentation it is hard to setup project in our system.
Assign me this task under GSSoC'24, I will implement it.

### PR DESCRIPTION
**Pull request by TejaswiKandunuri**
uploaded Rapidoc Healthcare documentation file

Closes #9

### CODE REVIEW

**Comment by TejaswiKandunuri** [comment]
@Anishkagupta04 @varshith257 i have added documentation, kindly view it and Give points to me.

**Comment by TejaswiKandunuri** [comment]
do you want me to convert that file into a .md file and add it.

**Comment by varshith257** [comment]
> do you want me to convert that file into a .md file and add it.

Yes, divide each section into different .md files and link then in introduction.md file for each section

**Comment by TejaswiKandunuri** [comment]
@varshith257  i hope everything is fine now.

**Comment by varshith257** [comment]
@TejaswiKandunuri I am merging it. Can you also open an issue and work there on some changes I will suggest there?  Open a blank issue with title fixes in the documentation. Thanks for your efforts in providing comprehensive documentation

**Comment by varshith257** [comment]
also can remove the docx file in the PR and post a link here of docs file maybe by uploading in gdrive

**Comment by varshith257** [comment]
> also can remove the docx file in the PR and post a link here of the docs file maybe by uploading in drive

@TejaswiKandunuri Can you follow up with this?

**Comment by TejaswiKandunuri** [comment]
> > also can remove the docx file in the PR and post a link here of the docs file maybe by uploading in drive
> 
> @TejaswiKandunuri Can you follow up with this?

Could you please clarify what you mean?

**Comment by varshith257** [comment]
Remove/delete the documentation.docx file in the PR and upload it in drive  and post a link here for the same

**Comment by TejaswiKandunuri** [comment]
here is the link [https://docs.google.com/document/d/148_SY1gwmCa2B4QYetmz6Z9WQuZyjJfUK3CX71iaD4E/edit?usp=sharing](url)

**Comment by varshith257** [comment]
@TejaswiKandunuri Thanks! Will follow up you in #341

**Pull request merged**
