### PR TITLE
A structured footer and section title into a visible

### PR DESCRIPTION
**Pull request by P-lavanya16**
## PR Description

_Add your description_
footer into a beautiful and understable in structured and added a colourfull to section titles

## Related Issues: Issue for which you are raising a PR for

- Closes #

### Issue
[186]
[Issue number or description]

### Checklist

- [x] I have gone through the [contributing guide](## PR Description

_Add your description_

## Related Issues: Issue for which you are raising a PR for

- Closes #

### Issue

[Issue number or description]

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by varshith257** [comment]
Can send screenshot of changes?

**Comment by P-lavanya16** [comment]
Screenshot (86)
Screenshot (87)

**Comment by P-lavanya16** [comment]
i have resolved conflicts but again its showing like these why 

> @P-lavanya16 Can you link the issue you solving with this PR?

i have linked the issue above

**Comment by P-lavanya16** [comment]
I linked the issue above in pr

**Comment by P-lavanya16** [comment]
How to fix it I resolved it again it's getting like this

**Comment by P-lavanya16** [comment]
Screenshot (101)
Now its done with conflicts

**Pull request closed without merging**
