### PR TITLE
Miss alignment in Appointment Page in Small Screen(bug)

### LINKED ISSUE #1107: Miss alignment in Appointment Page in Small Screen(bug)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Miss alignment in Appointment Page in Small Screen

### Expected behavior

Proper alignment without overflow 

### Add ScreenShots

Screenshot_20240801_204355_Chrome
Screenshot_20240801_204402_Chrome

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#1107

## Description

Added favicon for twitter correctly , aligned nav bar in large screen , aligned navbar and footer in small screen too.

## Related Issues

- Closes #1107 

## Type of PR

- [X] (bug)

## Screenshots / videos (if applicable)

image

image

image

image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR , adjustment is done in both small and large screens and also Auto Label PR is also updated.

**Comment by varshith257** [comment]
Netifly deploy failed? Update branch

**Comment by Anjaliavv51** [comment]
> Netifly deploy failed? Update branch 

@varshith257 sure.

**Pull request closed without merging**
