### PR TITLE
Enhanced About Us page

### PR DESCRIPTION
**Pull request by meghana9044**
Solved the issue #86.

### CODE REVIEW

**Comment by varshith257** [comment]
can you send the scr of changes

**Comment by meghana9044** [comment]
> can you send the scr of changes

@varshith257 Sir, I couldn't understand what you asked for?

**Comment by varshith257** [comment]
Newly added About Us page image

**Comment by meghana9044** [comment]
> Newly added About Us page image

It is not image sir, Its the code i changed.

index.html

<section id="about" class="about">
    <div id="blackbox">
    </div>
    <div id="content">
        <div class="content-box">
            <div id="darkbox"></div>
            <div id="lightbox"></div>
            <div class="vert-Text">About Us</div>
            <div class="text-box">
              <div class="mobtext">About Us</div>
                <h1>
                    What is RAPIDOC?
                </h1>
                <h2>
                  RapiDoc is an online platform which enables you to get information about your nearest hospitals and
                  healthcare facilities. It aims to address health-related issues. It is a one-stop destination for all your
                  medical needs.
                </h2>
                <h1>
                    Our Goal
                </h1>
                <h2>
                    We believe that booking a hosiptal appointment is unncessarily convoluted and our goal is to make it a hassle-free experience to all.
                    We provide services like HEALTH CHECKUPS, EMERGENCY WARDS.
                </h2>
            </div>
        </div>
    </div>
    </section>


style.css

.content-box {
  position: relative;
  width: 100%;
  height: 80vh;
  max-height: 800px;
  margin: auto;
  margin-top: 60px;
  background: #ebf2fa;
  border-radius: 8px;
  box-shadow: 0px 4px 19px -3px rgba(0, 0, 0, 0.25);
  overflow: hidden;
  display: flex;
  flex-direction: row;
}

.content-box {
  animation: fadeInAnimation ease-in-out 0.3s;
  /* animation-iteration-count: 1; */
  animation-fill-mode: forwards;
}
@keyframes fadeInAnimation {
  0% {
      opacity: 0;
  }
  100% {
      opacity: 1;
  }
}

#darkbox {
  position: absolute;
  height: 70%;
  width: 100%;
  left: -15%;
  top: -40%;
  background-color: #3fbcc0a4;
  transform: rotate(-25.16deg);
  z-index: 0;
}

#lightbox {
  position: absolute;
  height: 100%;
  width: 120%;
  bottom: 55%;
  overflow: hidden;
  background-color: #4e7770;
  transform: rotate(25.16deg);
  z-index: 0;
}

.vert-Text {
  font-style: normal;
  font-weight: 600;
  font-size: 56px;
  line-height: 84px;
  text-align: center;
  color: #000000;
  transform: rotate(-900deg);
  writing-mode: vertical-lr;
  margin: auto;
  width: 10%;
  display: inline;
  z-index: 10;
}

.text-box {
  width: 90%;
  display: inline;
  z-index: 10;
  text-align: right;
  padding: 35px;
  margin: auto;
}

h1 {
  font-weight: 600;
  font-size: 32px;
  line-height: 48px;
}

h2 {
  font-style: normal;
  font-weight: 400;
  font-size: 22px;
  line-height: 33px;
  margin-bottom: 10%;
}

.mobtext{
  display: none;
}

@media screen and (max-width: 650px) {
  h1 {
      font-size: 24px;
      line-height: 26px;
  }

  h2 {
      font-size: 18px;
      line-height: 28px;
  }

  .vert-Text {
      display: none;
  }

  #lightbox {
      position: absolute;
      height: 200%;
      width: 1200px;
      bottom: 20%;
      overflow: hidden;
      background-color:#3fbcc0a4;
      transform: rotate(35.16deg) translateX(50px);
      z-index: 0;
  }

  #darkbox {
      position: absolute;
      height: 600px;
      width: 800px;
      left: -85%;
      top: -45%;
      background-color: #3fbcc0a4;
      transform: rotate(-33.16deg);
      z-index: 0;
  }
  .mobtext{
      display: block;
      font-size: 40px;
      font-weight: 600;
      margin-bottom: 10%;
  }
  .text-box{
      width: 100%;
      padding: 20px;
      margin: 5% 0;
  }
}

@media screen and (min-height: 700px) and (max-width: 650px) {
  .text-box{
      margin-top: 10%;
  }
  h1{
      margin-bottom: 20px;
  }
  h2{
      margin-bottom: 45px;
      line-height: 30px;
  }
}

**Comment by varshith257** [comment]
I mean the compiled code page

**Comment by meghana9044** [comment]
> I mean the compiled About Us screenshot

Screen Shot 2024-05-15 at 7 52 40 PM

**Comment by varshith257** [comment]
Can make some consistent with project using colors?

**Comment by meghana9044** [comment]
@varshith257 Sir, can you also please check by other commit

**Comment by varshith257** [comment]
> @varshith257 Sir, can you also please check by other commit

Ok will combine both issues here in the PR and give you level 2/3 gssoc label. Let's wait for review from @Anishkagupta04 for About Us page

**Comment by meghana9044** [comment]
> > @varshith257 Sir, can you also please check by other commit
> 
> Ok will combine both issues here in the PR and give you level 2/3 gssoc label. Let's wait for review from @Anishkagupta04 for About Us page

okay sir, Thank You

**Review by Anishkagupta04 — COMMENTED** [review]
Didn't liked the about us page it can be more innovative

**Comment by meghana9044** [comment]
@Anishkagupta04 @varshith257 Check the about us page 

Screen Shot 2024-05-15 at 9 39 02 PM

**Review by Anishkagupta04 — COMMENTED** [review]
Try to use the Rapidoc logo in the about us page 
Provide ranking 
Add a section of rating the website

**Comment by meghana9044** [comment]
> Try to use the Rapidoc logo in the about us page Provide ranking Add a section of rating the website

@Anishkagupta04 already rating feature is assigned to somebody. This issue is only to add About Us page, but i will add the rapidoc logo in the about us page

**Comment by meghana9044** [comment]
> Try to use the Rapidoc logo in the about us page Provide ranking Add a section of rating the website

Should i create a logo or just the one which is on top of the website

**Comment by meghana9044** [comment]
Screen Shot 2024-05-15 at 11 43 01 PM

**Comment by Anishkagupta04** [comment]
Okay then just add the logo ig the logo is made by one of the contributor

**Comment by meghana9044** [comment]
> Okay then just add the logo ig the logo is made by one of the contributor

@Anishkagupta04 Mam, No PR's are there for logo

**Comment by meghana9044** [comment]
@Anishkagupta04 @varshith257 I have added the logo in the About Us page. Please check
Screen Shot 2024-05-16 at 1 35 56 AM

**Comment by meghana9044** [comment]
> @varshith257 Sir Please add label to this issue with small L and also please add me as assignee as I am working on this issue

@varshith257

**Comment by Anishkagupta04** [comment]
@meghana9044 if possible please refer to this link for an idea of how a about us page should look like 
http://www.indiahospital.in/AboutUs.aspx
https://www.maxhealthcare.in/about-us

**Comment by meghana9044** [comment]
> @meghana9044 if possible please refer to this link for an idea of how a about us page should look like http://www.indiahospital.in/AboutUs.aspx https://www.maxhealthcare.in/about-us

Yes mam, I have gone through the links and in those websites one page is dedicated to a specific feature but that's not the case in RAPIDOC. So sorry mam, but this is all i can do.

**Comment by varshith257** [comment]
> > @meghana9044 if possible please refer to this link for an idea of how a about us page should look like http://www.indiahospital.in/AboutUs.aspx https://www.maxhealthcare.in/about-us
> 
> Yes mam, I have gone through the links and in those websites one page is dedicated to a specific feature but that's not the case in RAPIDOC. So sorry mam, but this is all i can do.

Will need About Us page as same of @Anishkagupta04 suggestion. It's something could look like to be in our project

**Comment by varshith257** [comment]
@meghana9044 Converted to draft. Work on @Anishkagupta04 suggestions. It could be better

**Comment by varshith257** [comment]
> > @meghana9044 Converted to draft. Work on @Anishkagupta04 suggestions. It could be better IMO
> 
> Can you please accept by issue #132 

Can submit new PR just addressing the issue #132

**Comment by varshith257** [comment]
@meghana9044 Understood your frustration but the requirements have to be fulfilled for the issue. I have also faced similar issue waiting for our work to get merge fast but it this teaches us more when we go and work in production codebases.

**Comment by meghana9044** [comment]
> @meghana9044 Understood your frustration but the requirements have to be fulfilled for the issue. I have also faced similar issues waiting for our work to get merged fast but this teaches us more when we go and work in production codebases.

I had to create a new PR so deleted the forked one and again I forked the repository. No issues

**Pull request closed without merging**
