### PR TITLE
Feat/popup subscribe to newsletter and some bugs

### LINKED ISSUE #891: ✨[Feature Request]:  add popup when someone subscribe the website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

when someone subscribe the website a popup comes thanks for subscribing 

also increase the input box width 

### Use Case

thanks giving 

### Benefits

thanks giving message 

### Add ScreenShots

before : 

image

after : 

image

also popup for this 

Screenshot 2024-07-16 233933

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
## Description

1. hover on find out more 
2. input box of contach
3. popup on subscribing website 

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #891 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/b55e664c-a98b-47fa-bd76-ebc82a8619b4

Screenshot 2024-07-17 015650

https://github.com/user-attachments/assets/8db624ec-f4c6-4dba-8c2b-c1f6d030094b

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ANKeshri** [comment]
@varshith257 please review and merge my pr

**Review by varshith257 — COMMENTED** [review]
Why back to top code removed?

**Comment by ANKeshri** [comment]
> Why back to top code removed?

@varshith257 done please check now

**Comment by ANKeshri** [comment]
@ ihave solved the conflicts can you please review them and merge my pr

**Comment by ANKeshri** [comment]
> @ANKeshri Solve conflicts and good to merge

@varshith257 done

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
