### PR TITLE
Made the normal check up page responsive

### LINKED ISSUE #1002: 🐞[Bug]:  normal check up page is not mobile responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

normal check up page is not mobile responsive

### Expected behavior

it should be responsive for mobile and tablet screens

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description
made the normaL checkup page mobile responsive

## Related Issues

- Closes #1002 

## Type of PR

- [x] (Bug Fix)

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/1a7dea12-8e1c-4ffa-afcc-b99a8c865f42

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anjaliavv51

**Comment by Anjaliavv51** [comment]
Please interchange change the bottom follow us icons and the sentence 

Screenshot_20240730_190657_Chrome

**Comment by Anjaliavv51** [comment]
And also decrease the size of navbar

Screenshot_20240730_190807_Chrome

**Comment by samarsajad** [comment]
> Please interchange change the bottom follow us icons and the sentence
> 
> Screenshot_20240730_190657_Chrome

but it is like this only in the main website @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@samarsajad for this page pls change as I said , the page has changed by someone I am looking into that

**Comment by samarsajad** [comment]
> @samarsajad for this page pls change as I said , the page has changed by someone I am looking into that


https://github.com/user-attachments/assets/fc6a4e9a-f6e0-4ea2-b60a-762cef8724c0

made the changes @Anjaliavv51

**Review by Anjaliavv51 — APPROVED** [review]
Approved.

**Comment by Anjaliavv51** [comment]
@varshith257 changes good , it can be merged.

**Pull request merged**
