### PR TITLE
🐞[Bug]: Fixes Unify Footer and Navbar in the Blood Test Page

### LINKED ISSUE #753: 🐞[Bug]: Unify Footer and Navbar in the Blood Test Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Add the current navbar and footer of the home page to the blood test page

image

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #753 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/d90b78f0-db06-425e-ba2b-d3892f627779

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please preview the PR

**Comment by varshith257** [comment]
@Anjaliavv51 Keep consistent of footer what been used on homepage

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by varshith257** [comment]
@Anjaliavv51 Why font style is different from text style we use across the website

**Comment by Anjaliavv51** [comment]
@varshith257 it is due to the Bootstrap used by the previous user.
if we remove it then , font will be removed to whole css which are linked to the other html files.

**Comment by varshith257** [comment]
@Anjaliavv51 ok, raise an issue to fix it

**Comment by Anjaliavv51** [comment]
@varshith257 sure

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
