### PR TITLE
added navbar and footer to news.html file

### LINKED ISSUE #272: news.html does not have navbar and footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

news.html does not have a navbar and footer

### Expected behavior

I want to add a navbar and footer to the news file
Screenshot 2024-05-22 220221

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by abhishekdumaniya**
## PR Description

added navbar and footer to the news.html file

## Related Issues: Issue for which you are raising a PR for

- Closes #272 

### Issue

[272]

## Related Issues: Issue for which you are raising a PR for

- Closes #272 

### Issue

[272]

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by abhishekdumaniya** [comment]
@varshith257 ok

**Comment by abhishekdumaniya** [comment]
@varshith257 Have to scroll a bit, the footer is the same as the home page

Screenshot 2024-05-23 183238

**Review by Anishkagupta04 — COMMENTED** [review]
Not looking nicee

**Comment by abhishekdumaniya** [comment]
@varshith257, @Anishkagupta004. Can you give me an idea of the UI

**Comment by Anishkagupta04** [comment]
Please send ss

**Comment by abhishekdumaniya** [comment]
@Anishkagupta004 can you send me a UI?

**Comment by abhishekdumaniya** [comment]
@varshith257 Can you merge my PR so that I can change some UI otherwise, a merge conflicts will occur

**Comment by varshith257** [comment]
Pull the latest changes and footer looks good now

**Comment by abhishekdumaniya** [comment]
@varshith257 okay I saw it but why has the look of the navbar changed it doesn't look good please merge this PR of mine so that I can create a new PR and make other changes..............

**Comment by varshith257** [comment]
How's the navbar changes? Send ss

**Comment by abhishekdumaniya** [comment]
@varshith257 The current home page which has a navbar looks like this, there is no news tag inside it
Screenshot 2024-05-30 225337

But it looked like this

Screenshot 2024-05-30 225712

**Comment by varshith257** [comment]
Haven't noticed which PR made it. Will look at the culprit PR that merged for making these changes? I will revert that PR

**Comment by abhishekdumaniya** [comment]
@varshith257 If you want, you can merge this PR of mine, and then I will solve the problem related to the navbar and small UI of the home page...

**Comment by varshith257** [comment]
Okay

**Comment by varshith257** [comment]
Is footer is fine of merged with new PR? Or it also got messed up

**Comment by abhishekdumaniya** [comment]
@varshith257 The footer looks good but has a small spelling error
Contact Us TYPO ---> Contact

I have a small request for you please check the PR and merge the UI of the whole website is not looking good
Please merge this PR so that I can make future changes and create the best website UI
Thank You...............

**Comment by varshith257** [comment]
Create an issue and follow up on this bugs

**Comment by abhishekdumaniya** [comment]
@varshith257 Thank you so much...........

**Pull request merged**
