### PR TITLE
Added "Scroll Down Progress Bar" To The website 

### LINKED ISSUE #751: 🌟 Feature: Add a Scroll "Progress Indicator Bar"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 ,
I want to add a "Scroll Down Progress Bar"

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.

### Use Case

The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### Add ScreenShots

****Progress Bar like:****

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Tejashri-Taral**
Hey @Anishkagupta04 and @varshith257 ,
 issue closes #751 

I have added the Scroll down progress bar in All pages of the website

******Screenshot******

image

******Type of PR******
 Feature enhancement

Please take a look and review it

### CODE REVIEW

**Comment by varshith257** [comment]
@Tejashri-Taral It's already present I think. Can you verify?

**Comment by Tejashri-Taral** [comment]
@varshith257 , I have added you the scrollbar in all the missing pages like privacy policy,terms and conditions, customer agreement, news, derma and appointment etc . You can check and review it.

**Comment by varshith257** [comment]
@Tejashri-Taral Please make sure the hex color of the scroll down progress bar is the same as the home page one . Except this looks good to merge

**Comment by Tejashri-Taral** [comment]
@Anishkagupta04 and @varshith257 ,done with the progress bar with same color as home page

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
