### PR TITLE
solves issue #521

### LINKED ISSUE #521: 🐞[Bug]: logo in Faq.Html page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is no logo showing in Faq.html page and the upscroll button is not working and I would like to add some changes in Footer like adding links to the So, that when clicked on the Faq's it'll open Faq page or When clicked on signup It's redirected to the Signup page 

before 
image

I would Like to fix this issue 

### Expected behavior

the expected behavior, there should be a logo showing in faq page and when clicked on the links in footer page it should be directed to the concern pages and when clicked on the scrolled button it should be directed to the top page of faq's page 

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by slytechiefrommagentashore**
## Description
I made changes such that the logo and the up-scroll button is working in Faq.html file and I made chanegs in dex.html file so, that the images appear.  
 I also made changes in footer such that when links are clicked in footer page it'll be redirected to that page (changes made in faq.html and index.html page)

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #521

## Type of PR

- [ ] Bug fix
issue number #521 

## Screenshots / videos (if applicable)
before it's there is no logo, 
after changes made 
image
the scroll button is working 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/97241435/8d03ba5d-8a27-4701-8099-a47e12ee172b

## Checklist

- [ X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [ X] I have performed a self-review of my code
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
The changes I made are in faq.html file and Index.html file,dex.html 
additionally when I'm checking the code I saw there are 3 appointment.html files. (appointment.html, aptmt.html and Html/appotiment.html) , requesting you to check.

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
footer is too small

**Comment by slytechiefrommagentashore** [comment]
Hello Madam, I didn;t change any css of the footer, It's already there before, if you want me change the footer I'll raise a new issue  , 
I just made changes in footer such that When clicked on the links in the footer, It'll be redirected to the page for faq.html page's footer.

**Comment by Anishkagupta04** [comment]
okay

**Comment by Anishkagupta04** [comment]
only in faq page the footer is small on website its fine the page you made ig that has the footer alignment wrong

**Comment by varshith257** [comment]
@slytechiefrommagentashore Incorporate changes requested and resolve conflicts

**Comment by slytechiefrommagentashore** [comment]
hello, @varshith257 , I have resolved the conflicts

**Pull request closed without merging**
