### PR TITLE
Updated find a doctor page

### LINKED ISSUE #545: ✨[Feature Request]: Improvement in the find a doctor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Screenshot 2024-06-13 at 11 29 41 AM
The logo of rapidoc is missing and I can add styling to the find a doctor page by adding them in a separate cards so the Ui of the page look good .

### Use Case

By adding logo and adding various styling features to make improvement in Ui .

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by DiwareNamrata23**
## Description
Added icon and improved the required styling for hovering and made the font size visible .
[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #545 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-06-13 at 3 09 51 PM

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@DiwareNamrata23 Instead, can you add the details of every doctor like image, etc...for every doctor?

**Comment by DiwareNamrata23** [comment]
yes sure

**Comment by DiwareNamrata23** [comment]
added images and specifications please view @varshith257 and let me know the changes

**Comment by DiwareNamrata23** [comment]
@varshith257 please review the pr

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
