### PR TITLE
Update auto-comment-on-pr-merge.yml

### LINKED ISSUE #359: 🐞[Bug]: Issue in autocommenting on merged pr
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message
Screenshot 2024-05-28 at 11 21 42 PM
Please let me work on this

### Expected behavior

to get the autocomment on the merged pr

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anshika14528**
## Description

i updated and changed the comment POST code. I have also tested this on my local repository and it worked.

## Related Issues #359

- Closes #359

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-05-28 at 8 25 20 PM

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@Anshika14528 I will merge this PR and test your approach. It looks fine for me to give write permissions and PR_target

**Comment by varshith257** [comment]
@Anshika14528 Thanks

**Comment by varshith257** [comment]
@Anshika14528 Can you also raise an issue and improve the PR comment workflow text:

image

This looks flaky. We need to improve this text.

**Comment by Anshika14528** [comment]
Ok

**Pull request merged**
