### PR TITLE
Enhance the contact page

### PR DESCRIPTION
**Pull request by ananyag309**
solved issue #492 
I have changed the contact form style a bit and added the functionality, confirmation message as well. @Anishkagupta04 ma'am or @varshith257 sir please have a look. also please add gssoc and level label. Thank you

earlier
earlier
now
noww

### CODE REVIEW

**Comment by varshith257** [comment]
@ananyag309 The submit button color could be the same of previous to align with current color scheme

**Comment by ananyag309** [comment]
@varshith257 done 
done

**Comment by varshith257** [comment]
Once check colors hex codes are different with existing one of submit button

**Comment by ananyag309** [comment]
@varshith257 done, now it looks much better

better

**Comment by varshith257** [comment]
Yes, it's good now

**Comment by ananyag309** [comment]
Thank you

**Pull request merged**
