### PR TITLE
Patient Section  responsive

### LINKED ISSUE #894: [ Priority] Make Website Mobile Responsive
We are introducing a new series of issue. It works as parent issue for all. 

**Requirements:**

1) Make all pages mobile responsive 
2) Navbar of every page should align with home page and mobile responsive 
3) Footer also need to be align with the homepage footer.
4) Every change should adhere to color scheme of website.

**Note:**

- This works as parent issue. Don't ask for assign. 

- Submit a PR directly with appropriate changes to make a page mobile responsive.

- Each contributor can submit any number of PRs. Each for a page to make mobile responsive.

-  Each PR will be awarded level 3 for it.

### PR DESCRIPTION
**Pull request by Damini2004**
## Description

Patient Section  responsive

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
image
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Damini2004** [comment]
@varshith257  review the PR

**Comment by Damini2004** [comment]
@aditya-bhaumik @varshith257 Review the PR

**Review by varshith257 — APPROVED** [review]

**Comment by Damini2004** [comment]
@varshith257 kindly merge it

**Comment by varshith257** [comment]
@Damini2004 Can you resolve conflicts and tag me?

**Comment by Damini2004** [comment]
@varshith257 kindly merge it and increase the level as it was mentioned as level3.

**Pull request merged**
