### PR TITLE
Improved UI of the form in patient portal

### PR DESCRIPTION
**Pull request by Wafmulla**
#210 issue resolved
This PR improves the UI of Patient Portal
I have improved the UI of the form also added hover effects.

Screenshots of updated UI:
Screenshot 2024-05-21 112611

Screenshot 2024-05-21 112643

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes
- [ ] Part of GSSOC
- [ ] Tested for any breaking changes
- [ ] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [ ] I Agree

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
Kindly add this box below the heading

**Comment by Wafmulla** [comment]
Ok

**Comment by Wafmulla** [comment]
I have made the changes suggested
image

**Comment by varshith257** [comment]
Resolve conflicts

**Comment by varshith257** [comment]
@Wafmulla any updates on this? LGTM with incorporating the @Anishkagupta004 's suggestions

**Comment by varshith257** [comment]
No activity

**Pull request closed without merging**
