### PR TITLE
Fix #7 : Map resolve

### LINKED ISSUE #7: addtion of functionalities at services section
We can integrate this project with Google Maps API.
Upon interaction with clinics and blood bank cards, Google Maps API will provide some fake locations of hospitals and blood banks near the area produced by a user.
So, please assign me this issue to work under GSSoC '24.
Screenshot 2024-05-09 210919

### PR DESCRIPTION
**Pull request by kumar1397**
## PR Description

I used Leaflet with OpenStreetMap to add map functionality which upon receiving location input from user shows Rapidoc healthcare units near them.

## Related Issues: Issue for which you are raising a PR for

- Closes #7 

### Issue

[Addition of map functionality at services section]

### Checklist

- [x] I have gone through the [contributing guide](## PR Description

_Add your description_

Suggest any other changes or issues if raising

- Closes #7 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree
Screenshot 2024-05-21 122927
Screenshot 2024-05-21 174011

### CODE REVIEW

**Comment by kumar1397** [comment]
@Anishkagupta04 please check this PR.

**Comment by varshith257** [comment]
Send a video for this changes accessing it

**Comment by varshith257** [comment]
@kumar1397 Can resolve this duplication?

image

**Comment by varshith257** [comment]
No activivty

**Comment by varshith257** [comment]
Duplicate of #588

**Pull request closed without merging**
