### PR TITLE
image with site name on home page

### PR DESCRIPTION
**Pull request by Bhoovi333**
## Description
hi mam,
this is bhoovi,you assigned me an issue and isaid i am having exams and i will update yu after, so here i am.
this is my first pull request, i changed the homepage image where i feel name of our site is important.

many more changes to come.......

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@Bhoovi333 Looks good to merge after fixing conflicts and tag me once it done

**Comment by Bhoovi333** [comment]
@Anishkagupta04 yu can check now

**Comment by Bhoovi333** [comment]
@Anishkagupta04 please merge

**Comment by Bhoovi333** [comment]
@Anishkagupta04 tomorrow is the last day of gssoc'24 pr.... please merge asap with label

**Pull request closed without merging**
