### PR TITLE
Modified the navbar on the news page .

### LINKED ISSUE #837: 🐞[Bug]: Navbar on the news page is not responsive .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Navbar on the news page is not responsive . Also it is not similar to the home page navbar .

### Expected behavior

Assign this task to me and I can create a responsive navbar similar to homepage with a hamburger icon for smaller screens.

### Add ScreenShots

Screenshot (691)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by meetarora10**
## Description
I have made a completely responsive navbar on the news page with a hamburger icon which makes it properly aligned for different devices and also similar to the navbar on the home page . 

## Related Issues
- Closes #837

## Type of PR
- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (716)
Screenshot (717)
Screenshot (718)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by meetarora10** [comment]
@varshith257 please review this .

**Comment by meetarora10** [comment]
@varshith257 please take a moment to review this .

**Comment by varshith257** [comment]
@meetarora10 Can you open new issue for mobile responsive of news page there are alignment gao at right of page and footer too

**Review by varshith257 — CHANGES_REQUESTED** [review]
Can you also add icons in navbar of what we have in homepage?

**Comment by meetarora10** [comment]
> @meetarora10 Can you open new issue for mobile responsive of news page there are alignment gao at right of page and footer to
@varshith257 okay I will create a new issue for news page .

**Comment by meetarora10** [comment]
> Can you also add icons in navbar of what we have in homepage?

@varshith257 can you please tell me which icons are you talking about ? Navbar is similar to the home page .

**Comment by varshith257** [comment]
@meetarora10 The mobile navbar has icons for each name. Refer to home page navbar

**Comment by meetarora10** [comment]
> @meetarora10 The mobile navbar has icons for each name. Refer to home page navbar

ok

**Comment by meetarora10** [comment]
@varshith257 made the changes, now icons are also visible .

**Comment by meetarora10** [comment]
@varshith257 review this

**Comment by varshith257** [comment]
@meetarora10 Small fix instead logo we just replace with RAPIDOC name check in this PR and good to merge after fixing this

**Comment by varshith257** [comment]
https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/895

**Comment by meetarora10** [comment]
Ok @varshith257

**Comment by meetarora10** [comment]
Screenshot (742)
@varshith257

**Comment by meetarora10** [comment]
In every navbar the logo is to be replaced by this text ? @varshith257

**Comment by meetarora10** [comment]
@varshith257 please merge this now.

**Comment by varshith257** [comment]
> In every navbar the logo is to be replaced by this text ? @varshith257 

Yes in mobile responsive

**Comment by varshith257** [comment]
@meetarora10 

nit: It could be good if we add small gap between icon and the text in navbar

**Comment by meetarora10** [comment]
@varshith257 done.
Screenshot (749)

**Comment by meetarora10** [comment]
@varshith257 merge this so that I can work on other issue.

**Comment by meetarora10** [comment]
@varshith257 .

**Comment by meetarora10** [comment]
@varshith257 this has not been merged yet.

**Comment by meetarora10** [comment]
Hey @varshith257 please merge this now.
Made all changes as you said.

**Comment by meetarora10** [comment]
@varshith257 please take a moment to merge this .

**Comment by meetarora10** [comment]
@varshith257 this PR is not merged yet . Please take a moment to merge this

**Pull request merged**
