### PR TITLE
There are few changes in the following sections:Make an appointment s…

### LINKED ISSUE #120: 🪲[Bug]: Alignment of cards in about section
**Description**
### Refrence Image
image

### PR DESCRIPTION
**Pull request by Amitesh-Mishra-AM**
…ection,Contact section,Feedback Section

## Description
I have enhanced the visual appeal of the website by arranging the sections, like giving perfect padding and margins which is required.

## Related Issues
None
- Closes #120

## Type of PR

- [x] Bug fix

### Before
image
image
image

### After
image
Gave a border to the section and a gap between the time slot and date.
image
The message button was not taking the full size so made it take the full area, and improved the visual appeal.
image
Made the section come in the center and also made the submit button look good.

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@Amitesh-Mishra-AM Can you also do for Mobile responsive?

**Comment by Anishkagupta04** [comment]
there is conflicting files please resolve

**Comment by Amitesh-Mishra-AM** [comment]
> there is conflicting files please resolve

The conflicting Issues have been resolved.

**Comment by Amitesh-Mishra-AM** [comment]
> @Amitesh-Mishra-AM Can you also do for Mobile responsive?

Yeah sure, assign me the issue.

**Comment by varshith257** [comment]
@Amitesh-Mishra-AM Assigned and resolve conflicts too

**Comment by varshith257** [comment]
No activity! Any updates

**Comment by Amitesh-Mishra-AM** [comment]
Sorry for the delay in my response. I tried working on the responsiveness of the website, but I faced difficulties due to the unorganized codebase. I have solved my previous issue and resolved the conflict that arose. Please check once more; however, if any conflict arises again, I will be happy to solve it. For now, I will not be able to work on the responsiveness of the page. Again, sorry for the delay in my response and for any inconvenience caused.

Please close this PR if everything is ok.

Thank you.

**Comment by varshith257** [comment]
@Amitesh-Mishra-AM Closing! There are many changes done after this PR was raised. We have recently removed the appointment section on the home page. Thanks! for your effort.

**Pull request closed without merging**
