### PR TITLE
Fixed Alignment Issues for Some Sections

### LINKED ISSUE #760: 🐞[Bug]: Alignment and Responsiveness Issues For Some Sections
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @varshith257 

I would like to fix the alignment issues as well as responsiveness issues in the website sections

Such as 

### Contact us section form

image

### Appointment section form
image

### Expected behavior

It should be properly Aligned

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @varshith257 and @Anishkagupta04 

I have fixed the alignment issues for Appointment section and Contact section

image

Also there were some duplications in appointment form I have removed it and enhanced the inputs and the submit button

image

## Related Issues

- Closes #760 

## Type of PR

- [x] Bug fix
- [x] Feature enhancement

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
Let's wait for a day for @Anishkagupta04 review on it

**Comment by varshith257** [comment]
@MastanSayyad I forgot this PR of making changes to the appointment form. I recently merged the PR for the appointment form. I think your changes have a better UI. Incorporate your changes here by updating your branch

**Comment by MastanSayyad** [comment]
Hey @varshith257 Please check it out!

**Comment by varshith257** [comment]
Can you share the screenshot of the updated one from the deploy. I can't see perfectly the changes from mobile

**Comment by MastanSayyad** [comment]
@varshith257 here it is


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/101971980/2ec5d898-c524-46f1-b1fa-43b8b10e7c35

**Pull request merged**
