### PR TITLE
✔️Implemented Real Email-Sending Functionality

### LINKED ISSUE #798: ➕Implement Real Email-Sending Functionality for Feedback Form!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hey @Anishkagupta04 and @varshith257 

I'd like to propose an enhancement for the feedback form on website. Currently, **there's no real email sending functionality**, and users see a "Successfully Submitted" popup **without confirmation that their feedback reached the website admin or not?.**

So, I Want to implement a functionality so that **the Admin of the Website will recieve a feedback** **Each time a User fills** out the form 
To achieve this, **I'll use** [Formspree.io](https://formspree.io/).
Formspree will allow me to set up form submissions and forward them to you via email.

### Next Steps:

I'll initially implement this solution **using my credentials.**
After testing, I'll submit a pull request for approval from the you.

**Once approved by you,** I'll just need **"Your Formspree form endpoint URL"** and the **"designated email address"** where feedback notifications should be sent.

**For Ex. Here's My Previous Work -** 

image

Please assign me this issue.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Anishkagupta04 and @varshith257,
issue closes #798

I have implemented the real email sending functionality for the feedback form using Formsfree. 
Now, **whenever a user submits** the feedback form, the **owner of the website will instantly receive an email** containing the following user information: `name`, `email`, `rating`, and `feedback`.

### Here's Key Features
1. The owner **will receive an email immediately** after form submission.
2. Form Reset: The form fields will reset **only upon successful submission** to ensure the email is sent.

**Here's the Demo :** 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/e9c0ea1b-0ea8-445a-a575-997f95a11cc8

**Here is the email I received after submitting the feedback form.**

image

Currently, the functionality uses my form ID. 
Once approved, I will update the code with your form ID and provide you with full access.
I'll just need **"Your Formspree form endpoint URL"** 

(Please **Make a free account** on [formspree.io](https://formspree.io/) **with your email id** and create a new Form. There you'll get the **formspree form endpoint URL**.)

## Type of PR

- [x] Feature enhancement

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aslams2020** [comment]
@Anishkagupta04 , @varshith257 
And Here's How you can see the Data Stored in formspree 

image

**Comment by aslams2020** [comment]
@varshith257 @Anishkagupta04 , Please take a look

**Comment by varshith257** [comment]
@Anishkagupta04 Take a look and we may need FormSpree endpoint

**Comment by aslams2020** [comment]
Yes, Please take a look @Anishkagupta04

**Comment by aslams2020** [comment]
@Anishkagupta04 please take a look.

**Comment by varshith257** [comment]
@aslams2020 Will test the behaviour later? Let's merge it. Can you fix conflicts and tag me?

**Comment by aslams2020** [comment]
@varshith257 Okay!.
Resolved the Conflicts please check :)

**Pull request merged**
