### PR TITLE
created separate page for services 

### LINKED ISSUE #1176: ✨[Feature Request]: add the services section of main page to the services page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

image

### Use Case

Would like to add this in the services page also

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## Related Issues

- Closes #1176 

## Type of PR

- [ ] ()

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

image

### CODE REVIEW

**Review by aditya-bhaumik — COMMENTED** [review]
@varshith257 please review and merge this pull request as only 8 hours are left for gssoc to get over

**Comment by varshith257** [comment]
@aditya-bhaumik Where this page have been linked in home page? I can also see existing page for services. Ok leave it apart


Also move css to another file

**Comment by aditya-bhaumik** [comment]
@varshith257 okay then instead of creating another services page i will just add this services section to the existing services page i think that would be better update 

There is a services section in the services page but it is not as good as the main page 

Sorry i had checked the link in the footer thats why i did not see that exisiting services page 

Now i checked it and it is saved as dex.html thats why i missed it

**Comment by aditya-bhaumik** [comment]
@varshith257 i have removed the new page i had made added the services properly to the services page 

please review and merge this pull request before 7pm as it is the last time for contributing

**Comment by aditya-bhaumik** [comment]
@varshith257 please merge this pull request only 1 hour is left

**Comment by aditya-bhaumik** [comment]
@varshith257 thank you this was my last pr for this repo for this program 

It was really nice working on this repositionary

**Pull request merged**
