### PR TITLE
Fixed "Webchat Bot" and "Scroll-to-top" Button Overlapping

### LINKED ISSUE #649: 🐞 "Webchat Bot" and "Scroll-to-top" Button are Overlapping
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @Anishkagupta04 

I have noticed that the"Webchat Bot" and "Scroll-to-top" Button are Overlapping when clicked on chatbot 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/101971980/650f4589-33ad-4366-8a5c-2806b7c10c9f

### Expected behavior

- Both buttons should work without overlapping each other
- Properly aligning and resizing the buttons 
- Additionally I would like to re-style the scroll to top button matching to website design theme.

### Add ScreenShots

- **Results may look Like This :**

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/101971980/c78f8546-7ee3-4f33-a380-cbd1b4b58fea

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey, @Anishkagupta04 @varshith257 | closes #649 

I have slve the pverlapping of "Webchat Bot" and "Scroll-to-top" Button

image

image

## Type of PR

- [x] Bug fix
- [x] Feature enhancement

## Checklist

- [x]  I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
-[x]  I have updated my branch and synced it with project `main` branch before making this PR
- [x]  I have performed a self-review of my code
-[x]  I have tested the changes thoroughly before submitting this pull request.
- [x]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x]  I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@Anishkagupta04 @varshith257 plstake a look at this PR

**Comment by Anishkagupta04** [comment]
some checks haven't completed

**Comment by MastanSayyad** [comment]
Hey @Anishkagupta04 checks are compelted the one you are seeing will not cause any issue, you can merge it, if after merging it didn't 
Work then revert the changes and let me know

**Comment by MastanSayyad** [comment]
You can see the deployment preview

**Comment by MastanSayyad** [comment]
@Anishkagupta04, @varshith257

**Comment by MastanSayyad** [comment]
@Anishkagupta04 and @varshith257 Please merge my this and other PR as it has been more than a week, this is important for me to score in the leaderboard, kindly pls merge it, Thank You!

**Comment by varshith257** [comment]
Thanks @MastanSayyad for being patience to get reviewed it :)

**Comment by MastanSayyad** [comment]
Thank you @varshith257 can you pls merge my other PR too

**Pull request merged**
