### PR TITLE
Adding Google Authentication

### LINKED ISSUE #1023: ✨[Feature Request]: Adding Google Authentication
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@Anishkagupta04 I want to add Google Authentication using Firebase. Kindly assign me this issue.

### Use Case

Using Authentication anyone can sign in the Page using his/her own email address.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Description

@varshith257 @Anishkagupta04 I have added Google Authentication, Password eye toggle, Javascript validations in Login/Signup form. Kindly make sure  to add firebase file code from Firebase Console to add api keys of the Firebase for Authentication to work. Kindly review this.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1023 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Ojas-Arora this branch is not updated , new branch contains forgetpass popup please rewrite the Google Authentication code in new branch

**Review by Anjaliavv51 — CHANGES_REQUESTED** [review]
Branch is not updated.

**Comment by Ojas-Arora** [comment]
Ok I will update the Branch

**Comment by Ojas-Arora** [comment]
Branch Updation Done

**Comment by Anjaliavv51** [comment]
> Branch Updation Done

image

**Comment by Ojas-Arora** [comment]
> > Branch Updation Done
> 
> image

How can you see the deployment? It is not visible to me and you are able to see this..

**Comment by Ojas-Arora** [comment]
You are the mentor for this project ? Am i right??

**Comment by Anjaliavv51** [comment]
@Ojas-Arora in below ss u can find the deploy preview in ur PR itself it can be accesed by anyone

image

**Comment by Ojas-Arora** [comment]
@varshith257 @Anishkagupta04  Kindly review the PR as the Gssoc is about to end in some days.

**Comment by varshith257** [comment]
Can you fix conflicts and tag me?

**Comment by Ojas-Arora** [comment]
Ok

**Comment by Ojas-Arora** [comment]
@varshith257 Resolved the conflicts Kindly review now

**Comment by Ojas-Arora** [comment]
@varshith257 @Anishkagupta04 Kindly review the PR as the Gssoc is about to end in 2 days.

**Comment by Ojas-Arora** [comment]
@varshith257  @Anjaliavv51 There is no level given for this . Kindly see this.

**Comment by Ojas-Arora** [comment]
@varshith257 @Anjaliavv51 Also There is no gssoc level . Without these There will be no gssoc points awarded to me.

**Pull request merged**
