### PR TITLE
Improved the layout of  Featured Services Section

### LINKED ISSUE #334: ✨[Feature Request]: Improve the layout of ' Featured Services Section'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The featured services section takes up to much space which is unnecessary and can be avoided . Every feature is placed vertically , it can be placed horizontally .

### Use Case

It can make the landing page more navigable. 

### Benefits

_No response_

### Add ScreenShots

Before : 
Screenshot (347)
Screenshot (348)

After : 
Screenshot (349)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Pruthaa17**
Closes #334 

Screenshot (347)

Improved to this 

Screenshot (350)

### CODE REVIEW

**Comment by varshith257** [comment]
@Pruthaa17 Is that card of green is of bg-color or hover effect?

**Comment by Pruthaa17** [comment]
@varshith257  It is on hover effect

**Comment by Pruthaa17** [comment]
> @Pruthaa17 Is that card of green is of bg-color or hover effect?
 It is on hover effect

**Comment by varshith257** [comment]
@Pruthaa17 Thanks

**Pull request merged**
