### PR TITLE
Static Documentation Site Using mkdocs

### LINKED ISSUE #495: 📝[Documentation Update]: static documentation site using mkdocs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

currently there are a lot of .md files that are hectic to read for the people.

### Suggested Change

i want to propose to use a clear well structured static documentation site made using mkdocs that can be deployed in future
i ll set up mkdocs and use suitable theme for the site so that will be easy for the public to read from the site about the project rather than only .md files.

### Rationale

_No response_

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Abhishek-Sood**
## Description

Static site for documentation have been made with the help of mkdocs and can be deployed in the future. 

## Related Issues

- Closes #495

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
more changes like logo on the site and more screenshots of the project can also be updated for public refrence.

### CODE REVIEW

**Comment by varshith257** [comment]
@Abhishek-Sood Can we also have a workflow for building the site for docs something like this?

```
name: Build site nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dot-release:
    name: dot-release
    runs-on: ubuntu-latest

    steps:
      - name: curl
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        uses: wei/curl@v1
        with:
          args: -X POST -d '{}' "$NETLIFY_BUILD_HOOK"
```

**Comment by Abhishek-Sood** [comment]
yes sir we can surely have a netlify nightly build workflow instead of the github pages one. the github one is more complex but is in detail and triggers only when there is pr change or if we have a documentation tag while the netlify is rather a simple one and will trigger every night ..

so if you want to i ll make changes in the workflows to work as you like :)

**Comment by varshith257** [comment]
Implement it

**Comment by Abhishek-Sood** [comment]
please check sir updated the workflows to nightly build.

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by Abhishek-Sood** [comment]
@Anishkagupta04 mam please look into this asap i need to do other things too :)

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by varshith257** [comment]
@Anishkagupta04 is PA. So, we need request her feedback to add any new features to project. Wait will ping Anishka in discord linking the this PR

**Review by varshith257 — APPROVED** [review]
GOOD Work!

**Comment by Abhishek-Sood** [comment]
sir very very thank you  :) u d best

**Pull request merged**
