### PR TITLE
added the "medicine use" page

### LINKED ISSUE #445: ✨[Feature Request]: Build the "Medicine Use" page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the medcine use redirects to homepage because there is no page that refers to the medications and its usage. I would like to create the page that is inline with the current theme

### Use Case

Adding a page that gives information about the medications and its direction of use would make the website more informative

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description
The "medicine use" now redirects to medicine.html that fetches data from FDA API and provides the information for medicines

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #445 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Comment by Anishkagupta04** [comment]
try making more attracted also footer text colour is not going with website

**Comment by varshith257** [comment]
@samarsajad Make colors consistent with what is already using in the project. Also why can't you try to put I'm ages related to medicines instead logo in the med page

**Comment by samarsajad** [comment]
You said I can raise multiple issues later, so I just created a basic framework for now . I focused on functionality in this PR

**Comment by varshith257** [comment]
Try to make little consistent with colors

**Comment by samarsajad** [comment]
> @samarsajad Make colors consistent with what is already using in the project. Also why can't you try to put I'm ages related to medicines instead logo in the med page

With all due respect, Sir, I think the colors are pretty consistent with the overall layout since I took the colors from the style.css file. If you notice in the home page, everything that has a green container , also has a blue hover. So I did that.

**Comment by samarsajad** [comment]
> Try to make little consistent with colors

Should I Ichange the footer? cause everything else is consistent with the website design?

**Comment by samarsajad** [comment]
I made the changes. Made the footer consistent with the theme of the overall website @varshith257  @Anishkagupta04

**Comment by samarsajad** [comment]
heyy.  can you please take a look @Anishkagupta04

**Comment by samarsajad** [comment]
Can you please review this pull request so that I can further work on  enhancing this page @varshith257

**Comment by varshith257** [comment]
@samarsajad The page is not clickable on medical use on home page. PTAL

**Comment by samarsajad** [comment]
I made the chnages . can you please take a look again and see if it is working now @varshith257

**Comment by samarsajad** [comment]
Can you please take a look @varshith257

**Comment by samarsajad** [comment]
Can you please take a look @Anishkagupta04 @varshith257 . I checked the deploy preview and  it is working as expected

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/8fb9922d-2c09-450d-a713-9ee089a64e21

**Comment by samarsajad** [comment]
Please review my pull request. I made all the changes as requested and also posted the deploy preview . @varshith257  @Anishkagupta04

**Comment by varshith257** [comment]
@Anishkagupta04 Have a look and merge this

**Comment by samarsajad** [comment]
> @Anishkagupta04 Have a look and merge this

please look into this @Anishkagupta04 @varshith257

**Pull request merged**
