### PR TITLE
 improve the PR comment workflow text: #363

### LINKED ISSUE #363: 🐞[Bug]: improve the PR comment workflow text:
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Wants to improve the welcome text of pr comment  to get more engaging and polished message  commented when a pr is created.

### Expected behavior

To get  more engaging and polished welcome message for a pull request (PR) comment:

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anshika14528**
## Description

I have update the PR comment workflow text now 

(  Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/Anshika14528/RAPIDOC-HEALTHCARE-WEBSITE-/blob/main/CONTRIBUTING.md)'
        )
will commented when first PR is submited.

- Closes #363

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Anshika14528** [comment]
I was not able to check it on my local repository because this is only for first Pull request submission.

**Comment by varshith257** [comment]
@Anshika14528 I think we have to prompt for all PRs

**Comment by varshith257** [comment]
Fo that you can something use likethis:

```
name: PR Target Workflow
on: 
  pull_request_target:
  
jobs:
  PR-Greeting:
    name: Pull Request Target
    runs-on: ubuntu-latest
    steps:
      - name: Add the PR Review Policy
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: pr_review_policy
          message: |
            Great job, @${{ github.actor }}! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/Anshika14528/RAPIDOC-HEALTHCARE-WEBSITE-/blob/main/CONTRIBUTING.md)'
```

**Comment by Anshika14528** [comment]
Ok i will do this

**Comment by Anishkagupta04** [comment]
Thankyou for your  contribution!!

**Comment by Anshika14528** [comment]
@varshith257 sir, Do you want me to create new issue for that?

**Comment by varshith257** [comment]
@Anshika14528 Submit changes requested in another PR

**Comment by Anshika14528** [comment]
Ok

**Comment by Anshika14528** [comment]
Please give some label to this PR also

**Comment by varshith257** [comment]
> @varshith257 sir, Do you want me to create new issue for that?

I think there's no need . Submit the PR by tagging the same issue. I have reopened it

**Comment by Anshika14528** [comment]
Ok , Thankyou

**Pull request merged**
