### PR TITLE
Added Navbar & Footer in Blood.html

### PR DESCRIPTION
**Pull request by Rajput-xv**
issue #105 completed

I have added Navbar and Footer in Blood.html page.

preview

image

image

@varshith257 @Anishkagupta04   
kindly check this & do let me know anything you would like me to add.
add the suitable label's & merge this PR.

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
why have you changed the colour of the site to white

**Comment by Rajput-xv** [comment]
> why have you changed the colour of the site to white

Kindly check now, i have made few other changes you can review them all.
if there is something else, please do let me know.

**Comment by Anishkagupta04** [comment]
now its better

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution

**Comment by Rajput-xv** [comment]
@Anishkagupta04  @varshith257 
kindly add the labels to my issue & PR.

**Comment by sanjay-kv** [comment]
Hi @Anishkagupta04 could you add label to the same.

**Comment by Rajput-xv** [comment]
hello,
@varshith257  @Anishkagupta04 
can u please add the labels to this PR & make me assignee.

**Pull request merged**
