### PR TITLE
Addition of navbar and footer and improvement in the ui of signin and signup page that match the theme

### LINKED ISSUE #660: ✨[Feature Request]: Addition of navbar and footer and improvement in the ui of  signin and signup page that match the theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Screenshot 2024-06-21 at 11 09 18 AM
Using html and css the styling should be changed to the required design.

### Use Case

 Addition of navbar and footer and improvement in the ui of  signin and signup page that match the theme.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by DiwareNamrata23**
## Description

Added navbar and footer also changed background colour

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #660 

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-06-24 at 3 02 52 PM
Screenshot 2024-06-24 at 3 30 04 PM

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by DiwareNamrata23** [comment]
@varshith257 plz review my pr

**Comment by varshith257** [comment]
Will review it soon

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by DiwareNamrata23** [comment]
Does ay changes required @varshith257  & @Anishkagupta04  please let me know..

**Comment by varshith257** [comment]
@DiwareNamrata23 The navbar seems the old one. Please update with upstream and use the new one

**Comment by DiwareNamrata23** [comment]
Sure

**Comment by DiwareNamrata23** [comment]
@varshith257 done the changes please tell me the required changes

**Comment by Anishkagupta04** [comment]
the navbar is different also the color is not same as in website and the header is also not same

**Comment by varshith257** [comment]
> the navbar is different also the color is not same as in website and the header is also not same 

@DiwareNamrata23 Any updates on this?

**Comment by DiwareNamrata23** [comment]
Yes added changes in color will commit in few hours by today

**Comment by DiwareNamrata23** [comment]
Screenshot 2024-07-25 at 9 33 01 PM
Screenshot 2024-07-25 at 9 33 10 PM
added the changes plz review @varshith257 and @Anishkagupta04

**Comment by varshith257** [comment]
@DiwareNamrata23 Can you solve merge conflicts and tag me?

**Pull request closed without merging**
