### PR TITLE
✔️Enhanced "Complete UI Design and Alignment" of the "Appointment" Page!

### LINKED ISSUE #825: ➕Enhance Alignment and Design of the "Appointment" Page in Footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @varshith257 and @Anishkagupta04,

Curently, The **"Appointment" page** is currently a basic HTML file **with minimal styling and functionality.** 
It does not align well with the overall theme of the website and lacks user-friendly features.

I Propose to enhance the "Appointment" page by 
- **Improving its alignment**
- **Add Responsive design** to ensure the page looks good on all devices.
- Designing it to **match the website's theme**
- Adding some functionalities to **make it easier Cfor users to fill out** the form.
- **Add tooltips or placeholders to guide users** on how to fill out the form fields.

**Current Appointment Page :** 
image

I'd Like to contribute to this issue.
Thankyou!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
hey @Anishkagupta04 , @varshith257 
issue closes #825 

### Here's what I did
1. **Improved the "Complete UI and Alignment"** of the Appointment Form.
2. **Added "Responsiveness"** to the Page.
3. **"Re-ordered all the Form Label"** to Make it easier for any kind of patients to fill out the form.
4. Also **Added "Favicon"** to the Website Page.
5. **Followed the color theme** of the website **with respective hexcodes** of the Home page.
6. Added **Placeholders, Validity checks, and required attributes to the Labels**.
7. Additionally, Updated the **Complete UI and alignment of the "Preview Appointment"**

Overall, the complete Appointment form is now working and provides users with the best features and usability.

**Here is the Implementation**  

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/28f916e6-a3ab-4792-af98-86ff6c63b756

Please take a look and review it.
Thankyou! 

## Type of PR
- [x] Feature enhancement

## Checklist
- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by aslams2020** [comment]
@varshith257

**Comment by varshith257** [comment]
@aslams2020 Why placeholders misaligned in the attached video?

**Comment by aslams2020** [comment]
@varshith257 Sorry for the oversight, I Myself had made that change earlier.
Here I fixed it now - 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/131389695/4f64a621-66e2-420f-91bc-e1134068cd4a

 Please take a look

**Comment by aslams2020** [comment]
@varshith257 please review it.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
