### PR TITLE
Update testimonial section

### LINKED ISSUE #898: ✨[Feature Request]: add a testimonail page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a testimonial page as the current link in the footer is not directing us to any other page it just takes us back to the top of the screen

### Use Case

Build Trust: Displaying testimonials from satisfied users or clients helps build trust with new visitors.
Showcase Success: Highlighting positive feedback and success stories can encourage potential users to engage with your website or services.
Engage Users: Testimonials provide social proof and can be an effective way to engage with your audience.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## Description

i have made the changes to the testimonial section you mentioned now you can use the arrow to go the next testimonial

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #898

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by aditya-bhaumik** [comment]
@varshith257 please review and merge this pull request

**Comment by aditya-bhaumik** [comment]
@varshith257 please review this pull request

**Comment by aditya-bhaumik** [comment]
@varshith257 please review and merge my pull request

**Comment by aditya-bhaumik** [comment]
@varshith257 please review this pull request and merge it

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
