### PR TITLE
Added "Scroll Down Progress Bar" To The website

### LINKED ISSUE #659: ✨ Feature: Add "Scroll Down Progress Bar" To The website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Anishkagupta04 and @varshith257 

I would like to suggest adding **a scroll down progress bar** to the website to enhance user experience. A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. This feature can be especially helpful for long pages blogs and articles.

image

### Use Case

- Enhances user experience by providing visual feedback.
- Useful for long pages or articles.
- Improves overall navigation and user satisfaction

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @Anishkagupta04 and @varshith257   | issue closes #659

I have added the **Scroll down progress bar** in **All pages** of the **website** 

image

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/101971980/84153e42-c73b-4d16-a16e-2678a2f47407

## Type of PR

- [x] Feature enhancement

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Please take a look and review it, Thank You!!

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@varshith257 please review this PR

**Comment by MastanSayyad** [comment]
Hey @Anishkagupta04 and @varshith257 please take a look at this PR

**Comment by MastanSayyad** [comment]
@varshith257 I have resolved the conflicts pls merge this PR

**Comment by MastanSayyad** [comment]
@Anishkagupta04 @varshith257 I I have resolve the conflicts again pls merge this PR

**Comment by MastanSayyad** [comment]
@varshith257 I have resolved the conflicts pls merge this

**Comment by varshith257** [comment]
@MastanSayyad Navbar has disappeared with the scrollbar.Have a look onto it

**Comment by MastanSayyad** [comment]
@varshith257 

Sorry for the oversight it may have gotten broken while resolving the conflicts!!
thank you for letting me know, **I have fixed that!!** Please take a look and review it!

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
Awarding level 3 for extending Progress bar to other pages too

**Comment by varshith257** [comment]
@MastanSayyad 
Can raise an issue for this, I feel it is misaligned and an area for improvement:

image

**Comment by varshith257** [comment]
And also the same for appointment form section

**Comment by MastanSayyad** [comment]
> @MastanSayyad Can raise an issue for this, I feel it is misaligned and an area for improvement:
> 


Sure, I have raised the issue for it!

**Comment by MastanSayyad** [comment]
> Awarding level 3 for extending Progress bar to other pages too

Thank you for the consideration, really appreciated!!

**Pull request merged**
