### PR TITLE
Update Doctor Experience.html

### PR DESCRIPTION
**Pull request by ankitmodanwall**
I added some useful fonts with footer, header <h1> style that enhance the looks than before.

## Description

Since this page doesn't contain as such impressive footer along with data and about section so that i made changes.
## Related Issues

- Footer section at below the page
- Style tag
- text-align

- Closes #

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
now you can relate this updated page                   
                 

## Checklist
Screenshot 2024-06-14 061618

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ankitmodanwall** [comment]
Thank you!!

**Comment by Anishkagupta04** [comment]
send ss of the changes

**Comment by varshith257** [comment]
@ankitmodanwall Resolve conflicts

**Comment by ankitmodanwall** [comment]
now resolved conflicts.

**Comment by ankitmodanwall** [comment]
@Anishkagupta04 
I made few changes as  

- background palette added
- update social medias logo
- added black heart as compare to red heart
- about section consists of italic font


##Screen-shots
Screenshot 2024-06-16 182033


Screenshot 2024-06-16 182017

**Comment by varshith257** [comment]
@ankitmodanwall Closing. LATEST upstream footer is better

**Comment by ankitmodanwall** [comment]
@varshith257 so what did you mean ?

**Comment by varshith257** [comment]
The current footer satisfies the requirements and there is no assigned issues to this PR too and color Schema is not aligned with Project

**Comment by ankitmodanwall** [comment]
Could you share the ss?

**Pull request closed without merging**
