### PR TITLE
Improve Navigation bar #138

### PR DESCRIPTION
**Pull request by ShahHetviIT**
image

## PR Description

Improvement in navigation bar.
if any problem kindly explain to me i will solve it. I have tried my best to improve this

## Related Issues: Issue for which you are raising a PR for
Improve Navigation bar #138

- Closes #

### Issue

Improve Navigation bar #138

### Checklist

- [x] I have gone through the [contributing guide](## PR Description

_Add your description_

## Related Issues: Issue for which you are raising a PR for

- Closes #

### Issue

Improve Navigation bar #138

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [ ] Tested for any breaking changes
- [ ] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by varshith257** [comment]
@ShahHetviIT Can you add some alignment gap between the image and text in nav bar. Ex: Home image and it's text a little bit of 0.5px. Except this everything is fine

**Comment by ShahHetviIT** [comment]
yes sure i will do

**Comment by ShahHetviIT** [comment]
i have added 4 px gap as it looks nice. Tell me if more changes needed

**Comment by varshith257** [comment]
Can send updated navbar pic?

**Comment by ShahHetviIT** [comment]
image

**Comment by ShahHetviIT** [comment]
Any changes needed?

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
@ShahHetviIT Thanks for the contribution 🚀

**Comment by ShahHetviIT** [comment]
Thanks for give me opportunity.

**Pull request merged**
