### PR TITLE
🐞[Bug]: Decrease of font size in navbar and addition of effect the image

### LINKED ISSUE #1185: 🐞[Bug]: Decrease of font size in navbar and addition of effect the image
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Decrease of font size in navbar

### Expected behavior

font should be around 20px , so that they align in proper way

### Add ScreenShots

image

Additon of effects to the below image

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Related Issues

- Closes #1185 

## Type of PR

- [X] (bug)
- [X] (feature)

## Screenshots / videos (if applicable)

size decreased

image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

size decreased

image

**Comment by Anjaliavv51** [comment]
Added box effect 

image

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
