### PR TITLE
made service page responsive

### LINKED ISSUE #845: 🐞[Bug]: Service page is not mobile responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the service page is not mobile responsive

### Expected behavior

the contents are supposed to be aligned when viewed in mobile view

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Added media queries to make the services page mobile responsive.

## Related Issues

- Closes #845

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Comment by samarsajad** [comment]
Please review my pull request @varshith257

**Comment by varshith257** [comment]
@samarsajad Can you fix this?

image

**Comment by samarsajad** [comment]
> @samarsajad Can you fix this?
> 
> image
> 

Yes I'll look into it and let you know

**Comment by varshith257** [comment]
I can see it in the deploy

**Comment by samarsajad** [comment]
> I can see it in the deploy

image
this is the ss from the deploy preview @varshith257  Only one find a doctor is showing

**Comment by samarsajad** [comment]
Please review the changes made @varshith257

**Comment by varshith257** [comment]
Footer is totally misaligned with mobile responsive and some of buttons in service page also misaligned 


@Anjaliavv51 Take a look 
/approve or request changes

**Comment by Anjaliavv51** [comment]
@samarsajad footer alignment is not good , pls modify it.

**Comment by Anjaliavv51** [comment]
@samarsajad also , to check ur code output , please review the deployment in netlify

**Pull request closed without merging**
