### PR TITLE
✨[Feature Request]: Enhancement of Blood Bank.html page

### LINKED ISSUE #580: ✨[Feature Request]: Enhancement of Blood Bank.html page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Would like to add more features for blood bank webpage.

### Benefits

Attractes the user's experience.

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #580

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #580 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/b5f6165a-49f7-4189-8a32-b1c1f0b4c496

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes , when we click on the Getlist button in blood.html file , we get details in the page of list.html file.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by varshith257** [comment]
Will review it by EOD

**Comment by Anjaliavv51** [comment]
@varshith257 okay

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 also add GSSOC and level labels

**Comment by Anjaliavv51** [comment]
@varshith257

**Pull request merged**
