### PR TITLE
I made beautiful patient portal section and also aligned the services …

### LINKED ISSUE #269: ✨[Feature Request]: Improve UI of Services section and Patient Portal section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In services section, the cards are not consistent and their is no sequence, in the Patient portal section the login details are poorly designed and there is no response when you click login.
RAPIDOCisuue1

### Use Case

The improved UI of services section would improve user experience, the responsive and neatly designed login (patient portal) section will further add to user experience.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by the-indian-hustler**
…section rightly

## PR Description

I have rightly aligned the services section and improved the UI of input buttons for the patient portal section now, that section is looking good

- Closes #269

### Issue

Improve UI of Services section and Patient Portal section #269
RapidocResolvedIssue1
RapidocResolvedIssue2

### Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes
- [ ] Part of GSSOC
- [ ] Tested for any breaking changes
- [ ] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [ ] I Agree

### CODE REVIEW

**Comment by varshith257** [comment]
@the-indian-hustler I can't see any enhancements here

**Comment by the-indian-hustler** [comment]
You can see the screenshots which i gave during issue mentioning and those which i gave in pull request, the boxes are properly aligned now, the login buttons are smooth and more attractive then the previous which were appearing childish .
________________________________

**Comment by varshith257** [comment]
Post a video of your changes @the-indian-hustler

**Comment by varshith257** [comment]
No activity

**Pull request closed without merging**
