### PR TITLE
Fixed Mobile View of Contact Page

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
Fixed Mobile View of RateUs Page as i have mentioned it in this issue #894
Kindly Please go through this PR @varshith257

https://github.com/user-attachments/assets/b7199ecf-4df0-4dfe-a2fa-608e812cce0a

### CODE REVIEW

**Comment by varshith257** [comment]
@sailaja-adapa looks good to merge.

nit: The logo should replaced by a text. Refer here the changes discussed in the PR:

**Comment by sailaja-adapa** [comment]
Yeah okk @varshith257

**Comment by sailaja-adapa** [comment]
@varshith257 is it okay now 

lkl

**Comment by varshith257** [comment]
@Pruthaa17 @Anjaliavv51 @aditya-bhaumik PTAL

**Comment by sailaja-adapa** [comment]
> @sailaja-adapa Other contributers will get this reviewed for time being as examinations are ongoing.

Yeah okk @varshith257

**Comment by Anjaliavv51** [comment]
@sailaja-adapa please wrap the below two sections in row.

image

image

**Comment by sailaja-adapa** [comment]
Can you explain in detail please you want me to set it in same row like on large screen @Anjaliavv51

**Comment by sailaja-adapa** [comment]
okk thank you @Anjaliavv51

**Review by aditya-bhaumik — COMMENTED** [review]
image
there should not be so much extra space at the right side it is not looking good when you are adding them in rows make sure there is only a small gap

**Comment by sailaja-adapa** [comment]
yeah okk @aditya-bhaumik

**Comment by sailaja-adapa** [comment]
Is it okay now? @Anjaliavv51 

c

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
