### PR TITLE
🐞[Bug]: Fixing News.html

### LINKED ISSUE #873: 🐞[Bug]: Fixing New.html
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

New.html file is not structured properly

image

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#873

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #873 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Vercel Deployment screenrecording

https://github.com/user-attachments/assets/6109b161-8806-4a58-9ccf-aa299b24f8d4

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR and also please check the deployment screen recording vercel app.

**Comment by varshith257** [comment]
@Anjaliavv51 Why footer is blue?

**Comment by Anjaliavv51** [comment]
@varshith257 

image

**Comment by Anjaliavv51** [comment]
@varshith257 changes are done.

**Comment by varshith257** [comment]
Why's there gap between footer and news section and also the gap between footer and end of page?

Also make hover me or readme buttons to center of card

**Comment by Anjaliavv51** [comment]
@varshith257 

image


It is fixed.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
