### PR TITLE
 Database Support for forms and various registrations

### LINKED ISSUE #705: Database Support for forms and various registrations
### Discussed in https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/discussions/455

<div type='discussions-op-text'>

<sup>Originally posted by **varshith257** June  6, 2024</sup>
PostgreSQL is one I prefer as I worked with three of these dbs. But I can't say we use this only for our project as every usecase has other preferences over dbs in projects. Submit a report of your findings, why we prefer PostgreSQL for our project, and why not MongoDB and MySQL. Pros and cons of them and what you are suggesting to use finally based on your research?</div>

### PR DESCRIPTION
**Pull request by Pruthaa17**
## Description

Added an image in assets to show DB Schema 

## Related Issues

- Closes #705 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
[
DbSchema
](url)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by varshith257** [comment]
@Pruthaa17 User can have some more additional fields like age. Refer what we taking in appointment form for it and appointment table and user table can have 1-1 relationship

**Comment by varshith257** [comment]
Next to Hospital to labs, clinics 1-many

**Comment by Pruthaa17** [comment]
drawSQL-image-export-2024-06-28

**Comment by varshith257** [comment]
@Pruthaa17 It now makes sense!
Thanks for this!
Would you also add support for backend using PostgreSQL?

**Comment by Pruthaa17** [comment]
@varshith257 I will create a new pull request ,  by mistake i deleted the branch

**Comment by Pruthaa17** [comment]
> @Pruthaa17 It now makes sense! Thanks for this! Would you also add support for backend using PostgreSQL?

Yes I'll

**Comment by varshith257** [comment]
Why was this deleted? Make a new PR

**Comment by Pruthaa17** [comment]
> Why was this deleted? Make a new PR

#724

**Pull request closed without merging**
