### PR TITLE
Fixes issue #925

### LINKED ISSUE #925: Improvement of Navbar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello PA,

Nav items  in the navbar are looking little clumsy.
Want to increase some gap between them for better UI design.

### Expected behavior

Improved navbar for better visibility.

### Add ScreenShots

Before:
image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
This PR improves navbar for better visibility.

- Closes #925 

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)
Before:
image

After:
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@Anishkagupta04 @varshith257 
Please review this PR and assign gssoc, level labels.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
Please review this PR and assign the labels.
Thank you.

**Comment by varshith257** [comment]
@Bhattu-Anitha-07 Reduce some gap between nav bar items it elongated whole.on the navbar

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 done will update it.

**Comment by Bhattu-Anitha-07** [comment]
image
@varshith257 
Please checkout this.
Thank you

**Comment by varshith257** [comment]
Looks good to merge.

nit: can be given a small gap between text and icon of contact us and rate us?

**Comment by Bhattu-Anitha-07** [comment]
Ok sure.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 Please take a look over issue no. # 931
And kindly assign that issue to me

**Comment by Bhattu-Anitha-07** [comment]
image
Does it look fine, shall I update my PR.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
