### PR TITLE
Improved the UI by Color Changed and various location added

### LINKED ISSUE #143: Improving the UI of Make an Appointment section
Alignment of the appointment the section can also be improved input fields do not have the same colored text 
Kindly Assign this issue to me I can make the required changes 
thank you 
image

### PR DESCRIPTION
**Pull request by Kriagr23**
image
image
issue resolved #143

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
Add time section(you have seen the layout of book my show for movies in that there are given dates list of theatres and time slot available so you can do it in that way also it will look good and also helps user to chooseslot quickly)
List of hospital 
List of OPD sections like ent, gynecologist,etc

**Comment by Kriagr23** [comment]
Okay I'll do by tomorrow thank you so much

**Comment by Kriagr23** [comment]
image
#150

**Comment by varshith257** [comment]
@Kriagr23 Thanks for your contribution 🚀

**Pull request merged**
