### PR TITLE
Addition of about us page

### LINKED ISSUE #967: ✨[Feature Request]: Addition of about us page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of about us page , which tells about the  webapge.Which contains information about contributors mentors and project admins.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#967

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #967 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/31f32eb9-1ffb-4399-a569-a115e70d8527

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by varshith257** [comment]
Can you update with a video?

**Comment by Anjaliavv51** [comment]
> #967
> 
> ## Description
> 
> [Please include a brief description of the changes or features added]
> 
> ## Related Issues
> 
> [Cite any related issue(s) this pull request addresses. If none, simply state “None”]
> - Closes #967 
> 
> ## Type of PR
> 
> - [ ] Bug fix
> - [X] Feature enhancement
> - [ ] Documentation update
> - [ ] Other (specify): _______________
> 
> ## Screenshots / videos (if applicable)
> 
> 
> https://github.com/user-attachments/assets/31f32eb9-1ffb-4399-a569-a115e70d8527
> 
> 
> 
> ## Checklist
> 
> - [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
> - [X] I have updated my branch and synced it with project `main` branch before making this PR
> - [X] I have performed a self-review of my code
> - [X] I have tested the changes thoroughly before submitting this pull request.
> - [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
> - [X] I have commented my code, particularly in hard-to-understand areas.
> 
> 

Here is the video @varshith257

**Comment by Anjaliavv51** [comment]
https://github.com/user-attachments/assets/31f32eb9-1ffb-4399-a569-a115e70d8527

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by Anjaliavv51** [comment]
@varshith257 please review the video

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
Good to have this. Great work! @Anjaliavv51

**Comment by Anjaliavv51** [comment]
> Good to have this. Great work! @Anjaliavv51 

I would like contribute more to this repo @varshith257 , also in future to after GSSOC.

**Pull request merged**
