### PR TITLE
added-navbar

### PR DESCRIPTION
**Pull request by Soujanya2004**
Issue: #1094 

## Screenshots / videos (if applicable)
Screenshot (155)

## Checklist

- [ X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X ] I have updated my branch and synced it with project `main` branch before making this PR
- [X ] I have performed a self-review of my code
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@varshith257

**Comment by ayush-848** [comment]
> @varshith257

@Soujanya2004 you have added the wrong issue mistakenly. Please check. #1100 is the one on which I am working upon

**Comment by Soujanya2004** [comment]
@ayush-848 got it

**Comment by varshith257** [comment]
@Anjaliavv51 Take a look

**Comment by Anjaliavv51** [comment]
@Soujanya2004 



Their is no navbar in the deploy.
Did commit the changes properly?
Once please check

**Comment by Anjaliavv51** [comment]
@Soujanya2004 please check the code.

**Comment by Anjaliavv51** [comment]
@Soujanya2004 please update ur branch

**Comment by Soujanya2004** [comment]
@Anjaliavv51 I will look into this

**Comment by Anjaliavv51** [comment]
Latest branch has no appointment section in index.html page.

So please update ur branch and commit the changes.

**Comment by Soujanya2004** [comment]
but there is appointment.html without navbar @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Soujanya2004 first please update the branch and commit the changes.

**Comment by varshith257** [comment]
@Soujanya2004 Looks good to merge but the navbar should align with home page navbar style

**Pull request closed without merging**
