### PR TITLE
Blood test page added

### LINKED ISSUE #365: ✨[Feature Request]: Blood Test Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The blood test icon leads to the homepage and has not been built. Features such as, type of test, method of choosing collection of the sample, available slots, pricing, etc would be added.

### Use Case

Adding detailed features to the blood test section, such as type of test, sample collection method, available slots, and pricing, enhances user experience by providing clarity, flexibility, efficient scheduling, and transparent pricing. This empowers users to make informed decisions, save time, and trust the service, leading to higher satisfaction and convenience.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Created a blood test page where the user can book for the tests 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/542dccd7-e5f8-44e9-ac20-ab3d69ab628a

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Anishkagupta04 @varshith257

**Comment by Anishkagupta04** [comment]
The alignment is not proper

**Comment by samarsajad** [comment]
can you please explain what changes you want me to do ? @Anishkagupta04

**Comment by varshith257** [comment]
@Anishkagupta04 Suggest the changes required

**Comment by samarsajad** [comment]
> @Anishkagupta04 Suggest the changes required 

Can you please specify the changes? It'd be really helpful if you suggest what all to fix in the webpage and what sort of alignment you want me to keep @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
Hah, the issue is that it looks like a column page and you can create it as a separate page and keep it as a form for blood test details. 

Something you can take reference from this article:
https://medium.com/@pawankumar/ui-ux-case-study-redefined-test-booking-experience-by-following-the-design-thinking-process-be2ac6a1b805

You can submit multiple PRs for features and pages you add for the complete blood test feature for this project as mentioned in above article, we assign labels each for them separately

**Comment by samarsajad** [comment]
Alright, I'll change it @varshith257

**Comment by varshith257** [comment]
Better follow the referenced article

**Comment by samarsajad** [comment]
I did the required changes and created a new pull request. Please take a look #486  @Anishkagupta04 @varshith257

**Pull request closed without merging**
