### PR TITLE
Implement Sign-In/Sign-Up Page

### PR DESCRIPTION
**Pull request by Vaibhav22p-qw**
**Fixed issue #268 **

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/75926745/3d7795bc-6608-462c-abff-16dde722be1d

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
It's RAPIDOC spelling mistake

**Comment by Vaibhav22p-qw** [comment]
hello @Anishkagupta04  done

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257 & @Anishkagupta004 issue fix #277 


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/75926745/d2b79e08-d055-41f0-a700-381dc0ce3a3a

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257 & @Anishkagupta004 both issue fixed #268 & #277 done

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257 7 @Anishkagupta004  Done

**Comment by Bishal-35** [comment]
@Anishkagupta004 I would like to work on it under gssoc'24

**Comment by Vaibhav22p-qw** [comment]
Hello @varshith257 make 1 label only merge both

**Comment by varshith257** [comment]
Can resolve the conflicts?

**Comment by Vaibhav22p-qw** [comment]
Hello @varshith257 plz assist me how to do

**Comment by varshith257** [comment]
I have solved it

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
