### PR TITLE
Add Contact Us Page and News Section (GSSoC'24) #112

### LINKED ISSUE #112: 💡[FEATURE]: Add Contact Us Page and News Section (GSSoC'24)
Assigning this issue to myself for implementation. (GSSoC'24)

Contact Us Page:
-Include a form for users to submit queries or feedback.
-Display contact information such as email, phone number, and address if applicable.
-Ensure accessibility and user-friendly design.

News Section for Medicines and Doctors' News:
-Integrate a news feed or blog section focusing on medical updates, new treatments, and healthcare industry insights.
-Provide filters or categories for easy navigation (e.g., news related to medicines, doctors, health tips).
-Include options for users to subscribe to newsletters or alerts.

### PR DESCRIPTION
**Pull request by Vaibhav22p-qw**
issue fixed #112

### CODE REVIEW

**Comment by Vaibhav22p-qw** [comment]
Ok

**Comment by Vaibhav22p-qw** [comment]
5:30PM

**Comment by Vaibhav22p-qw** [comment]
Screenshot 2024-05-15 170940
Screenshot 2024-05-15 171105

**Comment by Vaibhav22p-qw** [comment]
> @Vaibhav22p-qw Can you send the pic of added sections?

Done

**Comment by varshith257** [comment]
For news section, can you add any news of healthcare-related and use slide the news with time

**Comment by Vaibhav22p-qw** [comment]
plz send me NEWS to display

**Comment by varshith257** [comment]
> plz send me NEWS to display

@Arpcoder @richasriva Can you help in this?

**Comment by Vaibhav22p-qw** [comment]
Don't worry I will do it by myself @varshith257

**Comment by Vaibhav22p-qw** [comment]
hello @varshith257  &  @Anishkagupta04  issue #92 done please preview , and assign other issue if you want

**Review by Anishkagupta04 — APPROVED** [review]

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution! @Vaibhav22p-qw

**Pull request merged**
