### PR TITLE
🐞[bug]:Signup with google isn't working

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Description

Fixes issue #427 signup with google button.

## Related Issues

issue #427 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/91906b7d-6d32-4835-80dd-bb3972b41372

Signup in Login Form:

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/8e9fa36d-34ae-4f14-9da1-46357610e9cd

Signup in Register Form:

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/729b7b5c-1800-4ee3-9592-79742cf1ce4e

After Signup:

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/2e5cf86f-acbb-4a0b-be13-2fdde613f6ca

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/a3bc673e-ede1-4245-ac6e-a26b86b473b4

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Added a file one script file and html file.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 @Anishkagupta04 please check i added Signup with google in two forms

**Comment by Anjaliavv51** [comment]
@varshith257 @Anishkagupta04 please check i added Signup with google in two forms and also successfully completed signup page.

**Comment by varshith257** [comment]
@Anjaliavv51 Have you used firebase for it?

**Comment by Anjaliavv51** [comment]
@varshith257 yes

**Comment by Anjaliavv51** [comment]
@varshith257 is their any problem in using firebase?

**Comment by varshith257** [comment]
I will discuss it with Anishka. We are planning to add backend support so that it can be easy for this all

**Comment by Anjaliavv51** [comment]
@varshith257 okay

**Comment by Anjaliavv51** [comment]
@varshith257 any updates?

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 plese Review the CHanges

**Comment by Anishkagupta04** [comment]
Some error is there ig google page is not appearing

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 I will check it

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@Anishkagupta04  please review the changes.

**Comment by varshith257** [comment]
@Anishkagupta04 Preview it  in vercel deployment

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 please review the changes

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 please review the changes

**Comment by Anjaliavv51** [comment]
@varshith257 please check the PR

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
