### PR TITLE
Adding Facebook Authentication

### LINKED ISSUE #1046: ✨[Feature Request]: Adding Facebook Authentication
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@Anishkagupta04 @varshith257 I want to add Facebook Authentication to the website. Kindly assign me this issue.

### Use Case

Using Authentication anyone can sign in the Page using his/her own email address.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Description
@Anishkagupta04 @varshith257 I have added Facebook Authentication to the website. Kindly review this.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #1046 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Ojas-Arora** [comment]
@varshith257 @Anishkagupta04 Kindly review the PR as the Gssoc is about to end in 2 days.

**Comment by varshith257** [comment]
@Anjaliavv51 Could you test it?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 Could you test it?

It is disappearing immediately.
@varshith257

**Comment by Ojas-Arora** [comment]
@Anjaliavv51 @varshith257 U need to create an account on firebase console to get the api keys for the authentication to work properly. Due to absence of that the Authentication is not working .

**Pull request merged**
