### PR TITLE
Hover effects and transform added

### PR DESCRIPTION
**Pull request by zalabhavy**
## Description
I have added Hover effects of color change and also added transform to looks amazing.

## Related Issues
issue no #354 

## Type of PR
- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________
## Screenshots / videos (if applicable)

image

## Checklist
- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by zalabhavy** [comment]
@Anshika14528 After 1 Month my PR is still not review

**Comment by zalabhavy** [comment]
@Anishkagupta04 After 1 Month my PR is not review

**Comment by zalabhavy** [comment]
@varshith257 Can you please merge this PR !

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
