### PR TITLE
Added blood test page

### LINKED ISSUE #365: ✨[Feature Request]: Blood Test Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The blood test icon leads to the homepage and has not been built. Features such as, type of test, method of choosing collection of the sample, available slots, pricing, etc would be added.

### Use Case

Adding detailed features to the blood test section, such as type of test, sample collection method, available slots, and pricing, enhances user experience by providing clarity, flexibility, efficient scheduling, and transparent pricing. This empowers users to make informed decisions, save time, and trust the service, leading to higher satisfaction and convenience.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Created a blood test page where the user can book for the tests 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/0a2ceaed-c96c-4a32-875a-90540e168231

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
I fixed the issue in my previous pull request #486  Please review it @Anishkagupta04 @varshith257

**Comment by samarsajad** [comment]
yeah i just realised it is not linked with the main index.html. Sorry for the inconvenience. Please check #500 that resolves the issue in this one

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by samarsajad** [comment]
@Anishkagupta04 please take a look, ma'am so that I can continue working on other issues

**Comment by Anishkagupta04** [comment]
why there is dotted line appearing in between the page

**Comment by varshith257** [comment]
Also use the current footer of the homepage there and remove the hover in the options

**Comment by samarsajad** [comment]
I removed the dots and also aligned the dots. Kindly take a look. @Anishkagupta04 @varshith257

**Comment by varshith257** [comment]
@samarsajad Can;t access the blood test page

**Comment by samarsajad** [comment]
Can you please recheck? I am able to view it from the home page. Here is the demo video @varshith257  @Anishkagupta04 
 
Uploading testpage3.mp4…

**Comment by varshith257** [comment]
In netifly deployment, I can't able to access it

**Comment by samarsajad** [comment]
> In netifly deployment, I can't able to access it

If you see the files changed, you can clearly see that I have linked the Blood test page with the test.html file. Can you please suggest what to do ? @Anishkagupta04 @varshith257

**Comment by samarsajad** [comment]
made the chnages. can you please take a look @varshith257 @Anishkagupta04

**Comment by samarsajad** [comment]
I checked the deploy preview and it is working asexpected. PTAL @Anishkagupta04 @varshith257

**Comment by varshith257** [comment]
@samarsajad Can you post a video about how you get access to blood test page

**Comment by samarsajad** [comment]
> @samarsajad Can you post a video about how you get access to blood test page



https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/ccdc6048-4852-49d8-80be-b87734f9bb46



@varshith257 @Anishkagupta04

**Comment by samarsajad** [comment]
hey now i uploaded the deploy preview  as well. please take a look @varshith257  @Anishkagupta04

**Comment by samarsajad** [comment]
Kindly review my pull request @varshith257  @Anishkagupta04 . I have uploaded the deploy preview as well

**Comment by samarsajad** [comment]
@varshith257  @Anishkagupta04  Please review this so that I can further work on this page.

**Comment by samarsajad** [comment]
> @varshith257 @Anishkagupta04 Please review this so that I can further work on this page.

PTAL

**Comment by samarsajad** [comment]
can you please review my pull request @varshith257 @Anishkagupta04

**Pull request merged**
