### PR TITLE
UI of one of the cards does not match with the other cards in the news page .

### LINKED ISSUE #1112: 🐞[Bug]: UI of one of the cards does not match with the other cards in the news page .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

UI of one of the cards does not match with the other cards in the news page .

### Expected behavior

The UI of every card must be the same .

### Add ScreenShots

Screenshot (920)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by meetarora10**
## Description
Changed the UI of the card with different UI and now the cards on the news page have a uniform UI .

## Related Issues
- Closes #1112

## Type of PR

- [x] (Bug Fix)

## Screenshots / videos (if applicable)
Screenshot (923)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
I have also removed one extra RAPIDOC white logo which was coming in responsive view .
Screenshot (922)

### CODE REVIEW

**Comment by meetarora10** [comment]
@varshith257 please review and merge .

**Comment by meetarora10** [comment]
Hey @varshith257 please have a look .

**Comment by meetarora10** [comment]
@varshith257 not reviewed yet .

**Comment by varshith257** [comment]
@meetarora10 I think every card should be green instead the white and also move hover buttons to center of each card

**Comment by meetarora10** [comment]
Ok @varshith257

**Comment by meetarora10** [comment]
Screenshot (973)

**Comment by meetarora10** [comment]
@varshith257 done please review and merge .

**Pull request merged**
