### PR TITLE
Navbar

### LINKED ISSUE #598: ✨[Feature Request]: Responsive Navbar with Toggle Button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The feature described is a Responsive Navigation Bar with a Toggle Button designed to adapt seamlessly across different screen sizes, particularly enhancing usability on mobile devices.

### Use Case

The responsive navigation bar is a user interface component that adjusts its layout and behavior based on the screen size of the device being used. It includes a toggle button that allows users to show or hide the navigation links when viewed on smaller screens, such as smartphones and tablets.

### Benefits

It will make the navbar responsive for the small screens.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RohithChitrada**
## Description
I have redesigned the navbar in the index.html file

[Please include a brief description of the changes or features added]

## Related Issues
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #598 

## Type of PR

- [] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-07-18 192055

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RohithChitrada** [comment]
Hi @varshith257, This message is just to remained you that the time is running out. So please try to merge the PR as fast as you can, I resolved the conflicts also. So, please try to act fast

**Comment by varshith257** [comment]
@RohithChitrada We have open PRs of making mobile responsive of navbar. Can you look at them and make changes to align their design?

**Comment by varshith257** [comment]
Look at responsive named prs

**Comment by RohithChitrada** [comment]
@varshith257 Do i need to check already merged pr's or still open pr's

**Comment by varshith257** [comment]
Open PR/closed anything is fine with mobile responsiveness named prs

**Pull request closed without merging**
