### PR TITLE
✨[Feature Request]: Addition of GSSOC label 

### LINKED ISSUE #581: ✨[Feature Request]: Addition of GSSOC label
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of GSSOC label automaticlly , if they are contributor's under GSSOC.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Description

Added automatic addition of GSSOC label.
issue #581 

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #581 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
added new file in workfloes.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by varshith257** [comment]
News.html and chatbot.css deleted?

**Comment by Anjaliavv51** [comment]
Chatbot.css is old one

**Comment by Anjaliavv51** [comment]
@varshith257

**Comment by Anjaliavv51** [comment]
@varshith257 I updated the new.html code

**Comment by Anjaliavv51** [comment]
@varshith257 now u can see , it is updated.

**Comment by Anishkagupta04** [comment]
ig the header footer is disturbed in you deployment kindly see into it

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 in which file?

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 and also I didn't made any changes in HTML CSS OR JS files

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes only yml file is added in work flow

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
