### PR TITLE
Added new footer section design

### LINKED ISSUE #535: 🐞[Bug]: Footer Section Alignment and UI Issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No Proper alignment of the footer section and the visual appearance and styling of the footer section is also not good.

Please assign this issue to me under gssoc 2024 and also add an appropriate level label to this issue.

### Expected behavior

The footer section should have a consistent and well-aligned layout. The positioning and spacing of elements should be visually appealing and follow best practices for user experience.

### Add ScreenShots

Now:
fo1
fo2

My idea is somewhat like this:
image

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by DebapriyaJha**
## Description

In this pull request, I have made the following changes to the footer section design:

1) Updated the newsletter design to improve its visual appearance.
2) Added the website logo to the footer section for better branding and recognition.
3) Adjusted the alignment and positioning of the social media icons and other footer content for better layout and responsiveness across different screen sizes.

## Related Issues

- Closes #535 

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before:
fo1
fo2

After:
footer change

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
The updates to the footer section design aim to improve the overall user experience and visual appeal of the website. The newsletter design has been updated to make it more visually appealing and encourage user engagement. The addition of the website logo in the footer section reinforces the branding and helps users quickly identify the website they are visiting. Furthermore, the adjustments made to the alignment and positioning of the social media icons and other footer content ensure a consistent and responsive layout across different screen sizes, enhancing the overall usability of the website.

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
why this header is disturbed in you deployment

**Comment by DebapriyaJha** [comment]
@Anishkagupta04 I was assigned to redesign the footer section according to my idea so as per the website color theme and design I have only updated the footer section by moving the newsletter part above the footer section to make it more clearly visible and attractive and making other changes in the footer. I have made no changes to the header. It would be helpful for me if you could explain which part you are specifying.

**Comment by varshith257** [comment]
@DebapriyaJha Resolve conflicts

**Comment by DebapriyaJha** [comment]
@varshith257 Resolved the conflicts. Please merge the PR. 
Thank you

**Comment by varshith257** [comment]
@DebapriyaJha Good to merge after fixing conflicts. Tag me incase to get merged it

**Comment by DebapriyaJha** [comment]
@varshith257 check once I have resolved the conflicts

**Pull request closed without merging**
