### PR TITLE
Fixed Mobile view of Rate us

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
Fixed Mobile View of RateUs Page as i have mentioned it in this issue #894
Kindly Please go through this PR @varshith257 

https://github.com/user-attachments/assets/8a896349-9f29-4141-9279-842a36855776

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@Anjaliavv51 kindly go through this PR too

**Comment by sailaja-adapa** [comment]
@Anjaliavv51 is it okay???

**Comment by Anjaliavv51** [comment]
@sailaja-adapa it okay 

@aditya-bhaumik once PTAL this PR , their are just little difference 

Actual Repo

image

Changes Repo

image

**Comment by aditya-bhaumik** [comment]
image

@Anjaliavv51 its overflowing in small devices @sailaja-adapa please fix that

**Review by aditya-bhaumik — COMMENTED** [review]
image
@sailaja-adapa please fix this overflow issue rest everything is fine

**Comment by sailaja-adapa** [comment]
yeah ok @aditya-bhaumik

**Comment by sailaja-adapa** [comment]
is it okay now @aditya-bhaumik 

sfvd

**Comment by aditya-bhaumik** [comment]
@sailaja-adapa hi can you check the preview in this pull request i can still see it is overflowing in some devices

**Comment by sailaja-adapa** [comment]
Okk @aditya-bhaumik I will resolve and again update you soon

**Comment by aditya-bhaumik** [comment]
> Okk @aditya-bhaumik I will resolve and again update you soon

its okay the deploy had not loaded properly

**Comment by sailaja-adapa** [comment]
Is it fine now then? @aditya-bhaumik

**Comment by aditya-bhaumik** [comment]
@sailaja-adapa i checked in mobile now it is still overflowing sorry for the confusion

**Comment by sailaja-adapa** [comment]
It's okk fine @aditya-bhaumik

**Pull request closed without merging**
