### PR TITLE
Made the cardiologist doctor page responsive .

### PR DESCRIPTION
**Pull request by meetarora10**
## Description
I have made the cardiologist doctor page responsive .

## Related Issues
#894
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (746)
Screenshot (747)
Screenshot (748)

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by meetarora10** [comment]
@varshith257 please review this .

**Comment by meetarora10** [comment]
@varshith257 please review and merge.

**Comment by meetarora10** [comment]
@varshith257 kindly review this as well .

**Comment by varshith257** [comment]
@meetarora10 Fix conflicts and tag me to get merged

**Comment by meetarora10** [comment]
@varshith257 done .

**Pull request merged**
