### PR TITLE
Auto Label Added

### LINKED ISSUE #991: 📝[Documentation Update]: Bug , Enchancement and Documentation label to Issues & PR.
Automatic Addition of Bug , Enchancement and Documentation label to Issues

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#991

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #991 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Make sure to do the above after PR merging.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by varshith257** [comment]
@Anjaliavv51 See its workflow is failing

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 See its workflow is failing

As it's options are changed.

**Comment by Anjaliavv51** [comment]
"Settings" > "Actions" > "General" and under "Workflow permissions", select "Read and write permissions".
Should be made

**Comment by varshith257** [comment]
ok! let's do it later with @Anishkagupta04

**Comment by Anjaliavv51** [comment]
@varshith257 can u please revert the it , i have to change code in yml

**Comment by varshith257** [comment]
Submit another PR instead reverting it aginy

**Comment by Anjaliavv51** [comment]
Okay

**Pull request merged**
