### PR TITLE
Added refresher

### LINKED ISSUE #983: ✨[Feature Request]: A refresh hanger
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To refresh the page incase.

### Use Case

Used to refresh the page incase.

### Benefits

To refresh the page incase the server is slow.

### Add ScreenShots

https://github.com/user-attachments/assets/fac6ff57-7505-4a95-8056-6dbeb82722a9

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#983

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #983

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/9b05889c-9797-4ee7-858b-4c3a3deb7eb0

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
> @varshith257 please review the PR

@varshith257

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
