### PR TITLE
About us section - mobile responsive

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #894 

image
image

About us section has been made responsive across all devices

@Anishkagupta04 can you please check and approve?

### CODE REVIEW

**Comment by varshith257** [comment]
@Hemashree21 Please fix conflicts and check latest PR merged of about-us

**Comment by varshith257** [comment]
@Anjaliavv51 Take a look related to your recent changes

**Comment by Anjaliavv51** [comment]
@varshith257 I will check in both small and larger , then I will mention u.

**Comment by Anjaliavv51** [comment]
Screenshot_20240731_151959_Chrome

**Comment by Anjaliavv51** [comment]
@Hemashree21 please decrease the size of these containers.

**Comment by Anjaliavv51** [comment]
@Hemashree21 please remove the responsive for 
.about-us-community,
.about-us-event,
  .about-us-location,
  .about-us-product

**Comment by Hemashree21** [comment]
> @Hemashree21 please remove the responsive code for .about-us-community, .about-us-event, .about-us-location, .about-us-product

If I remove it, the layout is distorted.

image

**Comment by Anjaliavv51** [comment]
@Hemashree21 please update ur branch

**Comment by Anjaliavv51** [comment]
https://rapidoc.netlify.app/

This is the link

**Comment by Anjaliavv51** [comment]
@Hemashree21 please update ur branch and commit the changes.

**Comment by varshith257** [comment]
Is it ready to merge?

**Comment by Anjaliavv51** [comment]
> Is it ready to merge?

No

**Comment by Anjaliavv51** [comment]
@varshith257 changes are done.

U can review once and merge it.

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
