### PR TITLE
Redesigned the footer section

### LINKED ISSUE #510: ✨Redesign Footer Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The footer section is not aligned properly. Moreover, it is very large when it is supposed to be small

### Use Case

A better UI is important for better user experience

### Benefits

_No response_

### Add ScreenShots

image

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

The footer section was not aligned properly and most of its contents had disappeared. I redesigned it and fixed the alignments of its contents and brought back the disappeared items

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #510 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
BEFORE
image
AFTER
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Comment by Anishkagupta04** [comment]
please see into it 2 footers are there

**Comment by samarsajad** [comment]
> please see into it 2 footers are there

Ma'am there are not two footers. The first picture is from"before" I have mentioned it there. Please take a look @Anishkagupta04

**Comment by samarsajad** [comment]
> please see into it 2 footers are there

Ma'am can you please show me where you can see the two footers cause I just ran the code in my browser & only one green footer is showing.
The first picture is of the "before"

**Comment by samarsajad** [comment]
Can you please review my pull request @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
@samarsajad Everything is fine, I think the Rapidocs Newsletter section is good for older one than these changes. Can you add back it?

**Comment by samarsajad** [comment]
image
This is the current newsletter section @varshith257 You want me to make it like this or do you have something different in mind?

**Comment by samarsajad** [comment]
> @samarsajad Everything is fine, I think the Rapidocs Newsletter section is good for older one than these changes. Can you add back it?

image
Like this? @varshith257

**Comment by varshith257** [comment]
@samarsajad Yes

**Comment by samarsajad** [comment]
> @samarsajad Yes

Alright done 
image

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
@samarsajad See this

image

**Comment by samarsajad** [comment]
created a new pull request #604  Please take a look

**Pull request closed without merging**
