### PR TITLE
Added Rate us Option

### LINKED ISSUE #541: ✨ Add a Rate Us Option
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Use Case

It will help us to know what improvements we need to make

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin,
I added Rate us Option (updated) - Closes #541 
Kindly Please go through it 
Updations Include :
-> Increased Star Size when Selected
-> Added Project Colour Theme
-> Added Hover and Lighting Effect to Container
-> Added Toastify Messages to make website Responsive
-> Alligned Navbar Perfectly and Added Icons

@Anishkagupta04 @varshith257 Kindly Please go through it

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/161804629/74518467-32a4-41de-975b-aa2e3447078d

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@varshith257 can u please go through this PR

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
@sailaja-adapa Are you from BVRITN?

**Comment by sailaja-adapa** [comment]
@varshith257 No, I am from Shri Vishnu,Bhimavaram

**Comment by varshith257** [comment]
Ok, the steps in background of your profile look like our college and ID card too :)

**Comment by sailaja-adapa** [comment]
@varshith257  okkk :)

**Comment by sailaja-adapa** [comment]
@varshith257 my name is not visible at assignees in this PR

**Comment by varshith257** [comment]
I think there is need of assignee in the PR

**Comment by varshith257** [comment]
> @varshith257 Telugu??

Yes

**Comment by sailaja-adapa** [comment]
i think points won't be added to me if there isn't my profile in assignee @varshith257

**Comment by varshith257** [comment]
No, It will be added

**Comment by sailaja-adapa** [comment]
@varshith257 okk Thankk you :)

**Comment by sailaja-adapa** [comment]
@varshith257 Thank you so much :)

**Pull request merged**
