### PR TITLE
Div's in about us section were adjusted now in center with hover effect and appropriate color is given to icons and divs

### PR DESCRIPTION
**Pull request by SumithThota**
## Description

Div's in about-us section is adjusted in center with hover effect and appropriate color is given to icons and divs

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Before

Screenshot 2024-06-11 185435

## After
Screenshot 2024-06-11 174406
Screenshot 2024-06-11 174246

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/108344062/7ceed70f-0f02-40bc-bfa7-f3363a28c46a

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by SumithThota** [comment]
Successfully completed the Assigned task :-)

**Comment by SumithThota** [comment]
1)  There was no hower affect(Animation) to the div's {Doctors available, beds available,Nearest Labs, User Reviews}
2)  The color of the icons in above Div's are able to change now, when you hover on it.
3)  When you Rapidoc in a large screen then all the Div are aligned to left but now it is fixed with center justification
4) Bottom-width to are added

**Comment by SumithThota** [comment]
@Anishkagupta04, Please add level1 or level2 or level3 labels 
(Note: There should not be any space in between level and number 1 or 2 or 3)

**Comment by varshith257** [comment]
@Anishkagupta04 Isn't this hover effect demoting our project color scheme?

**Comment by SumithThota** [comment]
> @Anishkagupta04 Isn't this hover effect demoting our project color scheme?

No, since I have checked your project color scheme and applied the same to those hover effect

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by SumithThota** [comment]
@Anishkagupta04 Check this PR and inform if any changes reqiured

**Comment by varshith257** [comment]
@SumithThota Can you fix conflicts?

**Pull request closed without merging**
