### PR TITLE
Contact section is aligned properly 

### LINKED ISSUE #230: 🪲[Bug]: Contact section is aligned left
**Describe the bug**
Contact section is aligned left it should me aligned properly
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@Anishkagupta04 Please assign me this issue under GSSoC'24

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
## Description
Contact section is aligned properly  

[Please include a brief description of the changes or features added]
1. I have corrected the typo
2. Info section is moved at the left
3. Forms are aligned at the right

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #230 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
@Anishkagupta04 
I am contributing under GSSoC 24 and Please label and assign me this PR under GSSoC 24

### CODE REVIEW

**Comment by varshith257** [comment]
@SuhainaFathimaM Please post scr of changes

**Comment by SuhainaFathimaM** [comment]
@Anishkagupta04 
image

**Comment by Anishkagupta04** [comment]
Ig possible can you remove the right side of this name email ....etc coz contact us already have query page and it is repeatedly made if possible try to add a new feature

**Review by Anishkagupta04 — CHANGES_REQUESTED** [review]
>

**Comment by varshith257** [comment]
@SuhainaFathimaM Any updates on this?

**Comment by SuhainaFathimaM** [comment]
@Anishkagupta04 I am working on it..

**Comment by SuhainaFathimaM** [comment]
@Anishkagupta04 Please give me some suggestions to add the thing instead of contact section

**Comment by varshith257** [comment]
@SuhainaFathimaM Didn't get it?

**Comment by varshith257** [comment]
@SuhainaFathimaM Any updates on this?

**Comment by varshith257** [comment]
No activity

**Pull request closed without merging**
