### PR TITLE
🐞[Bug]: Fixes Proper alignment of Medicine.html

### LINKED ISSUE #920: 🐞[Bug]: Proper alignment of Medicine.html
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Page is not aligned properly and also header and footer sections , doesn't match with repo.

### Add ScreenShots

image

WhatsApp Image 2024-07-18 at 19 39 43_f923feab

WhatsApp Image 2024-07-18 at 19 39 48_af882e6a

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#920

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #920 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/61fcdf0b-e04c-4aee-aeca-d3d970b99acd

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by varshith257** [comment]
@Anjaliavv51 Can search bar and search button could be consistent with same sizes?

**Comment by Anjaliavv51** [comment]
@varshith257 okay

**Comment by Anjaliavv51** [comment]
@varshith257 changes are done please review the PR.

image

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
@Anjaliavv51 Fix the merge conflicts and looka good to merge

**Comment by Anjaliavv51** [comment]
@varshith257 conflicts are resolved.

**Comment by varshith257** [comment]
@Anjaliavv51 


Please be careful while resolving conflicts

**Comment by Anjaliavv51** [comment]
@varshith257 i saw that , i changed the code again please review it.

**Comment by Anjaliavv51** [comment]
@varshith257 please assign me this PR 
u didn't made this PR as assigned to me.

**Pull request merged**
