### PR TITLE
Enhanced About Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #437 

I have enhanced the about section and I have also made it responsive.

image

@Anishkagupta04 can you please check and let me know if any changes are required?

### CODE REVIEW

**Comment by varshith257** [comment]
@Hemashree21 Nice work! But colors should match the colors already used in a project. And everything is fine except it.

Can you make color scheme adjustments?

**Comment by Hemashree21** [comment]
image

@varshith257 I have made the changes in the color.

**Comment by varshith257** [comment]
@Hemashree21 Can you post a video of all this changes?

**Comment by Hemashree21** [comment]
> @Hemashree21 Can you post a video of all this changes?

https://screenrec.com/share/2EMeam9zqQ

**Comment by varshith257** [comment]
Great work @Hemashree21

**Comment by Hemashree21** [comment]
@varshith257 Thankyou!

**Pull request merged**
