### PR TITLE
📝[Documentation Update]: Modification of Readme.md file

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Related Issues
issue #404 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the Changes.

**Comment by varshith257** [comment]
@Anjaliavv51 This is good but README (Markdown files) doesn't;t embed custom styles. See this:

`<style> :root{ --ff-philosopher: "Philosopher", sans-serif; --ff-poppins: "Poppins", sans-serif; } </style>
`

This part of the code mayn't compile and appear as code in README

**Comment by Anjaliavv51** [comment]
@varshith257 should i remove it?

**Comment by varshith257** [comment]
Better embed the font styles in separate section i.e.NOTE section header and put the code  of <style></style>  naming as used fonts

**Comment by varshith257** [comment]
> @varshith257 should i remove it?

Then how the font can be used here as described in issue

**Comment by Anjaliavv51** [comment]
> > @varshith257 should i remove it?
> 
> Then how the font can be used here as described in issue

Can i write the Readme.md file code in HTML

**Comment by Anjaliavv51** [comment]
> > > @varshith257 should i remove it?
> > 
> > 
> > Then how the font can be used here as described in issue
> 
> Can i write the Readme.md file code in HTML form

?

**Comment by varshith257** [comment]
I think Reame files could be better in the Markdown files :)

**Comment by Anjaliavv51** [comment]
> I think Readme files could be better in the Markdown files :)

I will try to solve this

**Comment by varshith257** [comment]
Ok

**Comment by Anjaliavv51** [comment]
@varshith257 it not possible sorry

**Comment by Anjaliavv51** [comment]
@varshith257 instead i will do this  , a workflow , which allows a github user to automatically assign themselves and their is a condition that user can create only one issue at a time

**Comment by Anjaliavv51** [comment]
> @varshith257 instead i will do this  , a workflow , which allows a github user to automatically assign themselves and their is a condition that user can create only one issue at a time 

@varshith257

**Comment by varshith257** [comment]
@Anjaliavv51 I have fixed it. Meanwhile you add the existing screenshots of cloning etc..

**Comment by Anjaliavv51** [comment]
Okay

**Comment by varshith257** [comment]
> @varshith257 instead i will do this , a workflow , which allows a github user to automatically assign themselves and their is a condition that user can create only one issue at a time

IMO, It's not needed. First, we have to give a contributor a choice to open issues that have in their mind. If we apply the auto-assigning of issues, we can't know what the contributor for the issue opened and it also needed to be approved by PA. So, it mayn't be good to add

**Comment by Anjaliavv51** [comment]
> ## Related Issues
> issue #404 
> 
> ## Type of PR
> 
> - [ ] Bug fix
> - [ ] Feature enhancement
> - [X] Documentation update
> - [ ] Other (specify): _______________
> 
> ## Screenshots / videos (if applicable)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ## Checklist
> 
> - [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
> - [X] I have updated my branch and synced it with project `main` branch before making this PR
> - [X] I have performed a self-review of my code
> - [X] I have tested the changes thoroughly before submitting this pull request.
> - [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
> - [X] I have commented my code, particularly in hard-to-understand areas.
> 
> 
> 

It is edited

**Comment by varshith257** [comment]
Add this screenshots in the PR which had removed: 
   Screenshot (127)



this one too

   Screenshot (128)


for reference, see the current readme and add back the images there in the current README.md

**Comment by Anjaliavv51** [comment]
> Add this screenshots in the PR which had removed: 
>    Screenshot (127)
> 
> 
> 
> this one too
> 
>    Screenshot (128)
> 
> 
> for reference, see the current readme and add back the images there in the current README.md

Okay

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR ,changes are made

**Comment by varshith257** [comment]
One screenshot isn't loaded check it once in view file

**Comment by Anjaliavv51** [comment]
@varshith257 i can't see anything like that please send a screenshot

**Comment by Anjaliavv51** [comment]
@varshith257 now u can check i made changes in that.

**Comment by Anjaliavv51** [comment]
@varshith257 review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 what happened?

**Comment by varshith257** [comment]
Make the last line into center

**Comment by Anjaliavv51** [comment]
@varshith257 which last line?

**Comment by varshith257** [comment]
This one:
 <h3 style="text-align:center;font-size:2rem;">
If you find this project helpful, please consider giving it a star! </p>

**Comment by Anjaliavv51** [comment]
Now is it okay?

**Comment by Anjaliavv51** [comment]
@varshith257 i changed it please check

**Review by varshith257 — APPROVED** [review]

**Comment by Anjaliavv51** [comment]
@varshith257 is it okay now?

**Comment by varshith257** [comment]
@Anjaliavv51 Thanks

**Comment by Anjaliavv51** [comment]
@varshith257 added the labels?

**Pull request merged**
