### PR TITLE
News Page is been changed with Animated Buttons

### PR DESCRIPTION
**Pull request by AbheetHacker4278**
## Description

**In this I have changed the buttons in the news page with Cool Animated Buttons**

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes 

## Type of PR

- [x] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/114290748/0410c287-963e-4e78-a726-d1c341731fc5

BEFORE:
Screenshot 2024-06-18 024008

AFTER:
Screenshot 2024-06-18 162414

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
@Anishkagupta04 please review this PR and give me feedback and please assign this PR to me under Gssoc24

### CODE REVIEW

**Comment by AbheetHacker4278** [comment]
@Anishkagupta04 please check this out , i have done necessary changes

**Comment by AbheetHacker4278** [comment]
@varshith257 please check this PR

**Comment by varshith257** [comment]
@AbheetHacker4278 Good work! But let's also take @Anishkagupta04 's opinion for this new feature

**Comment by AbheetHacker4278** [comment]
> @AbheetHacker4278 Good work! But let's also take @Anishkagupta04 's opinion for this new feature

Okay no problem , its fine ✌️

**Comment by AbheetHacker4278** [comment]
> @AbheetHacker4278 Good work! But let's also take @Anishkagupta04 's opinion for this new feature

Also please assign this PR under gssoc24

**Comment by AbheetHacker4278** [comment]
@varshith257 Thanks for assigning this PR , i hope you merge this PR with main branch as soon as possible , Again Thanks  👍

**Comment by AbheetHacker4278** [comment]
@varshith257 please merge this PR

**Comment by AbheetHacker4278** [comment]
@varshith257 please merge my PR

**Review by AbheetHacker4278 — COMMENTED** [review]
All fine

**Review by AbheetHacker4278 — COMMENTED** [review]
Is there any issue with my PR

**Comment by AbheetHacker4278** [comment]
All checked has been passed successfully

**Comment by AbheetHacker4278** [comment]
@varshith257

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
