### PR TITLE
Fixes issue #949

### LINKED ISSUE #949: Validating Email
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Validating email, register the user if the entered email is valid.

### Use Case

Free from unauthorized login.

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
Validation of email

Validation of email using firebase, that ensures user to register if the entered email is valid email.
Verification is done by sending a verification email.

Prevent from unauthorized access.
- Closes #949 

## Type of PR

- [X] Bug fix
- [X] Feature enhancement

## Screenshots / videos (if applicable)
https://drive.google.com/file/d/1zmcGU6QB116CPJx0EuJAt3UaOYnscRkS/view?usp=drive_link

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 @Anishkagupta04 
Please review this PR and label it.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
Are there any changes to be made?

**Comment by varshith257** [comment]
I will let it review in Wednesday

**Comment by Bhattu-Anitha-07** [comment]
Ok @varshith257 
Can you please review PR opened in #948?
It was opened 2 days go, if you have time.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 please take a look over this.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 @Anishkagupta04 
Please review this PR and if any changes are needed please update.

**Comment by varshith257** [comment]
Can you fix merge conflicts?

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
How to fix it? I don't know the reason why the branch has conflicts.

**Comment by varshith257** [comment]
Someone PR has done recent changes to the pages you have done changes. Carefully solve them to reflect your changes with any distrupt.

OR else let me solve the merge conflicts and merge by EOD

**Comment by Bhattu-Anitha-07** [comment]
Ok @varshith257 
I will try solve it, if not possible I'll let you know.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 What are the steps to be done to resolve the conflicts, do I need to fork the repo again and make the changes?

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
Unknowingly closed the this PR by deleting the repository. I have opened a new PR for issue #949 in #994. Kindly review it.

**Pull request closed without merging**
