### PR TITLE
made the faq page responsive 

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
## Description

@varshith257  hi i have made the faq page responsive by adding a hamburgur icon for smaller screen so that the navbar is responsive 
made the footer resonsive and the elements in the page responsive removed unnecessary lines from the code 

#894 i have mentioned it in this issue  

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Before : 
image
image

After:
image
image
image

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@aditya-bhaumik LGTM. Can you also add respective icons for each navbar element? 

I would suggest to move right maybe then navbar elements to be consistent 

Even better if we move navbar to left something like this and also replace logo with RAPIDOC Text

**Comment by aditya-bhaumik** [comment]
@varshith257 hi i made the changes you requested can you check it please

image

**Comment by varshith257** [comment]
@aditya-bhaumik The content of page has hidden under navbar make sure it doesn't attached with it 


In navbar copyright mark overflowed . Need a fix

**Comment by varshith257** [comment]
Can reduce navbar size similiar to attached image above bunny?

**Comment by aditya-bhaumik** [comment]
@varshith257 hi i have fixed the copyright overflow and about the content above i dont thing we need heading for faq as we are reaching this page using faq link only but i am not removing it as it is helping the navbar from not covering the first question

**Comment by aditya-bhaumik** [comment]
@varshith257 hi I have fixed the extra space at the top of the footer. The rest of the issues are still unresolved, and I will try working on them later. I will create another pr when i fix the bug

**Review by varshith257 — APPROVED** [review]

**Comment by varshith257** [comment]
@aditya-bhaumik There is also small fix needed in the navbar. The service element gemot green block hover in it fix it too

**Comment by aditya-bhaumik** [comment]
> @aditya-bhaumik There is also small fix needed in the navbar. The service element gemot green block hover in it fix it too

sure i will make the changes and create another pr when i am free

**Pull request merged**
