### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aditijainnn**
## Description

Made changes in readme.md

## Related Issues

- Closes #
- #880

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Aditijainnn** [comment]
@Anishkagupta04 please review the changes

**Comment by varshith257** [comment]
@Aditijainnn Can you post a video or image of latest changes you have done?

**Comment by Aditijainnn** [comment]
> @Anishkagupta04 please review the changes

image
image
added toggle to go to top

**Comment by Aditijainnn** [comment]
> @Aditijainnn Can you post a video or image of latest changes you have done?

please merge my request

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
