### PR TITLE
🐞[Bug]: Bugs in style.css

### LINKED ISSUE #516: 🐞[Bug]: Bugs in style.css
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bugs in Style css

### Expected behavior

image

image

### Add ScreenShots of Bugs

image

image

image

image

image

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Description

Fixed Bugs in Style.css file.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #516 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

After Changes

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/8d39733a-8a31-4477-8665-ee34f0947b74

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257  please review the Changes.

**Comment by Anjaliavv51** [comment]
output in vercel


https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/e2fd3066-a7f1-48cf-b147-d1eebe63cb47

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 please review the PR.

**Comment by Anjaliavv51** [comment]
@varshith257 @Anishkagupta04 please review the changes

**Comment by Anishkagupta04** [comment]
please into the headings they are left align idk why

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 can I keep the screenshot

**Comment by Anishkagupta04** [comment]
Screenshot 2024-06-11 at 12 49 08 PM

**Comment by Anishkagupta04** [comment]
Screenshot 2024-06-11 at 12 50 01 PM

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 i will align the service header to center 1 min.

**Comment by varshith257** [comment]
@Anishkagupta04 PTAL

**Comment by varshith257** [comment]
@Anishkagupta04 Thanks for adding netifly deployment

**Comment by varshith257** [comment]
@Anjaliavv51 Maybe this could be an issu:
image

**Comment by varshith257** [comment]
image
Patient portal is fully distorted, we need to align them to be consistent in the flow

**Comment by varshith257** [comment]
Sam for the appointment page:  
image

**Comment by varshith257** [comment]
Here too:  
image

**Comment by varshith257** [comment]
image
  This one too

**Comment by Anjaliavv51** [comment]
@varshith257 I will look into it

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by Anjaliavv51** [comment]
@varshith257 please review the changes.

**Comment by varshith257** [comment]
PAtient portal, appointment form, etc.. are still distorted

**Comment by Anjaliavv51** [comment]
@varshith257 in issue i found about footer and service section

**Comment by Anjaliavv51** [comment]
@varshith257 below is the main index.html in Repo

image

**Comment by Anjaliavv51** [comment]
@varshith257 please check it

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by varshith257** [comment]
@Anjaliavv51 Almost everything seems fine. Can you also make update for patient portal?

**Comment by Anjaliavv51** [comment]
@varshith257 i would like , create another issue on Patiental Portal , as  code should be rewritten again

**Pull request merged**
