### PR TITLE
fixed overlapping

### LINKED ISSUE #868: 🐞[Bug]: The service section is overlapping
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer section is on top and navbar is not visible and everything is overlapping

### Expected behavior

the componentss are supposed to be in the right place without overlapping

### Add ScreenShots

image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Fixed overlapping of the services page

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #868 

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
Why navbar got misaligned?

**Comment by varshith257** [comment]
Is there any large gap after first section to second section in service page?

**Comment by samarsajad** [comment]
> Is there any large gap after first section to second section in service page?

I don't think so. I just checked the deploy preview it looks as expected. However if you want changed you can let me know @varshith257

**Comment by varshith257** [comment]
Is home also got misaligned? I am viewing it in mobile can't able to understand what happened

**Comment by samarsajad** [comment]
> Is home also got misaligned? I am viewing it in mobile can't able to understand what happened 

No the homepage is fine. @varshith257

**Comment by varshith257** [comment]
Ok, will review this PR later as code changes are more

**Comment by samarsajad** [comment]
> Ok, will review this PR later as code changes are more

Okay thank you so much. I've  many open pull requests in this repo. If you get time please review them too #869 & #842

**Pull request closed without merging**
