### PR TITLE
Fixed Mobile View of About Page

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
Fixed Mobile View of About Page as i have mentioned it in this issue #894 
Kindly Please go through this PR @varshith257 

aa

https://github.com/user-attachments/assets/3afe7e4c-90f3-4003-ae46-d1b09c0ef4d2

### CODE REVIEW

**Comment by sailaja-adapa** [comment]
@Anjaliavv51 kindly go through this PR too

**Comment by Anjaliavv51** [comment]
@varshith257 review the PR.

All changes are done , it is ready to get merge.

image

**Comment by sailaja-adapa** [comment]
@varshith257 please add level label too

**Comment by sailaja-adapa** [comment]
@varshith257 please add level label for this Merged PR

**Pull request merged**
