### PR TITLE
Navbar Responsiveness and Hamburger Button

### LINKED ISSUE #598: ✨[Feature Request]: Responsive Navbar with Toggle Button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The feature described is a Responsive Navigation Bar with a Toggle Button designed to adapt seamlessly across different screen sizes, particularly enhancing usability on mobile devices.

### Use Case

The responsive navigation bar is a user interface component that adjusts its layout and behavior based on the screen size of the device being used. It includes a toggle button that allows users to show or hide the navigation links when viewed on smaller screens, such as smartphones and tablets.

### Benefits

It will make the navbar responsive for the small screens.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RohithChitrada**
## Description

[Please include a brief description of the changes or features added]
Made  navigation bar (navbar) to adapt to different screen sizes and orientations. The hamburger button, typically represented by three stacked horizontal lines, is a common solution for handling navigation on smaller screens
## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #598 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-06-21 210928

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
some error is there all checks are not passed

**Comment by RohithChitrada** [comment]
All four checks are passed and remaining 3 are neutra. If you find any error just tell me about it in detail

**Comment by RohithChitrada** [comment]
Hi @Anishkagupta04 ,
I wanted to follow up regarding the pull request (PR) I submitted two weeks ago. I understand everyone is busy, but I wanted to check if there's been any progress or feedback on the PR. Please let me know if there's anything further needed from my side.

Looking forward to your response.

**Comment by RohithChitrada** [comment]
Hi @Anishkagupta04,

I wanted to follow up on my Level-2 issue. I submitted a PR three weeks ago, but it seems it was closed for some reason. Could you please merge it so I can resubmit the PR?

Looking forward to your response.

**Pull request closed without merging**
