### PR TITLE
Updated doctor.css

### LINKED ISSUE #385: ✨[Feature Request]: In appoint a doctor page, clicking on the logo should direct you to home.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the appoint doctor page there is no way to return to home page.
I want to make it in such a way that on clicking the logo user is directed to homepage.

### Use Case

I will help to exit from the 'Appoint' page to the home page

### Benefits

_No response_

### Add ScreenShots

image

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ayush-848**
## Description

I have added the required elements so that on clicking the logo page is redirected to home.

## Related Issues

- Closes #385 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
In the doc.html, for the logo I added the link for the index.html
In the doc.css, I gave it a hover effect and cursor pointer

### CODE REVIEW

**Comment by ayush-848** [comment]
@Anishkagupta04 The doc.html file is opening differently here.
So that's why I cant provide a screen shot.

**Comment by ayush-848** [comment]
@Anishkagupta04 

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/126975547/f2359a83-8911-4278-8213-22d6da32fdac

**Comment by ayush-848** [comment]
@Anishkagupta04 please check the PR

**Comment by ayush-848** [comment]
@Anishkagupta04 Please check it

**Comment by ayush-848** [comment]
@Anishkagupta04 I have solved the merging conflicts please merge the PR and assign this to me

**Comment by ayush-848** [comment]
@varshith257 Please check the PR if there is any issue to fix here, you can tell me

**Comment by varshith257** [comment]
@ayush-848 Can I know where you updated code related of redirecting to home ?

**Comment by ayush-848** [comment]
> @ayush-848 Can I know where you updated code related of redirecting to home ?

In doc.html

**Comment by ayush-848** [comment]
@varshith257 please assign this PR to me in this page

**Pull request merged**
