### PR TITLE
Update Date input for appointment

### LINKED ISSUE #19: Appointment Date
Right now the user has to insert date manually and i believe that it would be better if we input date in calendar format by providing the user with a date input.

Kindly assign this to me to work under GSSOC contribution

### PR DESCRIPTION
**Pull request by CS251000**
Earlier while making the appointment Date had to be input as a string

Now a small calendar will popup to input the data

RESOLVES #19 

Screenshot 2024-05-15 at 8 21 27 PM

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
Size of the box is too large

**Comment by CS251000** [comment]
@Anishkagupta04 This is the standard date input size websites use and i believe this will work good in real life use

**Comment by Anishkagupta04** [comment]
This is not looking good

**Comment by Anishkagupta04** [comment]
The way it is formed is soo mess up plss undo all this

**Comment by Anishkagupta04** [comment]
You can add this instead of adding the whole appointment page on the website itself

**Comment by varshith257** [comment]
Closing! No activity

**Pull request closed without merging**
