### PR TITLE
New twitter icon

### LINKED ISSUE #67: Replace old twitter icon with new icon
On the [webiste](https://69glitch.github.io/RapiDoc/#) under contact section the twitter logo is still the old one.
It needs to be updated.

### PR DESCRIPTION
**Pull request by antriksh-9**
I have updated the old twitter logo to the new one, for this I have used fontawesome icons libraries. 
Also, I have updated the other social icons with fontawesome icon library.

Closes #67.

Screenshot 2024-05-14 001753

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
great job

**Comment by antriksh-9** [comment]
Hey @Anishkagupta04, please assign necessary labels to my PR.

**Comment by antriksh-9** [comment]
> Hey @Anishkagupta04, please assign necessary labels to my PR.

Please assign labels to my PR.

**Comment by antriksh-9** [comment]
> > Hey @Anishkagupta04, please assign necessary labels to my PR.
> 
> Please assign labels to my PR.

@Anishkagupta004 ?

**Comment by antriksh-9** [comment]
> Hey @Anishkagupta04, please assign necessary labels to my PR.

@varshith257

**Pull request merged**
