### PR TITLE
updated home page css

### LINKED ISSUE #794: 🐞[Bug]:  CSS of website in mobile view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

image

fixing css

### Expected behavior

fixed margin and all

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Description
Fixed

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142989448/1bed9969-3355-4338-ba5d-1991797a8d0c

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #794 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@varshith257 please check this

**Comment by varshith257** [comment]
I will review it by EOD. Till then I will tag @Anishkagupta04 for review

**Comment by varshith257** [comment]
And a quick review, the Footer is looking large, and there is still to be improvedd and patient login and appointment form i think you can reduce long blocks and give padding without sticking it to the homwpage

**Comment by dhairyagothi** [comment]
what changes you want can you please share ss of changes you want for better understanding i think its look good in my mobile phone 
please tell me @varshith257 whenever you are free from your work  no need to hurry thanks.

**Comment by dhairyagothi** [comment]
@varshith257 please check this

**Comment by varshith257** [comment]
To keep better for testimonials better implement < and > buttons to make easier for users to switch testimonials and also if needed add some timeout to move them automatically.


And for footer all links keep in a same row move the below Legal Section to above 3 in a row and keep subscribe news letter to left and move footer details and social links to left if needed.

Appointment form you can reduce the size of it. It looking like sticked in home page

PS: I am not going with technical aspects. I am on other works. So given a wrap up feedback :)

Tage if you need any explanation of them

**Comment by dhairyagothi** [comment]
> To keep better for testimonials better implement < and > buttons to make easier for users to switch testimonials and also if needed add some timeout to move them automatically.
> 
> And for footer all links keep in a same row move the below Legal Section to above 3 in a row and keep subscribe news letter to left and move footer details and social links to left if needed.
> 
> Appointment form you can reduce the size of it. It looking like sticked in home page
> 
> PS: I am not going with technical aspects. I am on other works. So given a wrap up feedback :)
> 
> Tag me if you need any explanation of them

okay @varshith257 i will do changes about footer i think its look good in mobile view . i have made changes only for mobile view :)

**Comment by varshith257** [comment]
I am referencing for the same for mobile view and it's feel like footer is big so make those changes let's see how it results

**Comment by dhairyagothi** [comment]
Screenshot 2024-07-10 014014
Screenshot 2024-07-10 014023

@varshith257 now check bro  :|

**Comment by dhairyagothi** [comment]
@varshith257 please check it and tell me if anything else i have to change else please merge the PR

**Comment by varshith257** [comment]
The news letter subscribe elements can be expanded horizontally like

Text within 2 lines.        Mail box.        Subscribe button

**Comment by varshith257** [comment]
And social media buttons move to center and any updates of testimonials section!

**Comment by dhairyagothi** [comment]
> And social media buttons move to center and any updates of testimonials section?

ya i am trying to increase it width

**Comment by dhairyagothi** [comment]
any other changes needed @varshith257 ?

**Comment by varshith257** [comment]
It's fine with adjusting above changes. If you feel difficulty for testimonials section. Raise a new issue and I will send sample design of it

**Comment by dhairyagothi** [comment]
Screenshot 2024-07-10 102533
Screenshot 2024-07-10 102541

**Comment by varshith257** [comment]
I mean newsletter section should expanded horizontally something like this 

Text. ----->.  Mail box.       --->.  Subscribe Button

**Comment by dhairyagothi** [comment]
@varshith257 check this i think it is

> I mean newsletter section should expanded horizontally something like this
> 
> Text. ----->. Mail box. --->. Subscribe Button

image

this one @varshith257

**Comment by varshith257** [comment]
You got it wrong. Ahh, something like below:

**Comment by varshith257** [comment]
@dhairyagothi You got it wrong. Ahh, something like below:

image

**Comment by dhairyagothi** [comment]
image

@varshith257 now : )

**Comment by varshith257** [comment]
@dhairyagothi Once see the screenshot we attached you can reduce the sizes of them in the mobile view

**Comment by dhairyagothi** [comment]
> @dhairyagothi Once see the screenshot we attached you can reduce the sizes of them in the mobile view

what i have to do i dont get it ?

**Comment by varshith257** [comment]
In media width make email block and subscribe button side by side as attached in the image and you can reduce their sizes in media screen

**Comment by dhairyagothi** [comment]
@varshith257 any other changes needed ?

**Comment by dhairyagothi** [comment]
image

@varshith257 check this

**Comment by dhairyagothi** [comment]
@varshith257 please merge the PR

**Comment by varshith257** [comment]
@dhairyagothi  The footer got misaligned. Check in the deploy

**Comment by dhairyagothi** [comment]
> @dhairyagothi The footer got misaligned. Check in the deployI

IT IS ASKING FOR ACCESS

**Comment by varshith257** [comment]
Check it in netifly deployment in above. Vercel couldn't be accessed

**Comment by dhairyagothi** [comment]
fixed @varshith257 
please assign PR to me

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
