### PR TITLE
🐞[Bug]: Favicon and Color's

### LINKED ISSUE #538: 🐞[Bug]: Favicon and Color's
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

##Missing of favicon's

image

image

##Overlap

image

##Colors in dex.html file 

image

### Expected behavior

Two HTML files , doesn't have any favicon elements so i would like to add them.
And also wanted to adjust the image and Rapidoc heading which are in news.html file.
Wanted to change the colors in dex.html file from Yellow Green.

### Add ScreenShots

Added in Bug section.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## Description

##Missing of favicon's

image

image

##Overlap

image

##Colors in dex.html file 

image

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #538  #534

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

image

image

image

image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the Changes

**Comment by varshith257** [comment]
@Anjaliavv51 Can you make an appointment form and contact us form align properly? It is looking weird  with gaps and missing alignment

**Comment by Anjaliavv51** [comment]
@varshith257 sure I will remove the gaps

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR

**Comment by Anishkagupta04** [comment]
Thankyou for your contribution

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 @varshith257 please add level labels

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 @varshith257 please add level labels

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 @varshith257 please add level labels

**Comment by Anjaliavv51** [comment]
@varshith257 this PR contains both issues

**Comment by Anjaliavv51** [comment]
@varshith257 this PR contains both issues #538 #534 please check and add Level label.

**Pull request merged**
