### PR TITLE
Added responsiveness for doctor type ent

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

- Made the Doctor type "ENT" page responsive for various screens like Tablet(768px), Mobile-L (425px) & Mobile-M (375px)

## Related Issues

-  Part of #894 

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/db0a55ca-72cb-49c1-8b0c-6a76a747645d

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@varshith257 Please review and merge this PR

**Comment by varshith257** [comment]
Remove maxcare image and also better if we add footer and navbar aligning home page

**Comment by Asymtode712** [comment]
> Remove maxcare image and also better if we add footer and navbar aligning home page

Sure

**Comment by varshith257** [comment]
Follow with the changes discussed here in PR 
-  https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/pull/895

**Comment by Asymtode712** [comment]
@varshith257 Done with the changes.....


https://github.com/user-attachments/assets/35327454-2d35-4065-8c8e-60343490f37b

**Comment by varshith257** [comment]
Can you fix the conflicts and tag me?

**Comment by Asymtode712** [comment]
@varshith257 Conflicts resolved.....Kindly check the PR

**Pull request merged**
