### PR TITLE
fix message box , text in contact us add hovering effect in cards of about us and emergency add proper link to doctors available and user review

### LINKED ISSUE #636: 🐞[Bug]:  contact section text is not visible , message box is of small size , submit button not aligned
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 while writing on contact page the text written is not visible , message box is not of same size as others and submit button is not aligned

### Expected behavior

while writing on contact page the text written must be visible to us , the message box must be of same size as others and submit button must be properly aligned

### Add ScreenShots

1.  before:

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159682348/96d3185b-822c-48c0-9cbf-c6dd35652b53

after :

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159682348/75ef38ca-d838-44ac-a1e2-a2898fe4dcc2

2. before :

Screenshot 2024-06-18 185024
 after :  
image

3.before :
Screenshot 2024-06-18 173741
after :
Screenshot 2024-06-18 183357

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
fixex 636

## Description

fix message box , text in contact us add hovering effect in cards of about us and emergency add proper link to doctors available and user review

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #636 

## Type of PR

- [X] Bug fix
- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/159682348/c938c622-c682-4e19-84b8-0149b465a11f

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
closed #638 and opened this

### CODE REVIEW

**Comment by ANKeshri** [comment]
@Anshika14528 please review and erge my pull request

**Comment by Anishkagupta04** [comment]
thankyou for your contribution

**Comment by ANKeshri** [comment]
> thankyou for your contribution
@Anishkagupta04 mam please give level 1 and gssoc labels to it

**Comment by ANKeshri** [comment]
@Anishkagupta04 please give level to this pr

**Pull request merged**
