### PR TITLE
fixed css of service page

### LINKED ISSUE #820: 🐞[Bug]:  Fixing Complete CSS of Delivery page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

image

fixing CSS in mobile view

### Expected behavior

making website responsive

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #820 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by varshith257** [comment]
@dhairyagothi Can you move Get started and contact us pages to centre, everything is fine except above and looks good to merge

**Comment by dhairyagothi** [comment]
image


@varshith257 have a look on it

**Comment by varshith257** [comment]
@dhairyagothi Can you see at netifly deploy , their view of  page got rendered two times check it out and in website view the image should be beside the section text

**Comment by dhairyagothi** [comment]
@varshith257 done please check and merge PR asap

**Comment by dhairyagothi** [comment]
@varshith257 please have a look

**Comment by dhairyagothi** [comment]
@varshith257 please merge PR

**Comment by dhairyagothi** [comment]
please merge PR @varshith257

**Comment by varshith257** [comment]
Hey! I got busy with exams. And I follow up with the other contributers review of this PR.

@Pruthaa17 @Anjaliavv51 @aditya-bhaumik Can you look at the PR changes are good at mobile and web view? If needed request changes in the PR or approve the PR

**Comment by aditya-bhaumik** [comment]
@dhairyagothi @varshith257 hi i think everything is fine except 2 things the navbar should be similar to the main page navbar 
image
image

as it is same in all the pages except this page the elements can be different but the color scheme should be similar

image

the page is overflowing in small devices rest everything is good

**Comment by dhairyagothi** [comment]
hey @aditya-bhaumik i am also from vit bhopal 😂

**Comment by Anjaliavv51** [comment]
@dhairyagothi u have removed id names in footer , which is used to Reveal elements on scroll

**Comment by dhairyagothi** [comment]
okay i will do changes @aditya-bhaumik @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@dhairyagothi 

image


please minimize the dimensions of Make an Appointmnet section.

**Comment by Anjaliavv51** [comment]
@dhairyagothi please check the mentioned changes.

**Comment by dhairyagothi** [comment]
> @dhairyagothi please check the mentioned changes.

ok i will do asap

**Pull request closed without merging**
