### PR TITLE
Fixes issue no. #931

### LINKED ISSUE #931: Improving Navbar in Find a doctor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello PA,

Navbar in Find a doctor page is looking so dull, and some styles are not even applied.
Please assign this issue to me, will work on this.

### Expected behavior

Improved navbar in Find a doctor

### Add ScreenShots

Before:
image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
Improved navbar alognments and styling in Find a doctor page and new page
- Closes #931

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
## Screenshots / videos (if applicable)
Before:
image

After:
Find a doctor-
image
News-
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@Anishkagupta04  @varshith257 
Please review this PR and assign labels.
Thank you..

**Comment by varshith257** [comment]
@aditya-bhaumik @Anjaliavv51 PTAL

**Comment by Anjaliavv51** [comment]
@varshith257 it's good.

**Comment by Bhattu-Anitha-07** [comment]
@Anishkagupta04 @varshith257 
Can you please add labels to this issue.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
Thank you @varshith257 
Will contribute more.

**Pull request merged**
