### PR TITLE
Added Footer in Terms and Condition Page

### LINKED ISSUE #830: 🐞[Bug]: Add Footer and Navbar in the Terms and Condition Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @varshith257 

There is an absence of footer in terms and condition page 
For consistency across to the website I would like add a footer just like home page T and c page

image

Please assign this issue to me Under GSSOC24?

### Expected behavior

N/A

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description
Hey @Anishkagupta04  and @varshith257 
 
I have Added Footer in Terms and Condition Page

## Related Issues

- Closes #830 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

https://github.com/user-attachments/assets/761159e2-bfb1-4ca1-94fd-f95049970bc1

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@varshith257 Please merge this PR as i need this point to score in leaderboard

**Comment by RadhikaMalpani1702** [comment]
@varshith257 Can you please merge it

**Comment by varshith257** [comment]
@Pruthaa17 @Anjaliavv51 @aditya-bhaumik Have a look at this PR

**Comment by Anjaliavv51** [comment]
@varshith257 this PR can be merged , all changes meantioned by her are done , check the below screenshoot. 

image

**Comment by varshith257** [comment]
@Anjaliavv51 Is it good with alignment and I can't see the navbar and some gaps before footer of page in deploy preview from mobile

**Comment by aditya-bhaumik** [comment]
@RadhikaMalpani1702 please add the navbar in the page also

**Comment by Anjaliavv51** [comment]
@RadhikaMalpani1702 their is missing of social icons.

image


Add also change the favicon of the webapage to rd.png image in images folder.

image


And also minimize the space above footer

image

Make sure the header and footer matches , in font ,color and size.

**Comment by Anjaliavv51** [comment]
@varshith257 those are the changes that should be done by @RadhikaMalpani1702

**Comment by Anjaliavv51** [comment]
@RadhikaMalpani1702 please view the above changes.

**Comment by varshith257** [comment]
@RadhikaMalpani1702 Looks good to merge and update with social icons

**Comment by varshith257** [comment]
@RadhikaMalpani1702 Can you align footer with latest changes done in home page footer and tag me to get quick attention to merge this PR

**Pull request closed without merging**
