### PR TITLE
Made the Find A Doctor/Doctor Experience page responsive .

### LINKED ISSUE #894: [ Priority] Make Website Mobile Responsive
We are introducing a new series of issue. It works as parent issue for all. 

**Requirements:**

1) Make all pages mobile responsive 
2) Navbar of every page should align with home page and mobile responsive 
3) Footer also need to be align with the homepage footer.
4) Every change should adhere to color scheme of website.

**Note:**

- This works as parent issue. Don't ask for assign. 

- Submit a PR directly with appropriate changes to make a page mobile responsive.

- Each contributor can submit any number of PRs. Each for a page to make mobile responsive.

-  Each PR will be awarded level 3 for it.

### PR DESCRIPTION
**Pull request by meetarora10**
## Description

Made the Find A Doctor/Doctor Experience page responsive . Made changes in navbar , main content , footer.

## Related Issues
#894
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes 

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot (740)
Screenshot (738)
Screenshot (741)
## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by meetarora10** [comment]
Also added icons on the navbar similar to home Page

**Comment by meetarora10** [comment]
Screenshot (745)

**Comment by meetarora10** [comment]
@varshith257 please review and merge this .

**Comment by meetarora10** [comment]
@varshith257 please have a look .

**Comment by meetarora10** [comment]
@varshith257 please review and merge.

**Comment by varshith257** [comment]
Will merge all the linked issues of mobile responsive together.

**Comment by varshith257** [comment]
@Anjaliavv51 PTAL

/approve or request changes

**Comment by Anjaliavv51** [comment]
@meetarora10 reduce the gap after in the below ss

image

and also in footer y the below content is moved to left side at the bottom?

image

**Comment by meetarora10** [comment]
Ok @Anjaliavv51

**Comment by meetarora10** [comment]
@Anjaliavv51 @varshith257 done changes .

**Comment by Anjaliavv51** [comment]
@meetarora10 missing of nav bar and in footer sentence is overflowed

Screenshot_20240729_075713_Chrome
Screenshot_20240729_075716_Chrome

**Comment by varshith257** [comment]
@meetarora10 Do  above changes as requested and looks good to mege

**Comment by meetarora10** [comment]
@Anjaliavv51 @varshith257 done .

**Comment by meetarora10** [comment]
Screenshot (889)
Screenshot (890)
Screenshot (891)

**Comment by meetarora10** [comment]
@Anjaliavv51 @varshith257 please have a look .

**Pull request merged**
