### PR TITLE
Added Style Vertical Scrollbar Matching to The Website Theme 

### LINKED ISSUE #764: Style Vertical Scrollbar Matching to The Website Theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @varshith257  and @Anishkagupta04 

I would like to Style Vertical Scrollbar Matching to The Website design Theme.

image

Could you please assign me this issue under GSSOC24 ?

### Use Case

To look more visually appealing and match the website design theme . 

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description
Hey @Anishkagupta04 and @varshith257 

I have added a vertical scrollbar across all the pages to ensure consistency.
## Related Issues

- Closes #764 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
Hey @varshith257 Please take a look

**Comment by RadhikaMalpani1702** [comment]
@varshith257  Please merge this PR

**Comment by varshith257** [comment]
@RadhikaMalpani1702 Why the code deletions and additions are high in this PR? I can't verify watching it in mobile

**Comment by RadhikaMalpani1702** [comment]
@varshith257  Don't worry, I just formatted the document to organize the code, that's why it is showing

**Comment by varshith257** [comment]
I think we need to add format and lint check workflows

**Comment by varshith257** [comment]
@RadhikaMalpani1702 Looks good to merge and can you also replace the current vertical scrollbar color to mobile too it's appearing black in it

**Comment by RadhikaMalpani1702** [comment]
@varshith257 Vertical scrollbars are not needed in mobile views as there are multiple browsers in mobile that won't reflect the changes

**Comment by RadhikaMalpani1702** [comment]
@varshith257  Please add the labels

**Pull request merged**
