### PR TITLE
Fixes issue #1041

### LINKED ISSUE #1041: 🐞[Bug]: Improvement of navbar in "Find a doctor" page and "News" page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello PA,
The navbar on the "Find a Doctor" page is not styled properly. Additionally, the nav items on the "News" page are not aligned correctly.

### Expected behavior

Proper alignement and styling of navbar.

### Add ScreenShots

Before:
image
image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Bhattu-Anitha-07**
## Description

Proper Alignment of navbar items in Find a doctor page and News page.

- Closes #1041 

## Type of PR

- [X] Bug fix

## Screenshots / videos (if applicable)
Before:
image
image
After:
image
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 @Anishkagupta04 
Kindly review this PR.
Thank you.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
The number of changed files is a bit higher because I forked the repo yesterday, but someone else's PR got merged in the meantime.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
Please review this PR.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 please review this PR.

**Comment by varshith257** [comment]
I didn't see any changes related to navbar in PR

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
I added icons to the nav items on the "Find a Doctor" page, aligned the nav items into a single row on the "News" page, and added an icon at the top left.
These are the changes I made.

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
Shall I close this pull request and open a new one?

**Comment by Bhattu-Anitha-07** [comment]
@varshith257 
Please tell me whether I need to close this PR and open new one.

**Comment by Bhattu-Anitha-07** [comment]
Ok @varshith257

**Pull request closed without merging**
