### PR TITLE
Added Blood Test Page 

### LINKED ISSUE #365: ✨[Feature Request]: Blood Test Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The blood test icon leads to the homepage and has not been built. Features such as, type of test, method of choosing collection of the sample, available slots, pricing, etc would be added.

### Use Case

Adding detailed features to the blood test section, such as type of test, sample collection method, available slots, and pricing, enhances user experience by providing clarity, flexibility, efficient scheduling, and transparent pricing. This empowers users to make informed decisions, save time, and trust the service, leading to higher satisfaction and convenience.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Created a blood test page where the user can book for the tests 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/163805e8-b5cc-412d-aeb9-4910036b225e

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
We need @Anishkagupta04 review here

**Comment by samarsajad** [comment]
@Anishkagupta04  Can u please review it so that i can start building other  pages for the website as well?

**Comment by Anishkagupta04** [comment]
can you tell which button iterates it to the blood bank page as i have tried seeing it is not showing

**Comment by samarsajad** [comment]
yeah i just realised it is not linked with the main index.html. Sorry for the inconvenience. Please check #500  that resolves the issue in this one @Anishkagupta04 @varshith257

**Pull request closed without merging**
