### PR TITLE
add hover and size of social icons of footer in find doctor page

### LINKED ISSUE #867: ✨[Feature Request]: Make footer social icons of find doctor just i made in home page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add hovering effect on social icons

### Use Case

add hovering effect on social icons

### Benefits

add hovering effect on social icons

### Add ScreenShots

before : 

https://github.com/user-attachments/assets/ccf39d40-4b75-41c7-a54a-d614223590a9

want to make like this : 

https://github.com/user-attachments/assets/73512054-62a8-4d1a-92ac-4ce27a0b56a4

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ANKeshri**
## Description

add hover effect in social icons of footer and resize the footer 

## Related Issues

- Closes #867 

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/394e85ef-90d8-4539-859c-8d227f6a79f2

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by ANKeshri** [comment]
@varshith257 please review once and merge this pr

**Comment by varshith257** [comment]
Why subscribe button and news letter section misaligned?

**Comment by ANKeshri** [comment]
> Why subscribe button and news letter section misaligned?

It is asking it was earlier you can see here 
https://github.com/user-attachments/assets/ccf39d40-4b75-41c7-a54a-d614223590a9

**Comment by ANKeshri** [comment]
@varshith257 i have made it just like home page see below . 


https://github.com/user-attachments/assets/117f337a-7940-4e21-a549-8085a2e6e3b2

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
