### PR TITLE
💡[FEATURE]: 🌟 Reveal Elements On Scroll 🌟

### PR DESCRIPTION
**Pull request by Anjaliavv51**
issue #103

Before Changes:
[Before Changes.zip](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/files/15331142/Before.Changes.zip)

After Changes:
[After Changes.zip](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/files/15331129/After.Changes.zip)

### Checklist

- [X] I have gone through the [contributing guide](## PR Description

### Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] Is this a bug fix/enhancement/documentation changes

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] Is this a bug fix/enhancement/documentation changes
- [X] Part of GSSOC
- [X] Tested for any breaking changes
- [X] Other relevant checks completed

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [X] I Agree

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
> issue #103
> 
> Before Changes:
> [Before Changes.zip](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/files/15331142/Before.Changes.zip)
> 
> 
> After Changes:
> [After Changes.zip](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/files/15331129/After.Changes.zip)
> 
> ### Checklist
> 
> - [X] I have gone through the [contributing guide](## PR Description
> 
> ### Checklist
> 
> - [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
> - [X] I have updated my branch and synced it with project `main` branch before making this PR
> - [X] Is this a bug fix/enhancement/documentation changes
> 
> 
> ## Undertaking
> 
> I declare that: 
> 
> 1. The content I am submitting is original and has not been plagiarized.  
> 2. No portion of the work has been copied from any other source without proper attribution.  
> 3. The work has been checked for plagiarism, and I assure its authenticity.
> - [X] I have updated my branch and synced it with project `main` branch before making this PR
> - [X] Is this a bug fix/enhancement/documentation changes
> - [X] Part of GSSOC
> - [X] Tested for any breaking changes
> - [X] Other relevant checks completed
> 
> 
> I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 
> 
> - [X] I Agree
> 

Here , before changes zip file is their

**Comment by Anjaliavv51** [comment]
> Can't download them. Can send screenshot of them? and also resolve the conflicts of index.html

Okay

**Comment by Anjaliavv51** [comment]
@varshith257 conflicts are resolved

**Comment by varshith257** [comment]
@Anishkagupta04 will review this PR

**Comment by Anjaliavv51** [comment]
@Anishkagupta04 please review the changes

**Comment by varshith257** [comment]
@Anjaliavv51 Can resolve the conflicts. Glas to see you on the GSSOC leaderboard

**Pull request closed without merging**
