### PR TITLE
Enhanced Appointment form with improved visual design and user-friendly UI/UX Issue #263

### PR DESCRIPTION
**Pull request by TARUN2K3**
Enhanced Appointment form with improved visual design and user-friendly features Issue #263

## Description

- **Visual Enhancements**
  - Added consistent shadow effect for better visual appeal
  - Set default font to 'Roboto' for a modern look
  - Centered layout and applied a background color for better focus

- **Form Improvements**
  - Improved form input, button, and textarea styles for clarity and ease of use
  - Highlighted mandatory fields clearly
  - Included icons and graphics to guide users

- **Appointment Card**
  - Enhanced card appearance with new shadow and padding adjustments

## Related Issues

Frustrated when users struggle to complete the appointment form due to its lack of visual appeal and user-friendly Appearance. 

## Type of PR

- [] Bug fix
- [X] Feature enhancement
- [] Documentation update
- [] Other 

## Screenshots / videos (if applicable)
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Visual aids can help in understanding the potential improvements and the positive impact they could have on the user experience.

### CODE REVIEW

**Comment by TARUN2K3** [comment]
@varshith257 
The changes in this pull request are now ready for merging into the main branch. I've thoroughly tested the changes to ensure they integrate smoothly with the existing codebase.

**Comment by varshith257** [comment]
Fix conflicts

**Comment by Anishkagupta04** [comment]
resolve conflict

**Comment by varshith257** [comment]
Closing due to inactivity

**Pull request closed without merging**
