### PR TITLE
fixed overlapping

### LINKED ISSUE #425: 🐞[Bug]:  Many sections overlapping in the Patient Portal Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Patient portal is overflown

### Expected behavior

Everything should be in place and visible

### Add ScreenShots

image

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Fixed the patient portal , doctor section and appointment section. They were overlapping and patient portal section was appearing twice. I also enhanced the CSS for the appointment section to make it go in-line with the rest of the webpage

## Related Issues

None

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before
image
After

image

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC24

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @Anishkagupta04 @varshith257

**Comment by varshith257** [comment]
@samarsajad Can you create a new issue for fixing the responsiveness to the patient portal?  or maybe you can go with implementing a blood test feature as it is an important one.

cc: @Anjaliavv51 Have a look and create an issue for it.

**Comment by varshith257** [comment]
@samarsajad I think you have deleted the appointment section. Have a look at the PR changes:

```
            <div class="row">
              <div class="col-md-12 form-group mt-3">

                <select name="hospital" id="hospital" class="form-select">
                  <option value="">Select Hospital</option>
                  <!-- Populate with available hospitals -->
                  <option value="Hospital 1">Hospital 1</option>
                  <option value="Hospital 2">Hospital 2</option>
                  <option value="Hospital 3">Hospital 3</option>
```

**Comment by samarsajad** [comment]
The code for patient portal existed twice just below one another. I deleted one of them as they were the same. Please take a look at the screenshot I attached with my pull request@varshith257 @Anishkagupta04

**Comment by samarsajad** [comment]
> @samarsajad I think you have deleted the appointment section. Have a look at the PR changes:
> 
> ```
>             <div class="row">
>               <div class="col-md-12 form-group mt-3">
> 
>                 <select name="hospital" id="hospital" class="form-select">
>                   <option value="">Select Hospital</option>
>                   
>                   <option value="Hospital 1">Hospital 1</option>
>                   <option value="Hospital 2">Hospital 2</option>
>                   <option value="Hospital 3">Hospital 3</option>
> ```

No it's still there. Please take a look at the screenshot I attached. If you want, I can attach a demo video for the same @varshith257 @Anishkagupta04

**Comment by samarsajad** [comment]
The code for patient portal existed twice just below one another. I deleted one of them as they were the same. Please take a look at the screenshot I attached with my pull request@varshith257 @Anishkagupta04

**Comment by samarsajad** [comment]
> @samarsajad Can you create a new issue for fixing the responsiveness to the patient portal?  or maybe you can go with implementing a blood test feature as it is an important one.
> 
> cc: @Anjaliavv51 Have a look and create an issue for it.

I can do both , I guess. The more the merrier.

**Comment by Anjaliavv51** [comment]
> @samarsajad Can you create a new issue for fixing the responsiveness to the patient portal?  or maybe you can go with implementing a blood test feature as it is an important one.
> 
> cc: @Anjaliavv51 Have a look and create an issue for it.

Sure

**Comment by varshith257** [comment]
@samarsajad Resolve conflicts

**Comment by samarsajad** [comment]
Resolved the conflicts @varshith257 @Anishkagupta04  Please take a look

**Pull request merged**
