### PR TITLE
✨[Feature Request]: Creating POPUP to blood types

### LINKED ISSUE #746: ✨[Feature Request]: Creating POPUP to blood types
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating POPUP to blood types  instead of redirecting another HTML page.
like below

image

### Benefits

Content will be read easily without confusion in data by searching throughtout the page in list.html

### Add ScreenShots

image

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#746

## Description

[Please include a brief description of the changes or features added]

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #746 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/98155b14-2f3e-4e07-ae2b-8f847a5a5640

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@varshith257 please review the PR.

**Review by varshith257 — APPROVED** [review]

**Comment by Anjaliavv51** [comment]
@varshith257 please add GSSOC LABEL

**Comment by varshith257** [comment]
LEVEL 3 FOR THE BETTER UI

**Comment by varshith257** [comment]
@Anjaliavv51 Raise an issue and make PR to unify and add the current navbar and footer of the home page to the blood test page

**Comment by varshith257** [comment]
See here it is diffferent

**Comment by Anjaliavv51** [comment]
@varshith257 sure

**Pull request merged**
