### PR TITLE
fixed navbar

### LINKED ISSUE #1106: ✨[Feature Request]: Restyling the navbar for responsive screens
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To position items and aligning them properly

### Use Case

To position items and aligning them properly

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ayush-848**
## Description

Fixed the navbars for various screen sizes

## Related Issues

- Closes #1106

## Screenshots / videos (if applicable)
image
fixed for 768px
image
for 820px
image
for 880px

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ayush-848** [comment]
@varshith257 please check this

**Comment by varshith257** [comment]
@Anjaliavv51 Take a look. I think existing one is also looks fine. WDYT?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 Take a look. I think existing one is also looks fine. WDYT?

Existing one is fine no need of this right nowm

**Comment by ayush-848** [comment]
> @Anjaliavv51 Take a look. I think existing one is also looks fine. WDYT?

Actually it is the existing one.
But it is not responsive for smaller screens.
I just fixed that.
I haven't added anything new

**Comment by Anjaliavv51** [comment]
> Actually it is the existing one. But it is not responsive for smaller screens. I just fixed that. I haven't added anything new

Screenshot_20240804_103858_Chrome

**Comment by ayush-848** [comment]
> > Actually it is the existing one. But it is not responsive for smaller screens. I just fixed that. I haven't added anything new
> 
> Screenshot_20240804_103858_Chrome

Here I brought the logo in center and added padding to the hamburger drop-down

**Comment by Anjaliavv51** [comment]
> > > Actually it is the existing one. But it is not responsive for smaller screens. I just fixed that. I haven't added anything new
> > 
> > 
> > Screenshot_20240804_103858_Chrome
> 
> Here I brought the logo in center and added padding to the hamburger drop-down

But it's size is decreased??? In ur changes

**Comment by ayush-848** [comment]
> > > > Actually it is the existing one. But it is not responsive for smaller screens. I just fixed that. I haven't added anything new
> > > 
> > > 
> > > Screenshot_20240804_103858_Chrome
> > 
> > 
> > Here I brought the logo in center and added padding to the hamburger drop-down
> 
> But it's size is decreased??? In ur changes

Yes but if you want, I can restore it's original size

**Comment by ayush-848** [comment]
@Anjaliavv51 should I increase the size???

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 should I increase the size???

Yes please increase the size of the navbar container in small screen.

**Comment by ayush-848** [comment]
> > @Anjaliavv51 should I increase the size???
> 
> Yes please increase the size of the navbar container in small screen.

for the 768px??

**Comment by ayush-848** [comment]
@Anjaliavv51 
image
maam can you reverify it for me, that in the 768px on clicking the hamburger the links don't appear

**Comment by Anjaliavv51** [comment]
Did u commit the code? @ayush-848

**Comment by ayush-848** [comment]
> Did u commit the code? @ayush-848

No no

**Comment by Anjaliavv51** [comment]
> > Did u commit the code? @ayush-848
> 
> No no

Once commit the code then I will check and I will mention u if any changes.

**Comment by ayush-848** [comment]
> > > Did u commit the code? @ayush-848
> > 
> > 
> > No no
> 
> Once commit the code then I will check and I will mention u if any changes.

Ok

**Comment by ayush-848** [comment]
@Anjaliavv51 
image
please check now

**Comment by Anjaliavv51** [comment]
@ayush-848 nav bar should appear when we click on the icon , but it's appearing before itself,  and also container should be wide.


Screenshot_20240804_141802_Chrome

**Comment by ayush-848** [comment]
> @ayush-848 nav bar should appear when we click on the icon , but it's appearing before itself, and also container should be wide.
> 
> Screenshot_20240804_141802_Chrome

ok

**Comment by ayush-848** [comment]
@Anjaliavv51 
image
Now check

**Comment by Anjaliavv51** [comment]
Screenshot_20240804_171427_Chrome

Please increase the container size of the navbar.

**Comment by ayush-848** [comment]
> Screenshot_20240804_171427_Chrome
> 
> Please increase the container size of the navbar in small screen

The one with home, about, news, etc??

**Comment by Anjaliavv51** [comment]
@ayush-848 that container which contains all those.

**Comment by ayush-848** [comment]
image
@Anjaliavv51 I have increased its width to 45% and increased the font size too

**Comment by ayush-848** [comment]
@Anjaliavv51 is this one ok??

**Comment by Anjaliavv51** [comment]
@varshith257 changes are not okay

**Comment by Anjaliavv51** [comment]
> Are you talking about width of navbar container?

Yes

**Pull request merged**
