### PR TITLE
Responsiveness Across Devices

### LINKED ISSUE #505: ✨[Feature Request]:  Responsive Design
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, this is Isha Prajapati,
I hope you're doing well. I'm interested in improving our website's functionality and user experience 
I'd like to request the implementation of responsive design for our healthcare platform's website. This feature will ensure that the website adapts seamlessly to various screen sizes and devices, providing users with an optimal viewing and browsing experience.
 
I am eager to contribute under GSSoC'24 and help enhance our website’s functionality and user experience. Please assign this task to me.
Thank you!

### Use Case

Imagine a user accessing our healthcare platform from their mobile device. With responsive design in place, the website will adjust its layout and content to fit the smaller screen, making it easier for the user to navigate, read information, and interact with the platform's features.

### Benefits

Improved Accessibility: Responsive design will make our website accessible to users across a wide range of devices, including smartphones, tablets, and desktop computers.
Enhanced User Experience: Users will enjoy a consistent and user-friendly experience regardless of the device they're using, leading to higher engagement and satisfaction.
Increased Reach: With a responsive website, we can reach a broader audience and attract users who prefer to access the internet on mobile devices.

Implementing responsive design is crucial for ensuring that our healthcare platform is accessible and user-friendly for all users, regardless of the device they use to access it.

### Add ScreenShots

Screenshot 2024-06-09 205816

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ishap11**
## Description
Implemented responsive design for the healthcare platform's website. This enhancement ensures that the website adapts seamlessly to various screen sizes and devices, providing an optimal viewing and browsing experience for users. The website now adjusts its layout and content to fit smaller screens, making it easier for users to navigate, read information, and interact with the platform's features on mobile devices.

## Related Issues
- Closes #505 

## Type of PR
- [x] Feature enhancement

## Checklist
- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by varshith257** [comment]
@ishap11 Resolve conflicts

**Comment by ishap11** [comment]
I'll resolve the conflicts

**Comment by varshith257** [comment]
@ishap11 Conflicts are still there

**Comment by ishap11** [comment]
I've submitted a new pull request with the changes I've made. Please take a look and review it.
Responsiveness #741"
Thank you!

**Pull request closed without merging**
