### PR TITLE
changed the footer of faq page

### LINKED ISSUE #521: 🐞[Bug]: logo in Faq.Html page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is no logo showing in Faq.html page and the upscroll button is not working and I would like to add some changes in Footer like adding links to the So, that when clicked on the Faq's it'll open Faq page or When clicked on signup It's redirected to the Signup page 

before 
image

I would Like to fix this issue 

### Expected behavior

the expected behavior, there should be a logo showing in faq page and when clicked on the links in footer page it should be directed to the concern pages and when clicked on the scrolled button it should be directed to the top page of faq's page 

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### LINKED ISSUE #628: 🐞[Bug]: Footer of the faq.html page is different from the home page footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer of the Faq.html page is different when compared to the footer of the Home page. 

### Expected behavior

footer should be same in the faq and home page 

### Add ScreenShots

before 
image
 after 
 
 
image

I would like to make changes to the footer of the faq.html page 

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by slytechiefrommagentashore**
## Description
I have changed the footer in faq page and The scrolling button is not working before I have fixed the scrolling button in faq page. I have added links in the footers of index page and faq page. The logo in Faq page is bug is fixed. 

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #628 
- Closes #521 

## Type of PR

- [X] Bug fix

## Screenshots / videos (if applicable)
before footer 
image
after footer in faq page 
image
Scroll button in faq page

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/97241435/9c70c019-62ae-46a2-b310-5a0e5af2c54d

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
There is no image showing in contact.html page I have fixed that too, now the image appears when the page is loaded.

### CODE REVIEW

**Comment by Anishkagupta04** [comment]
THANKYOU FOR YOUR CONTRIBUTION

**Comment by slytechiefrommagentashore** [comment]
Thank you for merging !!, It's my first pull request

**Comment by slytechiefrommagentashore** [comment]
Hey @Anishkagupta04 please add GSSOC'24 label and level also, to this repo!

**Comment by slytechiefrommagentashore** [comment]
Please add a GSSOC'24 label in my pull request @Anishkagupta04 @varshith257

**Pull request merged**
