### PR TITLE
Added more restrictions to Phone number and Calendar feature

### LINKED ISSUE #274: ✨[Feature Request]: Improving the Make Appointments Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently Make appointments section doesn't check for Phone numbers. Even Character or symbols input dont give error message .
Also the date option can have a calender for easy date selection.

### Use Case

Any user might not know the correct format of date input so to make it easier we can have calendar option. Also for phone number ,to avoid spamming using letters symbols we can add restrictions of number .

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by kesharwaniyanshi**
## Description

Earlier the phone number could accept anything alphabet,symbol etc and any length number . Now i have fixed that and also updated the Appointment date section .Added calendar to it for better user experience.

## Related Issues

- Closes #274

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image
image
image
image

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by kesharwaniyanshi** [comment]
> @kesharwaniyanshi I think it's better intuitive if we add strict validation of format of mobile number along with country codes and validation of phone number

So do you want me to modify it and make it in a format that it accepts country codes as well?

**Comment by kesharwaniyanshi** [comment]
image
I made required changes kindly have a look and merge my PR.

**Comment by kesharwaniyanshi** [comment]
> Can't see any changes over there in the files?

image
image
I have added a js code for country code and made some css modifications and additions to adjust it properly

**Comment by varshith257** [comment]
@kesharwaniyanshi Thanks for the contribution

**Pull request merged**
