### PR TITLE
made-input.html-responsive

### PR DESCRIPTION
**Pull request by Soujanya2004**
## Description

Made input.html page responsive to small screen
issue #894 

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X ] I have updated my branch and synced it with project `main` branch before making this PR
- [X ] I have performed a self-review of my code
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Comment by Soujanya2004** [comment]
@varshith257 made responsive, please review

**Comment by Soujanya2004** [comment]
@varshith257 please review

**Comment by varshith257** [comment]
@Soujanya2004 Can you post a video or image of latest changes done in the PR to speed up review process?

**Comment by Soujanya2004** [comment]
Screenshot (128)
this is the image with the changes made in PR for mobile view @varshith257

**Review by varshith257 — APPROVED** [review]

**Comment by Soujanya2004** [comment]
@varshith257 please add me as assignees 
and add level also.

**Pull request merged**
