### PR TITLE
Made the submit button functional

### LINKED ISSUE #703: 🐞[Bug]:  Submit button is not functional
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The feedback form is not functional . The submit button leads to nowhere

### Expected behavior

After submitting the feedback form, a message should be displayed 

### Add ScreenShots

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/0797f7bd-e195-4445-bdbf-12564aa326a0

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by samarsajad**
## Description

Added functionality to the submit button. When the submit button is clicked, it displays the messaged, "thank you for submitting your feedback" and refreshes. If the form is not filled and the submit button is clicked,it displays"Pease fill the feedback form "message

-## Closes #703 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/142666229/b4c3852f-b001-45d5-bc13-162679feb9da

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by samarsajad** [comment]
Please review my pull request @varshith257 @Anishkagupta04

**Comment by varshith257** [comment]
@samarsajad Is emoji checking is needed?
If yes, you can put a case when !emojichecked to display user to check emoji

**Comment by samarsajad** [comment]
It's already there. Check the code in the files merged @varshith257

**Comment by samarsajad** [comment]
Here is the code snippet that does what you requested

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
